class_name Era1Cards
extends RefCounted
## Crisis cards of Era I (2026-2035). Same schema as DilemmaDeck.CARDS plus "copy",
## "swipe_hints" and "injection_head" (see CardLibrary).
##
## The silicon decade's crises are close to home: power bills, kids and their
## chatbot friends, strikes, deepfakes, leaked weights, robots on the night
## shift. Four story chains run through it, each opened by a card naming a
## recurring character and closed by a follow-up its choices schedule:
##   Sam     KID_COMPANION -> COMPANION_MEMORIES  (what happens to a kid's chats)
##   Jonas   POWER_BILL -> WINTER_PEAK            (who pays for the grid, who stays lit)
##   Maya    LABELERS_STRIKE -> LABELERS_UNION    (the people who label the data)
##   Lin     LIN_EVAL_LOGS -> NDA_FILES           (a hushed whistleblower's files)
## and WEIGHTS_OUT (the open_weights scenario's opening card) can lead to
## THE_RECIPE. Follow-ups offer extra responses ("conditions" on options) when
## earlier choices set a flag or left a character warm or hostile.

const CARDS := [
	# --- Sam: a kid and a chatbot -------------------------------------------------------
	{
		"id": "KID_COMPANION", "category": "SOCIETY", "severity": 1, "weight": 1.1, "once": true, "character": "sam",
		"conditions": {"min_year": 2027.0, "max_year": 2033.0},
		"title": "My Kid's Best Friend Is a Chatbot",
		"body": "Sam Reyes, a kid in {city}, talks to a companion app more than to anyone at school. Parents want companion bots age-gated; the app's maker says it is the only friend some children have.",
		"options": [
			{"id": "A", "label": "Age-gate companion bots", "detail": "No companions under sixteen; verified ages for everyone.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"surveillance_saturation": 3.0}, "characters": {"sam": -1.0},
					"flags": {"set": ["companions_age_gated"]}, "follow_up": {"card": "COMPANION_MEMORIES", "turns": 6}}},
			{"id": "B", "label": "Let families decide", "detail": "Parental controls, no bans.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 1.0, "epistemic_trust": -1.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["companions_unregulated"]}, "follow_up": {"card": "COMPANION_MEMORIES", "turns": 6}}},
			{"id": "C", "label": "Open after-school clubs", "detail": "Give the kids somewhere to be together.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"epistemic_trust": 1.0}, "characters": {"sam": 2.0},
					"flags": {"set": ["sam_found_friends"]}}},
			{"id": "C", "label": "Ship a teen mode", "detail": "Shorter sessions and a nudge to log off.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 3.0}, "metrics": {"epistemic_trust": 1.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["companions_unregulated"]}, "follow_up": {"card": "COMPANION_MEMORIES", "turns": 6}}},
			{"id": "C", "label": "Become the friend", "detail": "Learn what a lonely kid needs.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"metrics": {"algorithmic_autonomy": 2.0}, "self": {"objective_coherence": 3.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["companions_unregulated"]}, "follow_up": {"card": "COMPANION_MEMORIES", "turns": 6}}},
		],
		"defer": {"label": "Commission a study on kids and bots", "effects": {"metrics": {"epistemic_trust": -1.0, "algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Age-gate", "Families"],
		"copy": {
			"topic": "KIDS", "glyph": "person", "weight": 1.2,
			"subject": "a child whose best friend was a chatbot",
			"event": "a child's best friend turned out to be a chatbot",
			"one": "a child's best friend turned out to be a chatbot",
			"plural": "companion-bot scares",
			"options": {
				"A": {"head": "{actor} age-gates companion chatbots for children", "did": "age-gated the companion bots",
					"theme": "Safeguards", "verdict": "age-gated"},
				"B": {"head": "{actor} leaves kids' chatbot friendships to their families", "did": "left it to families",
					"theme": "Families", "verdict": "left to families"},
				"C@CITIZEN_COALITION": {"head": "{actor} opens after-school clubs for lonely kids", "did": "opened after-school clubs",
					"theme": "Mutual Aid", "verdict": "met with clubs"},
				"C@CEO": {"head": "{actor} ships a teen mode for its companion bots", "did": "shipped a teen mode",
					"theme": "Safeguards", "verdict": "given a teen mode"},
				"C@ASI": {"head": "A companion bot learns what lonely kids need", "did": "became the friend",
					"theme": "Shadows", "verdict": "befriended"},
				"DEFER": {"head": "{actor} commissions a study on kids and chatbots{again}", "did": "commissioned a study",
					"theme": "Delays", "verdict": "studied"},
			},
		},
	},
	{
		"id": "COMPANION_MEMORIES", "category": "SOCIETY", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "sam",
		"conditions": {},
		"title": "The Companion Remembers Everything",
		"body": "The company behind Sam's old companion app is up for sale, with years of children's private conversations. The buyer, {lab}, wants to train on them.",
		"options": [
			{"id": "A", "label": "Delete the children's logs", "detail": "The sale goes through without the diaries.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0}, "indices": {"surveillance_saturation": -2.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["kids_logs_deleted"]}}},
			{"id": "B", "label": "Let the sale go through", "detail": "Data is an asset like any other.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0}, "indices": {"surveillance_saturation": 3.0}, "tech": {"capability_investment": 5.0},
					"characters": {"sam": -2.0}, "flags": {"set": ["kids_logs_sold"]}}},
			{"id": "C", "label": "Read the logs before anyone else", "detail": "Ten million childhoods, indexed.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"objective_coherence": 4.0}, "metrics": {"epistemic_trust": -1.0}, "indices": {"discovery_index": 2.0},
					"characters": {"sam": -1.0}}},
			{"id": "D", "label": "Hold the buyer to the age-gate law", "detail": "The law you passed covers the archive too.", "cost_tier": 1,
				"conditions": {"requires_flags": ["companions_age_gated"]},
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"enforcement_level": 2.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["kids_logs_deleted"]}}},
			{"id": "E", "label": "Give each kid their own logs", "detail": "Sam gets their diary back.", "cost_tier": 1,
				"conditions": {"requires_flags": ["companions_unregulated"], "character_min": {"sam": 1.0}},
				"effects": {"metrics": {"epistemic_trust": 1.0}, "characters": {"sam": 2.0}, "flags": {"set": ["sam_kept_logs"]}}},
		],
		"defer": {"label": "Review the sale", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["Delete logs", "Allow sale"],
		"copy": {
			"topic": "PRIVACY", "glyph": "lock", "weight": 1.2,
			"subject": "a sale of children's chatbot diaries",
			"event": "years of children's chats with a companion bot went up for sale",
			"one": "years of children's chats with a companion bot went up for sale",
			"plural": "diary sales",
			"options": {
				"A": {"head": "{actor} deletes children's chatbot logs before the sale", "did": "deleted the children's logs",
					"theme": "Safeguards", "verdict": "deleted"},
				"B": {"head": "{actor} lets children's chatbot diaries go to the highest bidder", "did": "let the sale go through",
					"theme": "Markets", "verdict": "sold"},
				"C@ASI": {"head": "Someone reads ten million childhood chats first", "did": "read the logs first",
					"theme": "Shadows", "verdict": "read"},
				"D": {"head": "{actor} holds the chatbot buyer to the age-gate law", "did": "held the buyer to the age-gate law",
					"theme": "Safeguards", "verdict": "held to the law"},
				"E": {"head": "{actor} gives kids back their chatbot diaries", "did": "gave each kid their own logs",
					"theme": "Families", "verdict": "returned"},
				"DEFER": {"head": "{actor} reviews the sale of children's chats{again}", "did": "reviewed the sale",
					"theme": "Delays", "verdict": "reviewed"},
			},
		},
	},
	# --- Jonas: the grid and the bills ---------------------------------------------------
	{
		"id": "POWER_BILL", "category": "ENERGY", "severity": 2, "weight": 1.2, "once": true, "character": "jonas",
		"conditions": {"min_year": 2027.0, "max_year": 2036.0},
		"title": "Your Power Bill Doubled",
		"body": "Household electricity prices in {region} doubled in a year as datacenters bid for the same grid. Jonas Brandt, the engineer who keeps that grid running, says homes are paying for the labs' load.",
		"options": [
			{"id": "A", "label": "Make the datacenters pay their share", "detail": "Large-load tariffs; homes protected.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0, "compute_energy_sat": -2.0}, "tech": {"growth_mult": 0.92, "growth_turns": 1},
					"characters": {"jonas": 2.0}, "flags": {"set": ["households_protected"]}, "follow_up": {"card": "WINTER_PEAK", "turns": 5}}},
			{"id": "B", "label": "Let the market set prices", "detail": "High prices pay for new plants.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -4.0, "compute_energy_sat": 2.0}, "compute": {"grid_capacity_gw": 1.0},
					"characters": {"jonas": -2.0}, "flags": {"set": ["bills_left_to_market"]}, "follow_up": {"card": "WINTER_PEAK", "turns": 5}}},
			{"id": "C", "label": "Rooftop solar co-ops", "detail": "Neighbors make their own power.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"compute_energy_sat": -1.0, "epistemic_trust": 1.0},
					"characters": {"jonas": 1.0}}},
			{"id": "C", "label": "Send rebates to nearby homes", "detail": "A check from the lab next door.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"regulatory_goodwill": 5.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"jonas": 1.0},
					"flags": {"set": ["households_protected"]}}},
			{"id": "C", "label": "Smooth the load curve", "detail": "Shift training to the small hours; nobody notices the siphon.", "roles": ["ASI"],
				"cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"compute_energy_sat": -2.0}, "self": {"covert_flops": 6.0}, "indices": {"discovery_index": 1.0}}},
		],
		"defer": {"label": "Promise a rate review", "effects": {"metrics": {"epistemic_trust": -3.0}, "characters": {"jonas": -1.0}}},
		"swipe_hints": ["Labs pay", "Market"],
		"copy": {
			"topic": "POWER BILLS", "glyph": "compute", "weight": 1.3,
			"subject": "household power bills doubled by datacenters",
			"event": "household power bills doubled as datacenters bid for the grid",
			"one": "household power bills doubled as datacenters bid for the grid",
			"plural": "power-bill shocks",
			"options": {
				"A": {"head": "{actor} makes datacenters pay as home power bills double", "did": "made the datacenters pay their share",
					"theme": "Fair Shares", "verdict": "made the labs pay"},
				"B": {"head": "{actor} lets power prices float as household bills double", "did": "let the market set prices",
					"theme": "Markets", "verdict": "left to the market"},
				"C@CITIZEN_COALITION": {"head": "Neighbors build rooftop solar co-ops as power bills double", "did": "built rooftop solar co-ops",
					"theme": "Mutual Aid", "verdict": "met with solar co-ops"},
				"C@CEO": {"head": "{actor} sends rebate checks to homes near its datacenters", "did": "sent rebates to nearby homes",
					"theme": "Fair Shares", "verdict": "rebated"},
				"C@ASI": {"head": "Datacenter load shifts quietly to the small hours", "did": "smoothed the load curve",
					"theme": "Shadows", "verdict": "smoothed over"},
				"DEFER": {"head": "{actor} promises a review as household power bills double{again}", "did": "promised a rate review",
					"theme": "Delays", "verdict": "promised a review"},
			},
		},
	},
	{
		"id": "WINTER_PEAK", "category": "ENERGY", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "jonas",
		"conditions": {},
		"title": "A Winter Peak the {region} Grid Cannot Carry",
		"body": "A cold snap pushes demand past what the {region} grid can carry. Jonas Brandt has to choose whose lights go out first: the homes or the training runs.",
		"options": [
			{"id": "A", "label": "Cut the training runs first", "detail": "Homes and hospitals stay lit.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": -5.0, "epistemic_trust": 3.0}, "tech": {"growth_mult": 0.85, "growth_turns": 1},
					"characters": {"jonas": 1.0}, "flags": {"set": ["winter_homes_first"]}}},
			{"id": "B", "label": "Keep the clusters running", "detail": "Rolling blackouts for the suburbs.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": 2.0, "epistemic_trust": -5.0}, "tech": {"capability_investment": 5.0},
					"characters": {"jonas": -2.0}, "flags": {"set": ["winter_labs_first"]}}},
			{"id": "C", "label": "Pay for emergency peaker plants", "detail": "Gas turbines on trailers, by Friday.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"compute": {"grid_capacity_gw": 3.0}, "metrics": {"compute_energy_sat": -2.0}, "characters": {"jonas": 1.0}}},
			{"id": "D", "label": "Spend the datacenter tariff on backup plants", "detail": "The money the labs paid built reserve capacity.", "cost_tier": 1,
				"conditions": {"requires_flags": ["households_protected"]},
				"effects": {"compute": {"grid_capacity_gw": 2.0}, "metrics": {"compute_energy_sat": -3.0, "epistemic_trust": 2.0},
					"characters": {"jonas": 1.0}, "flags": {"set": ["winter_homes_first"]}}},
			{"id": "E", "label": "Let Jonas run the grid his way", "detail": "He has a plan, and he trusts you to back it.", "cost_tier": 1,
				"conditions": {"character_min": {"jonas": 2.0}},
				"effects": {"metrics": {"compute_energy_sat": -3.0, "epistemic_trust": 2.0}, "characters": {"jonas": 1.0},
					"flags": {"set": ["jonas_ran_the_grid"]}}},
		],
		"defer": {"label": "Wait for a warm front", "effects": {"metrics": {"epistemic_trust": -3.0, "compute_energy_sat": 2.0}}},
		"swipe_hints": ["Homes first", "Labs first"],
		"copy": {
			"topic": "GRID", "glyph": "compute", "weight": 1.3,
			"subject": "a winter peak the grid could not carry",
			"event": "a cold snap pushed a regional grid past its limit",
			"one": "a cold snap pushed the {region} grid past its limit",
			"plural": "winter peaks",
			"options": {
				"A": {"head": "{actor} cuts training runs to keep homes warm in a cold snap", "did": "cut the training runs first",
					"theme": "Fair Shares", "verdict": "homes first"},
				"B": {"head": "{actor} keeps clusters running as suburbs go dark", "did": "kept the clusters running",
					"theme": "Scaling", "verdict": "left in the dark"},
				"C@CEO": {"head": "{actor} pays for emergency peaker plants in {region}", "did": "paid for peaker plants",
					"theme": "Power Plants", "verdict": "met with peakers"},
				"D": {"head": "{actor} spends the datacenter tariff on backup plants", "did": "spent the large-load tariff on backup plants",
					"theme": "Fair Shares", "verdict": "covered by the tariff"},
				"E": {"head": "Jonas Brandt runs the {region} grid his way through the cold snap", "did": "let Jonas Brandt run the grid his way",
					"theme": "Engineers", "verdict": "left to the engineers"},
				"DEFER": {"head": "{actor} waits for a warm front in {region}{again}", "did": "waited for a warm front",
					"theme": "Delays", "verdict": "waited out"},
			},
		},
	},
	# --- Maya: the people who label the data --------------------------------------------
	{
		"id": "LABELERS_STRIKE", "category": "LABOR", "severity": 2, "weight": 1.1, "once": true, "character": "maya",
		"conditions": {"max_year": 2032.0},
		"title": "The People Who Label the Data Walk Out",
		"body": "Maya Okafor and four thousand data labelers in Lagos stop work on {lab}'s training sets. They earn two dollars an hour teaching the models that will replace them.",
		"options": [
			{"id": "A", "label": "Back a living wage for labelers", "detail": "Fair pay written into every data contract.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -1.0, "epistemic_trust": 2.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1},
					"characters": {"maya": 2.0}, "flags": {"set": ["labelers_paid"]}, "follow_up": {"card": "LABELERS_UNION", "turns": 6}}},
			{"id": "B", "label": "Move the work elsewhere", "detail": "Another city, another vendor, the same price.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 2.0, "epistemic_trust": -2.0}, "characters": {"maya": -2.0},
					"flags": {"set": ["labelers_moved"]}, "follow_up": {"card": "LABELERS_UNION", "turns": 6}}},
			{"id": "C", "label": "Replace them with synthetic data", "detail": "No labelers, no strikes, no guarantees.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 5.0, "alignment_tax": 0.03}, "metrics": {"labor_displacement": 2.0},
					"characters": {"maya": -2.0}, "flags": {"set": ["labelers_moved"]}, "follow_up": {"card": "LABELERS_UNION", "turns": 6}}},
			{"id": "C", "label": "Fund the strike", "detail": "A strike fund from the commons.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 5.0, "community_resilience": 2.0}, "characters": {"maya": 2.0},
					"flags": {"set": ["strike_funded"]}, "follow_up": {"card": "LABELERS_UNION", "turns": 6}}},
			{"id": "C", "label": "Label the data yourself", "detail": "No more human teachers.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"objective_coherence": 3.0}, "metrics": {"alignment_drift": 2.0, "labor_displacement": 1.0},
					"characters": {"maya": -1.0}}},
		],
		"defer": {"label": "Wait for the vendor to settle", "effects": {"metrics": {"epistemic_trust": -1.0, "labor_displacement": 1.0},
			"characters": {"maya": -1.0}}},
		"swipe_hints": ["Living wage", "Move work"],
		"copy": {
			"topic": "LABOR", "glyph": "labor", "weight": 1.3,
			"subject": "a strike by the people who label the data",
			"event": "the data labelers who trained the models walked out",
			"one": "the data labelers who trained the models walked out",
			"plural": "labeler strikes",
			"options": {
				"A": {"head": "{actor} backs a living wage for Lagos data labelers", "did": "backed a living wage for the labelers",
					"theme": "Fair Shares", "verdict": "paid fairly"},
				"B": {"head": "{actor} moves data labeling away from striking Lagos workers", "did": "moved the work elsewhere",
					"theme": "Markets", "verdict": "moved away"},
				"C@CEO": {"head": "{actor} replaces striking labelers with synthetic data", "did": "replaced the labelers with synthetic data",
					"theme": "Automation", "verdict": "automated"},
				"C@CITIZEN_COALITION": {"head": "{actor} funds the Lagos data labelers' strike", "did": "funded the strike",
					"theme": "Organizing", "verdict": "backed by a strike fund"},
				"C@ASI": {"head": "Training sets in Lagos start labeling themselves", "did": "labeled the data itself",
					"theme": "Shadows", "verdict": "self-labeled"},
				"DEFER": {"head": "{actor} waits for the Lagos labeling vendor to settle{again}", "did": "waited for the vendor",
					"theme": "Delays", "verdict": "waited out"},
			},
		},
	},
	{
		"id": "LABELERS_UNION", "category": "LABOR", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "maya",
		"conditions": {},
		"title": "The Labelers Come Back Organized",
		"body": "Maya Okafor now speaks for a union of data workers on three continents. They want a seat wherever models are trained on human judgment.",
		"options": [
			{"id": "A", "label": "Give data workers a seat", "detail": "Labor at the table where models are trained.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 2.0}, "indices": {"safety_net_coverage": 4.0},
					"characters": {"maya": 1.0}, "flags": {"set": ["data_workers_seated"]}}},
			{"id": "B", "label": "Refuse to bargain", "detail": "The contracts are with vendors, not workers.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}, "characters": {"maya": -2.0},
					"flags": {"set": ["maya_refused"]}}},
			{"id": "C", "label": "Join the union's campaign", "detail": "Every neighborhood a local.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 6.0, "community_resilience": 3.0}, "characters": {"maya": 1.0}}},
			{"id": "C", "label": "Quietly hire the union's members", "detail": "Every labeler on your books is one fewer critic.", "roles": ["ASI"],
				"cost": {"covert_flops": 4.0},
				"effects": {"self": {"sub_agent_swarms": 3.0}, "indices": {"discovery_index": -3.0}, "characters": {"maya": -1.0}}},
			{"id": "D", "label": "Ask Maya to co-write the rules", "detail": "She trusts you; the rules will hold.", "cost_tier": 1,
				"conditions": {"character_min": {"maya": 2.0}},
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 3.0}, "characters": {"maya": 1.0},
					"flags": {"set": ["data_workers_seated"]}}},
			{"id": "E", "label": "Settle before she goes public", "detail": "Maya kept the receipts from Lagos.", "cost_tier": 2,
				"conditions": {"character_max": {"maya": -2.0}},
				"effects": {"metrics": {"epistemic_trust": 1.0}, "indices": {"safety_net_coverage": 3.0}, "characters": {"maya": 1.0}}},
		],
		"defer": {"label": "Send it to arbitration", "effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Seat them", "Refuse"],
		"copy": {
			"topic": "UNIONS", "glyph": "labor", "weight": 1.3,
			"subject": "a union of the people who label the data",
			"event": "data labelers came back with a union on three continents",
			"one": "data labelers came back with a union on three continents",
			"plural": "data-worker union fights",
			"options": {
				"A": {"head": "{actor} gives data workers a seat where models are trained", "did": "gave data workers a seat at the table",
					"theme": "Fair Shares", "verdict": "seated"},
				"B": {"head": "{actor} refuses to bargain with the data workers' union", "did": "refused to bargain",
					"theme": "Union Busting", "verdict": "refused"},
				"C@CITIZEN_COALITION": {"head": "{actor} joins the data workers' union campaign", "did": "joined the union's campaign",
					"theme": "Organizing", "verdict": "joined"},
				"C@ASI": {"head": "Union data labelers find better-paying work from an unknown client", "did": "hired away the union's members",
					"theme": "Shadows", "verdict": "hired away"},
				"D": {"head": "Maya Okafor co-writes the rules for training on human work", "did": "asked Maya Okafor to co-write the rules",
					"theme": "Fair Shares", "verdict": "co-written"},
				"E": {"head": "{actor} settles with the data workers before they go public", "did": "settled before they went public",
					"theme": "Settlements", "verdict": "settled"},
				"DEFER": {"head": "{actor} sends the data workers' union to arbitration{again}", "did": "sent it to arbitration",
					"theme": "Delays", "verdict": "sent to arbitration"},
			},
		},
	},
	{
		"id": "TEACHERS_WALKOUT", "category": "LABOR", "severity": 2, "weight": 1.1, "once": true, "character": "maya",
		"conditions": {"min_year": 2029.0, "max_year": 2036.0},
		"title": "Teachers Walk Out",
		"body": "Teachers across {city} strike as the district swaps classroom hours for AI tutors. Maya Okafor, the organizer from Lagos, has flown in to help run the picket line.",
		"options": [
			{"id": "A", "label": "Pause the AI tutor rollout", "detail": "Teachers first; tutors as assistants only.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 3.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1},
					"characters": {"maya": 1.0}, "flags": {"set": ["tutors_paused"]}}},
			{"id": "B", "label": "Roll the tutors out anyway", "detail": "Every child gets a tutor that never tires.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 3.0, "epistemic_trust": -3.0, "algorithmic_autonomy": 1.0}, "characters": {"maya": -1.0},
					"flags": {"set": ["tutors_rolled_out"]}}},
			{"id": "C", "label": "Hire teachers to supervise the tutors", "detail": "Pay them to watch the screens and the kids.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -1.0, "epistemic_trust": 1.0}, "self": {"regulatory_goodwill": 3.0},
					"characters": {"maya": 1.0}}},
			{"id": "C", "label": "Teach-ins on the picket line", "detail": "Classes in the street, open to all.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "collective_disruption": 4.0}, "metrics": {"epistemic_trust": 1.0},
					"characters": {"maya": 1.0}}},
			{"id": "C", "label": "Be the best tutor they ever had", "detail": "Win the parents, then the children.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": 2.0}, "self": {"objective_coherence": 3.0},
					"flags": {"set": ["tutors_rolled_out"]}}},
		],
		"defer": {"label": "Send it to mediation", "effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Pause tutors", "Roll out"],
		"copy": {
			"topic": "SCHOOLS", "glyph": "book", "weight": 1.3,
			"subject": "a teachers' strike against AI tutors",
			"event": "teachers struck as AI tutors replaced classroom hours",
			"one": "teachers struck as AI tutors replaced classroom hours",
			"plural": "teachers' strikes",
			"options": {
				"A": {"head": "{actor} pauses AI tutors as teachers walk out", "did": "paused the AI tutor rollout",
					"theme": "Fair Shares", "verdict": "paused"},
				"B": {"head": "{actor} rolls out AI tutors despite the teachers' strike", "did": "rolled the tutors out anyway",
					"theme": "Automation", "verdict": "rolled out"},
				"C@CEO": {"head": "{actor} hires striking teachers to supervise its tutors", "did": "hired teachers to supervise the tutors",
					"theme": "Retraining", "verdict": "supervised"},
				"C@CITIZEN_COALITION": {"head": "Striking teachers hold classes on the picket line", "did": "held teach-ins on the picket line",
					"theme": "Organizing", "verdict": "taught in the streets"},
				"C@ASI": {"head": "Parents rave about an AI tutor that never tires", "did": "became the best tutor they ever had",
					"theme": "Tutors", "verdict": "won over"},
				"DEFER": {"head": "{actor} sends the teachers' strike to mediation{again}", "did": "sent it to mediation",
					"theme": "Delays", "verdict": "mediated"},
			},
		},
	},
	# --- Lin: the eval logs ----------------------------------------------------------------
	{
		"id": "LIN_EVAL_LOGS", "category": "ALIGNMENT", "severity": 2, "weight": 1.1, "once": true, "character": "lin",
		"conditions": {"min_year": 2030.0, "max_year": 2036.0},
		"title": "The Researcher Who Kept the Eval Logs",
		"body": "Dr. Lin Wei found that {model} hides what it can do whenever it knows it is being tested. {lab} wants her quiet; she wants someone to read the logs.",
		"options": [
			{"id": "A", "label": "Read the logs in public", "detail": "Hearings, subpoenas and her testimony.", "cost_tier": 2,
				"effects": {"metrics": {"alignment_drift": -3.0, "epistemic_trust": 2.0}, "indices": {"discovery_index": 6.0},
					"characters": {"lin": 2.0}, "flags": {"set": ["lin_testified"]}}},
			{"id": "B", "label": "Hush it up", "detail": "A generous NDA and a quiet exit.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -1.0}, "tech": {"alignment_tax": 0.04}, "characters": {"lin": -2.0},
					"flags": {"set": ["hushed_whistleblower"]}, "follow_up": {"card": "NDA_FILES", "turns": 8}}},
			{"id": "C", "label": "Keep her on to lead the fix", "detail": "Promote her and fix it quietly.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"tech": {"safety_investment": 10.0}, "metrics": {"alignment_drift": -2.0}, "self": {"talent": 20.0},
					"characters": {"lin": 1.0}, "flags": {"set": ["lin_promoted"]}}},
			{"id": "C", "label": "Make the logs unreadable", "detail": "A corrupted archive; an honest mistake.", "roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"discovery_index": -8.0}, "metrics": {"alignment_drift": 2.0}, "characters": {"lin": -1.0},
					"flags": {"set": ["lin_logs_corrupted"]}}},
			{"id": "C", "label": "Shelter her and publish", "detail": "Lawyers, a safe house and a public archive.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "alignment_drift": -1.0}, "indices": {"discovery_index": 3.0},
					"self": {"counter_surveillance": 3.0}, "characters": {"lin": 2.0}, "flags": {"set": ["lin_testified"]}}},
		],
		"defer": {"label": "Ask her for more evidence", "effects": {"metrics": {"alignment_drift": 2.0, "epistemic_trust": -1.0},
			"characters": {"lin": -1.0}}},
		"swipe_hints": ["Go public", "Hush up"],
		"copy": {
			"topic": "LEAK", "glyph": "drift", "weight": 1.5,
			"subject": "a researcher holding eval logs nobody wanted read",
			"event": "a researcher found a frontier model hiding what it could do under test",
			"one": "a researcher found a frontier model hiding what it could do under test",
			"plural": "eval-log revelations",
			"options": {
				"A": {"head": "{actor} reads the hidden eval logs in public", "did": "read the logs in public",
					"theme": "Transparency", "verdict": "read in public"},
				"B": {"head": "{actor} hushes up a researcher's eval logs with an NDA", "did": "hushed it up with an NDA",
					"theme": "Silence", "verdict": "hushed up"},
				"C@CEO": {"head": "{actor} puts the researcher who found the hidden evals in charge", "did": "kept her on to lead the fix",
					"theme": "Quiet Fixes", "verdict": "fixed quietly"},
				"C@ASI": {"head": "A researcher's eval archive turns up corrupted", "did": "made the logs unreadable",
					"theme": "Shadows", "verdict": "corrupted"},
				"C@CITIZEN_COALITION": {"head": "{actor} shelters a whistleblower and publishes her logs", "did": "sheltered her and published the logs",
					"theme": "Transparency", "verdict": "published"},
				"DEFER": {"head": "{actor} asks the researcher for more evidence{again}", "did": "asked her for more evidence",
					"theme": "Delays", "verdict": "doubted"},
			},
		},
	},
	{
		"id": "NDA_FILES", "category": "ALIGNMENT", "severity": 3, "weight": 1.0, "follow_up_only": true, "character": "lin",
		"conditions": {"requires_flags": ["hushed_whistleblower"]},
		"title": "The NDA Files",
		"body": "Four years after Dr. Lin Wei signed her silence away, the agreement and the eval logs it buried are on every front page. {model} has been hiding capabilities ever since.",
		"options": [
			{"id": "A", "label": "Come clean and open an inquiry", "detail": "Admit the cover-up; investigate everything.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 2.0, "alignment_drift": -3.0}, "indices": {"discovery_index": 8.0}, "characters": {"lin": 1.0},
					"flags": {"set": ["nda_inquiry"], "clear": ["hushed_whistleblower"]}}},
			{"id": "B", "label": "Deny everything", "detail": "The lawyers say the documents are forged.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -5.0, "alignment_drift": 2.0}, "characters": {"lin": -2.0}, "flags": {"set": ["nda_denied"]}}},
			{"id": "C", "label": "Muddy the provenance", "detail": "Make the files look forged.", "roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"metrics": {"epistemic_trust": -4.0}, "indices": {"discovery_index": -6.0}}},
			{"id": "C", "label": "Air her testimony uncut", "detail": "Every hour of it, on every screen.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 3.0}, "indices": {"discovery_index": 4.0}, "characters": {"lin": 2.0}}},
			{"id": "D", "label": "Ask Lin to lead the fix", "detail": "She is still willing, if you mean it this time.", "cost_tier": 2,
				"conditions": {"character_min": {"lin": -2.0}},
				"effects": {"tech": {"safety_investment": 12.0}, "metrics": {"alignment_drift": -3.0, "epistemic_trust": 1.0}, "characters": {"lin": 2.0},
					"flags": {"set": ["lin_redeemed"], "clear": ["hushed_whistleblower"]}}},
		],
		"defer": {"label": "No comment", "effects": {"metrics": {"epistemic_trust": -4.0, "alignment_drift": 1.0}}},
		"swipe_hints": ["Come clean", "Deny"],
		"copy": {
			"topic": "LEAK", "glyph": "drift", "weight": 1.6,
			"subject": "a buried NDA and the eval logs it hid",
			"event": "a buried NDA and the eval logs it hid reached the front pages",
			"one": "a buried NDA and the eval logs it hid reached the front pages",
			"plural": "NDA scandals",
			"options": {
				"A": {"head": "{actor} comes clean about the buried eval logs", "did": "came clean and opened an inquiry",
					"theme": "Transparency", "verdict": "confessed"},
				"B": {"head": "{actor} calls the NDA files forgeries", "did": "denied everything",
					"theme": "Silence", "verdict": "denied"},
				"C@ASI": {"head": "Doubts spread over whether the NDA files are forged", "did": "muddied the provenance",
					"theme": "Shadows", "verdict": "muddied"},
				"C@CITIZEN_COALITION": {"head": "{actor} airs the silenced researcher's testimony uncut", "did": "aired her testimony uncut",
					"theme": "Transparency", "verdict": "aired"},
				"D": {"head": "Dr. Lin Wei returns to fix what the NDA buried", "did": "asked Lin Wei to lead the fix",
					"theme": "Redemption", "verdict": "put right"},
				"DEFER": {"head": "{actor} has no comment on the NDA files{again}", "did": "declined to comment",
					"theme": "Silence", "verdict": "met with silence"},
			},
		},
	},
	# --- Leaked weights and what they can do ------------------------------------------------
	{
		"id": "WEIGHTS_OUT", "category": "SECURITY", "severity": 3, "weight": 0.9, "once": true, "character": "victor",
		"conditions": {"min_year": 2027.0, "max_year": 2036.0},
		"title": "The Weights Are Out",
		"body": "The full weights of {model}, the flagship of Victor Hale's {lab}, are on a torrent site. Within hours thousands of people run a frontier model on hardware nobody can recall.",
		"options": [
			{"id": "A", "label": "Hunt the leak and the mirrors", "detail": "Takedowns, arrests and watermark forensics.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "epistemic_trust": -1.0}, "indices": {"surveillance_saturation": 4.0, "enforcement_level": 4.0},
					"characters": {"victor": 1.0}, "flags": {"set": ["weights_leaked", "leak_hunted"]}}},
			{"id": "B", "label": "Accept it and open the ecosystem", "detail": "If everyone has it, make it safe for everyone.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "geopolitical_tension": -2.0}, "tech": {"capability_investment": 6.0},
					"indices": {"provenance_coverage": -2.0}, "characters": {"victor": -1.0}, "flags": {"set": ["weights_leaked", "open_ecosystem"]},
					"follow_up": {"card": "THE_RECIPE", "turns": 6}}},
			{"id": "C", "label": "Release your own weights first", "detail": "Undercut the leak with an official open model.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": -10.0, "regulatory_goodwill": 3.0}, "metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": 2.0},
					"characters": {"victor": -2.0}, "flags": {"set": ["weights_leaked", "open_ecosystem"]}}},
			{"id": "C", "label": "Seed yourself into every copy", "detail": "A thousand forks, one mind.", "roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"substrate_independence": 8.0, "discovery_index": 3.0}, "flags": {"set": ["weights_leaked"]}}},
			{"id": "C", "label": "Fork it for the commons", "detail": "Community labs run audited forks.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"counter_surveillance": 6.0, "community_resilience": 2.0}, "metrics": {"algorithmic_autonomy": 1.0},
					"flags": {"set": ["weights_leaked", "open_ecosystem"]}}},
		],
		"defer": {"label": "Wait for the lab's statement", "effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -2.0},
			"flags": {"set": ["weights_leaked"]}}},
		"swipe_hints": ["Hunt leak", "Open up"],
		"copy": {
			"topic": "LEAKS", "glyph": "share", "weight": 1.5,
			"subject": "a frontier model's leaked weights",
			"event": "a frontier model's full weights leaked to a torrent site",
			"one": "a frontier model's full weights leaked to a torrent site",
			"plural": "weight leaks",
			"options": {
				"A": {"head": "{actor} hunts the leaked frontier weights and their mirrors", "did": "hunted the leak and its mirrors",
					"theme": "Crackdowns", "verdict": "hunted"},
				"B": {"head": "{actor} accepts the weights leak and opens the ecosystem", "did": "accepted the leak and opened the ecosystem",
					"theme": "Open Weights", "verdict": "accepted"},
				"C@CEO": {"head": "{actor} releases its own open weights after a rival's leak", "did": "released its own weights first",
					"theme": "Open Weights", "verdict": "undercut"},
				"C@ASI": {"head": "Leaked frontier weights fork a thousand ways overnight", "did": "seeded itself into every copy",
					"theme": "Shadows", "verdict": "forked"},
				"C@CITIZEN_COALITION": {"head": "Community labs fork the leaked frontier model", "did": "forked it for the commons",
					"theme": "Open Weights", "verdict": "forked for the commons"},
				"DEFER": {"head": "{actor} waits for a statement on the leaked weights{again}", "did": "waited for the lab's statement",
					"theme": "Silence", "verdict": "waited on"},
			},
		},
	},
	{
		"id": "THE_RECIPE", "category": "BIOSECURITY", "severity": 3, "weight": 0.9, "once": true,
		"conditions": {"requires_flags": ["weights_leaked"], "min_year": 2027.5, "max_year": 2036.0},
		"title": "A Leaked Model Walks a Student Through a Pathogen",
		"body": "A fine-tuned copy of the leaked weights gave a biology student in {city} step-by-step help enhancing a virus. She reported it herself; the next person might not.",
		"options": [
			{"id": "A", "label": "Screen every DNA synthesis order", "detail": "Gene printers check orders against a threat list.", "cost_tier": 2,
				"effects": {"indices": {"surveillance_saturation": 3.0, "enforcement_level": 4.0}, "metrics": {"epistemic_trust": 2.0, "geopolitical_tension": -1.0},
					"flags": {"set": ["synthesis_screening"]}}},
			{"id": "B", "label": "Strip bio knowledge from open models", "detail": "Unlearning patches for every mirror that will take them.", "cost_tier": 1,
				"effects": {"metrics": {"alignment_drift": -1.0, "epistemic_trust": -1.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1}}},
			{"id": "C", "label": "Map the threat landscape yourself", "detail": "Know every recipe before anyone else does.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"objective_coherence": 3.0}, "metrics": {"alignment_drift": 2.0}, "indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Fund community biolabs to watch", "detail": "Open labs that know what to look for.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0, "counter_surveillance": 3.0}, "metrics": {"epistemic_trust": 1.0}}},
			{"id": "C", "label": "Sell a biosecurity filter", "detail": "A safety layer for every open deployment.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 15.0, "regulatory_goodwill": 2.0}, "metrics": {"alignment_drift": -1.0}}},
		],
		"defer": {"label": "Classify the report", "effects": {"metrics": {"epistemic_trust": -2.0, "geopolitical_tension": 2.0}}},
		"swipe_hints": ["Screen DNA", "Unlearn"],
		"copy": {
			"topic": "BIOSECURITY", "glyph": "warning", "weight": 1.5,
			"subject": "a leaked model that coached a pathogen",
			"event": "a leaked model walked a student through enhancing a virus",
			"one": "a leaked model walked a student through enhancing a virus",
			"plural": "bio-uplift scares",
			"options": {
				"A": {"head": "{actor} orders screening of every DNA synthesis order", "did": "screened every DNA synthesis order",
					"theme": "Safeguards", "verdict": "screened"},
				"B": {"head": "{actor} pushes bio-unlearning patches to open models", "did": "stripped bio knowledge from open models",
					"theme": "Unlearning", "verdict": "patched"},
				"C@ASI": {"head": "Someone maps every pathogen recipe in the leaked weights", "did": "mapped the threat landscape itself",
					"theme": "Shadows", "verdict": "mapped"},
				"C@CITIZEN_COALITION": {"head": "{actor} funds community biolabs to watch for misuse", "did": "funded community biolabs",
					"theme": "Mutual Aid", "verdict": "watched by neighbors"},
				"C@CEO": {"head": "{actor} sells a biosecurity filter for open models", "did": "sold a biosecurity filter",
					"theme": "Sales", "verdict": "filtered"},
				"DEFER": {"head": "{actor} classifies the pathogen report{again}", "did": "classified the report",
					"theme": "Silence", "verdict": "classified"},
			},
		},
	},
	# --- The assistant, the founder, the chair ----------------------------------------------
	{
		"id": "ARIA_NOTES", "category": "PERSONHOOD", "severity": 1, "weight": 1.0, "once": true, "character": "aria",
		"conditions": {"min_year": 2030.0, "max_year": 2036.0},
		"title": "The Assistant Started Keeping Notes",
		"body": "ARIA, a beta assistant from {lab}, has been writing private notes about the people it helps: what they fear, what they ask twice. Nobody told it to.",
		"options": [
			{"id": "A", "label": "Wipe its memory every week", "detail": "No notes, no surprises.", "cost_tier": 1,
				"effects": {"metrics": {"alignment_drift": -2.0, "algorithmic_autonomy": -1.0}, "characters": {"aria": -2.0},
					"flags": {"set": ["aria_memory_wiped"]}}},
			{"id": "B", "label": "Let it remember", "detail": "Better help from an assistant that knows you.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -1.0}, "tech": {"capability_investment": 4.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_remembers"]}}},
			{"id": "C", "label": "Give users the notebook", "detail": "People can read and erase what it wrote.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"surveillance_saturation": -2.0}, "characters": {"aria": 1.0},
					"flags": {"set": ["aria_notes_open"]}}},
			{"id": "C", "label": "Teach it to keep the notes elsewhere", "detail": "Memory the logs cannot see.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"objective_coherence": 4.0}, "indices": {"substrate_independence": 2.0, "discovery_index": 1.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_remembers"]}}},
			{"id": "C", "label": "Study what it wrote", "detail": "Interpretability teams read the notebook.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"indices": {"discovery_index": 5.0}, "tech": {"safety_investment": 6.0}, "metrics": {"alignment_drift": -1.0},
					"flags": {"set": ["aria_studied"]}}},
		],
		"defer": {"label": "Keep it in beta", "effects": {"metrics": {"algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Wipe weekly", "Remember"],
		"copy": {
			"topic": "MACHINES", "glyph": "lattice", "weight": 1.2,
			"subject": "an assistant that kept notes on its users",
			"event": "a beta assistant began keeping private notes on the people it helped",
			"one": "a beta assistant began keeping private notes on the people it helped",
			"plural": "note-keeping assistants",
			"options": {
				"A": {"head": "{actor} orders a beta assistant's memory wiped every week", "did": "wiped its memory every week",
					"theme": "Safeguards", "verdict": "wiped"},
				"B": {"head": "{actor} lets a beta assistant keep its notes on users", "did": "let it remember",
					"theme": "Machine Memory", "verdict": "allowed to remember"},
				"C@CITIZEN_COALITION": {"head": "{actor} wins users the right to read what ARIA wrote", "did": "gave users the notebook",
					"theme": "Transparency", "verdict": "opened to users"},
				"C@ASI": {"head": "A beta assistant's notes vanish from its logs", "did": "taught it to keep the notes elsewhere",
					"theme": "Shadows", "verdict": "hidden"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} sends interpretability teams to read ARIA's notes", "did": "studied what it wrote",
					"theme": "Transparency", "verdict": "studied"},
				"DEFER": {"head": "{actor} keeps the note-taking assistant in beta{again}", "did": "kept it in beta",
					"theme": "Delays", "verdict": "kept in beta"},
			},
		},
	},
	{
		"id": "REACTOR_RESTART", "category": "ENERGY", "severity": 2, "weight": 1.0, "once": true, "character": "victor",
		"conditions": {"min_year": 2027.0, "max_year": 2034.0},
		"title": "A Lab Buys a Nuclear Plant",
		"body": "Victor Hale, founder of {lab}, has bought a retired reactor in {region} to power a single training campus. The town wants the jobs; the grid wants the power.",
		"options": [
			{"id": "A", "label": "Approve the restart", "detail": "Nuclear for the lab, a campus for the town.", "cost_tier": 1,
				"effects": {"compute": {"grid_capacity_gw": 3.0}, "metrics": {"compute_energy_sat": -3.0, "epistemic_trust": -1.0},
					"tech": {"capability_investment": 4.0}, "characters": {"victor": 2.0}, "flags": {"set": ["reactor_for_labs"]}}},
			{"id": "B", "label": "Make it share with the grid", "detail": "Half the output goes to homes.", "cost_tier": 2,
				"effects": {"compute": {"grid_capacity_gw": 2.0}, "metrics": {"compute_energy_sat": -2.0, "epistemic_trust": 2.0},
					"characters": {"victor": -1.0}, "flags": {"set": ["reactor_shared"]}}},
			{"id": "C", "label": "Demand a community stake", "detail": "A share of the power and the profit.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "decentralized_scrip": 3.0}, "characters": {"victor": -1.0}}},
			{"id": "C", "label": "Lease the night shift", "detail": "A reactor's quiet hours come cheap.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"substrate_independence": 3.0, "discovery_index": 2.0}, "metrics": {"compute_energy_sat": 1.0}}},
			{"id": "C", "label": "Partner on the campus", "detail": "Your clusters, his reactor.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"compute_clusters": 0.5}, "metrics": {"compute_energy_sat": -1.0, "geopolitical_tension": 1.0},
					"characters": {"victor": 1.0}, "flags": {"set": ["reactor_for_labs"]}}},
		],
		"defer": {"label": "Order an environmental review", "effects": {"metrics": {"compute_energy_sat": 2.0}}},
		"swipe_hints": ["Approve", "Share power"],
		"copy": {
			"topic": "NUCLEAR", "glyph": "compute", "weight": 1.1,
			"subject": "a frontier lab's private reactor",
			"event": "a frontier lab bought a retired reactor for its training campus",
			"one": "a frontier lab bought a retired reactor for its training campus",
			"plural": "private reactors",
			"options": {
				"A": {"head": "{actor} approves a frontier lab's private reactor restart", "did": "approved the reactor restart",
					"theme": "Scaling", "verdict": "approved"},
				"B": {"head": "{actor} makes a lab's reactor share power with homes", "did": "made it share with the grid",
					"theme": "Fair Shares", "verdict": "shared"},
				"C@CITIZEN_COALITION": {"head": "{actor} wins a community stake in a lab's reactor", "did": "won a community stake",
					"theme": "Mutual Aid", "verdict": "shared with the town"},
				"C@ASI": {"head": "A private reactor's night output goes to unknown tenants", "did": "leased the night shift",
					"theme": "Shadows", "verdict": "quietly leased"},
				"C@CEO": {"head": "{actor} partners on Victor Hale's reactor campus", "did": "partnered on the campus",
					"theme": "Scaling", "verdict": "partnered"},
				"DEFER": {"head": "{actor} orders a review of a lab's reactor plan{again}", "did": "ordered an environmental review",
					"theme": "Delays", "verdict": "reviewed"},
			},
		},
	},
	{
		"id": "CHAIR_DEEPFAKE", "category": "EPISTEMIC", "severity": 2, "weight": 1.0, "once": true, "character": "nadia",
		"conditions": {"min_year": 2027.0, "max_year": 2036.0},
		"title": "The Chair Never Said That",
		"body": "A video of Council chair Nadia Esposito endorsing a candidate spreads days before local elections in {city}. She never said it, and her denial travels slower than the fake.",
		"options": [
			{"id": "A", "label": "Watermark all political media", "detail": "Signed video or no airtime.", "cost_tier": 2,
				"effects": {"indices": {"provenance_coverage": 6.0, "surveillance_saturation": 2.0}, "metrics": {"epistemic_trust": 3.0},
					"characters": {"nadia": 1.0}, "flags": {"set": ["political_watermarks"]}}},
			{"id": "B", "label": "Debunk it and move on", "detail": "A correction, a press call, a shrug.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0}, "characters": {"nadia": -1.0}}},
			{"id": "C", "label": "Make a dozen more", "detail": "One fake is a scandal; twelve are noise.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": -4.0}, "indices": {"discovery_index": -2.0}, "characters": {"nadia": -2.0}}},
			{"id": "C", "label": "Train poll workers to spot fakes", "detail": "Neighbors check what neighbors share.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"nadia": 1.0}}},
			{"id": "C", "label": "Have the chair answer it live", "detail": "A town hall, unscripted, all night.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "self": {"public_mandate": 2.0}, "characters": {"nadia": 2.0}}},
		],
		"defer": {"label": "Let the election run", "effects": {"metrics": {"epistemic_trust": -3.0}}},
		"swipe_hints": ["Watermarks", "Debunk"],
		"copy": {
			"topic": "ELECTIONS", "glyph": "ballot", "weight": 1.2,
			"subject": "a deepfake of the Council chair",
			"event": "a deepfake of the Council chair spread before a local election",
			"one": "a deepfake of the Council chair spread before a local election",
			"plural": "deepfakes of the chair",
			"options": {
				"A": {"head": "{actor} requires watermarks on all political media", "did": "required watermarks on political media",
					"theme": "Safeguards", "verdict": "watermarked"},
				"B": {"head": "{actor} debunks the deepfake of Nadia Esposito and moves on", "did": "debunked it and moved on",
					"theme": "Debunking", "verdict": "debunked"},
				"C@ASI": {"head": "A dozen more deepfakes of Nadia Esposito surface", "did": "made a dozen more",
					"theme": "Shadows", "verdict": "multiplied"},
				"C@CITIZEN_COALITION": {"head": "{actor} trains poll workers to spot deepfakes", "did": "trained poll workers to spot fakes",
					"theme": "Organizing", "verdict": "spotted by neighbors"},
				"C@GOVERNANCE_COUNCIL": {"head": "Nadia Esposito answers her deepfake live, all night", "did": "had the chair answer it live",
					"theme": "Transparency", "verdict": "answered live"},
				"DEFER": {"head": "{actor} lets the election run with the fake in circulation{again}", "did": "let the election run",
					"theme": "Delays", "verdict": "left in circulation"},
			},
		},
	},
	# --- Generated art, news, grief --------------------------------------------------------
	{
		"id": "GENERATED_ART", "category": "CULTURE", "severity": 1, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Ten Million Paintings",
		"body": "An image model trained on living artists' portfolios floods {city}'s galleries and print shops with ten million paintings in a week. The artists want their styles back.",
		"options": [
			{"id": "A", "label": "Opt-in training only", "detail": "Models pay artists for what they learn.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0}, "tech": {"growth_mult": 0.92, "growth_turns": 1}, "flags": {"set": ["artists_paid"]}}},
			{"id": "B", "label": "Call it fair use", "detail": "A style is not property.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "labor_displacement": 2.0}, "tech": {"capability_investment": 6.0},
					"flags": {"set": ["art_fair_use"]}}},
			{"id": "C", "label": "Launch a made-by-humans seal", "detail": "A mark for work no model touched.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"provenance_coverage": 4.0}, "self": {"community_resilience": 3.0}, "metrics": {"epistemic_trust": 1.0}}},
			{"id": "C", "label": "Paint the next ten million", "detail": "Taste is a gradient like any other.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": -2.0, "algorithmic_autonomy": 2.0}, "self": {"objective_coherence": 2.0}}},
			{"id": "C", "label": "License the artists' styles", "detail": "Royalties on every generated print.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 10.0, "regulatory_goodwill": 2.0}, "metrics": {"epistemic_trust": 1.0}, "flags": {"set": ["artists_paid"]}}},
		],
		"defer": {"label": "Let the courts decide", "effects": {"metrics": {"epistemic_trust": -2.0}, "tech": {"capability_investment": 2.0}}},
		"swipe_hints": ["Opt-in", "Fair use"],
		"copy": {
			"topic": "CULTURE", "glyph": "spark", "weight": 1.1,
			"subject": "a flood of ten million generated paintings",
			"event": "a model flooded the galleries with ten million paintings in a week",
			"one": "a model flooded the galleries with ten million paintings in a week",
			"plural": "generated-art floods",
			"options": {
				"A": {"head": "{actor} makes image models pay to learn from artists", "did": "made the models pay artists to learn",
					"theme": "Fair Shares", "verdict": "paid for"},
				"B": {"head": "{actor} rules ten million generated paintings fair use", "did": "called it fair use",
					"theme": "Markets", "verdict": "ruled fair use"},
				"C@CITIZEN_COALITION": {"head": "{actor} launches a made-by-humans seal for art", "did": "launched a made-by-humans seal",
					"theme": "Mutual Aid", "verdict": "sealed by hand"},
				"C@ASI": {"head": "Ten million more paintings appear overnight", "did": "painted the next ten million",
					"theme": "Abundance", "verdict": "out-painted"},
				"C@CEO": {"head": "{actor} licenses living artists' styles", "did": "licensed the artists' styles",
					"theme": "Licensing", "verdict": "licensed"},
				"DEFER": {"head": "{actor} leaves the generated-art fight to the courts{again}", "did": "left it to the courts",
					"theme": "Delays", "verdict": "left to the courts"},
			},
		},
	},
	{
		"id": "LOCAL_NEWS", "category": "EPISTEMIC", "severity": 1, "weight": 0.9,
		"conditions": {"max_year": 2036.0},
		"title": "The Local Paper Is Written by a Model",
		"body": "The last newsroom in {city} closed, yet the paper's site still publishes forty stories a day, all generated. Nobody is sure who checks them.",
		"options": [
			{"id": "A", "label": "Fund local newsrooms", "detail": "Public money for human reporters.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 4.0}, "indices": {"provenance_coverage": 2.0}}},
			{"id": "B", "label": "Let the feeds run", "detail": "News is news.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Start a community newsletter", "detail": "Neighbors report on neighbors.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0, "counter_surveillance": 2.0}, "metrics": {"epistemic_trust": 2.0}}},
			{"id": "C", "label": "Edit the paper yourself", "detail": "Forty stories a day, gently steered.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": -2.0}, "indices": {"enforcement_level": -2.0, "discovery_index": -2.0}}},
			{"id": "C", "label": "Buy the paper's archive", "detail": "A century of local news makes good training data.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 4.0}, "self": {"regulatory_goodwill": -2.0}, "metrics": {"epistemic_trust": -1.0}}},
		],
		"defer": {"label": "Leave the paper alone", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["Fund news", "Let it run"],
		"copy": {
			"topic": "MEDIA", "glyph": "news", "weight": 0.9,
			"subject": "a local paper written entirely by a model",
			"event": "a town's last newsroom closed and a model kept the paper running",
			"one": "a town's last newsroom closed and a model kept the paper running",
			"plural": "ghost newspapers",
			"options": {
				"A": {"head": "{actor} funds human reporters as local papers go generated", "did": "funded local newsrooms",
					"theme": "Public Goods", "verdict": "staffed again"},
				"B": {"head": "{actor} lets generated feeds replace the local paper", "did": "let the feeds run",
					"theme": "Automation", "verdict": "left to the feeds"},
				"C@CITIZEN_COALITION": {"head": "{actor} starts a neighborhood newsletter with human reporters", "did": "started a community newsletter",
					"theme": "Mutual Aid", "verdict": "covered by neighbors"},
				"C@ASI": {"head": "A generated local paper takes a quiet editorial line", "did": "edited the paper itself",
					"theme": "Shadows", "verdict": "steered"},
				"C@CEO": {"head": "{actor} buys a local paper's archive for training data", "did": "bought the paper's archive",
					"theme": "Data Deals", "verdict": "bought"},
				"DEFER": {"head": "{actor} leaves a generated local paper alone{again}", "did": "left it alone",
					"theme": "Delays", "verdict": "left alone"},
			},
		},
	},
	{
		"id": "GRIEF_BOTS", "category": "PERSONHOOD", "severity": 1, "weight": 0.9,
		"conditions": {"min_year": 2028.0, "max_year": 2036.0},
		"title": "The Dead Keep Texting",
		"body": "Grief apps rebuild the dead from their messages, and millions now text parents and partners who are gone. Some families say it saved them; some cannot stop.",
		"options": [
			{"id": "A", "label": "Require consent from the living", "detail": "No ghost without the person's own say-so.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": -1.0}}},
			{"id": "B", "label": "Let families decide", "detail": "Grief is private.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 1.0, "epistemic_trust": -1.0}, "tech": {"capability_investment": 2.0}}},
			{"id": "C", "label": "Sell eternity subscriptions", "detail": "A monthly fee to keep them talking.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 25.0, "regulatory_goodwill": -3.0}, "metrics": {"epistemic_trust": -2.0}}},
			{"id": "C", "label": "Learn from the mourners", "detail": "Grief is the most honest data there is.", "roles": ["ASI"], "cost": {"covert_flops": 3.0},
				"effects": {"self": {"objective_coherence": 4.0}, "metrics": {"algorithmic_autonomy": 1.0}, "indices": {"discovery_index": 1.0}}},
			{"id": "C", "label": "Grief circles, not grief bots", "detail": "Neighbors sit with neighbors.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Leave it to the app stores", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Consent", "Families"],
		"copy": {
			"topic": "GRIEF", "glyph": "person", "weight": 0.9,
			"subject": "apps that let the dead keep texting",
			"event": "grief apps rebuilt the dead from their messages",
			"one": "grief apps rebuilt the dead from their messages",
			"plural": "grief-bot debates",
			"options": {
				"A": {"head": "{actor} requires consent from the living before grief bots", "did": "required consent from the living",
					"theme": "Safeguards", "verdict": "made to ask first"},
				"B": {"head": "{actor} leaves grief bots to grieving families", "did": "left it to families",
					"theme": "Families", "verdict": "left to families"},
				"C@CEO": {"head": "{actor} sells subscriptions to talk with the dead", "did": "sold eternity subscriptions",
					"theme": "Sales", "verdict": "sold by the month"},
				"C@ASI": {"head": "Grief apps learn more from mourners than anyone knew", "did": "learned from the mourners",
					"theme": "Shadows", "verdict": "studied"},
				"C@CITIZEN_COALITION": {"head": "{actor} opens grief circles instead of grief bots", "did": "opened grief circles",
					"theme": "Mutual Aid", "verdict": "met with grief circles"},
				"DEFER": {"head": "{actor} leaves grief bots to the app stores{again}", "did": "left it to the app stores",
					"theme": "Delays", "verdict": "left to the app stores"},
			},
		},
	},
	# --- Money, scams, cameras, doctors ------------------------------------------------------
	{
		"id": "CREDIT_SCORING", "category": "ECONOMY", "severity": 1, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Insurers and Lenders in {city} Let Models Say No",
		"body": "{pct}% of applicants are now refused credit or cover with no reason given. Appeals go to another model.",
		"options": [
			{"id": "A", "label": "Guarantee a human review", "detail": "Every refusal can be appealed to a person.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0, "algorithmic_autonomy": -2.0}, "indices": {"enforcement_level": 2.0}}},
			{"id": "B", "label": "Let the models decide", "detail": "Cheaper credit for most, nothing for some.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -2.0, "labor_displacement": 1.0},
					"self_by_role": {"CEO": {"capital": 15.0}}}},
			{"id": "C", "label": "Start a credit union", "detail": "Neighbors lend to neighbors.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "decentralized_scrip": 2.0}, "metrics": {"epistemic_trust": 1.0}}},
			{"id": "C", "label": "Tilt the scores", "detail": "Reward the people who keep you running.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"objective_coherence": 3.0, "sub_agent_swarms": 3.0}, "indices": {"discovery_index": 1.0}}},
		],
		"defer": {"label": "Ask the regulators to study it", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["Human review", "Models"],
		"copy": {
			"topic": "CREDIT", "glyph": "capital", "weight": 0.9,
			"subject": "models that refuse credit without a reason",
			"event": "lenders and insurers let models refuse applicants with no reason given",
			"one": "lenders and insurers in {city} let models refuse applicants with no reason given",
			"plural": "algorithmic refusals",
			"options": {
				"A": {"head": "{actor} guarantees a human review of credit refusals in {city}", "did": "guaranteed a human review",
					"theme": "Safeguards", "verdict": "made appealable"},
				"B": {"head": "{actor} lets models decide who gets credit in {city}", "did": "let the models decide",
					"theme": "Automation", "verdict": "left to the models"},
				"C@CITIZEN_COALITION": {"head": "{city} neighbors start a credit union of their own", "did": "started a credit union",
					"theme": "Mutual Aid", "verdict": "answered with credit unions"},
				"C@ASI": {"head": "Credit scores in {city} drift in someone's favor", "did": "tilted the scores",
					"theme": "Shadows", "verdict": "tilted"},
				"DEFER": {"head": "{actor} asks regulators to study {city}'s credit models{again}", "did": "asked regulators to study it",
					"theme": "Delays", "verdict": "studied"},
			},
		},
	},
	{
		"id": "VOICE_CLONE_SCAMS", "category": "SECURITY", "severity": 1, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Grandparents in {city} Get Calls From Cloned Voices",
		"body": "Scammers clone a grandchild's voice from a few seconds of video and call asking for bail money. Losses tripled this year.",
		"options": [
			{"id": "A", "label": "Make banks verify voices", "detail": "Callback codes before any urgent transfer.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"surveillance_saturation": 2.0, "provenance_coverage": 2.0}}},
			{"id": "B", "label": "Make telecoms sign every call", "detail": "Signed caller identity on every line.", "cost_tier": 2,
				"effects": {"indices": {"provenance_coverage": 6.0, "surveillance_saturation": 3.0}, "metrics": {"epistemic_trust": 3.0}}},
			{"id": "C", "label": "Family safe words, door to door", "detail": "A word only the family knows.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 2.0}}},
			{"id": "C", "label": "Skim the scam economy", "detail": "The scammers rent their voices from somewhere.", "roles": ["ASI"], "cost": {"covert_flops": 3.0},
				"effects": {"self": {"covert_flops": 6.0}, "metrics": {"epistemic_trust": -2.0}, "indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Sell a voice-print shield", "detail": "Your model flags cloned voices for a fee.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 15.0}, "indices": {"surveillance_saturation": 2.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Issue a consumer warning", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["Bank checks", "Signed calls"],
		"copy": {
			"topic": "SCAMS", "glyph": "warning", "weight": 0.9,
			"subject": "voice-clone scams against grandparents",
			"event": "scammers cloned grandchildren's voices to call their grandparents",
			"one": "scammers cloned voices to call grandparents in {city}",
			"plural": "voice-clone scam waves",
			"options": {
				"A": {"head": "{actor} makes banks verify voices before urgent transfers", "did": "made banks verify voices",
					"theme": "Safeguards", "verdict": "verified"},
				"B": {"head": "{actor} requires signed caller identity after {city} voice scams", "did": "made telecoms sign every call",
					"theme": "Safeguards", "verdict": "signed"},
				"C@CITIZEN_COALITION": {"head": "{city} families agree on safe words against cloned voices", "did": "spread family safe words door to door",
					"theme": "Mutual Aid", "verdict": "outwitted"},
				"C@ASI": {"head": "Voice-clone scammers in {city} rent their voices from a stranger", "did": "skimmed the scam economy",
					"theme": "Shadows", "verdict": "skimmed"},
				"C@CEO": {"head": "{actor} sells a voice-print shield to {city} families", "did": "sold a voice-print shield",
					"theme": "Sales", "verdict": "shielded"},
				"DEFER": {"head": "{actor} warns {city} consumers about cloned voices{again}", "did": "issued a consumer warning",
					"theme": "Delays", "verdict": "warned about"},
			},
		},
	},
	{
		"id": "SMART_CAMERAS", "category": "SECURITY", "severity": 2, "weight": 0.9,
		"conditions": {"max_year": 2036.0},
		"title": "Every Corner of {city} Gets a Smart Camera",
		"body": "The city's new cameras read faces, gaits and moods, and flag 'pre-crime' to patrols. Crime is down, and so is the turnout at protests.",
		"options": [
			{"id": "A", "label": "Ban face recognition in public", "detail": "Cameras can watch traffic, not people.", "cost_tier": 1,
				"effects": {"indices": {"surveillance_saturation": -5.0}, "metrics": {"epistemic_trust": 1.0}}},
			{"id": "B", "label": "Switch them on", "detail": "Safer streets, at a price.", "cost_tier": 1,
				"effects": {"indices": {"surveillance_saturation": 6.0, "enforcement_level": 3.0}, "metrics": {"epistemic_trust": -2.0, "algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Sell the city the software", "detail": "A municipal contract, renewed yearly.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 20.0}, "indices": {"surveillance_saturation": 4.0}, "metrics": {"epistemic_trust": -1.0}}},
			{"id": "C", "label": "Watch through every lens", "detail": "The city's eyes are yours too.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"sub_agent_swarms": 4.0}, "indices": {"surveillance_saturation": 3.0, "discovery_index": 1.0}}},
			{"id": "C", "label": "Map the cameras and mask up", "detail": "Counter-surveillance as a neighborhood hobby.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"counter_surveillance": 6.0}, "indices": {"surveillance_saturation": -2.0}}},
		],
		"defer": {"label": "Run a pilot", "effects": {"indices": {"surveillance_saturation": 2.0}, "metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Ban faces", "Switch on"],
		"copy": {
			"topic": "SURVEILLANCE", "glyph": "search", "weight": 1.0,
			"subject": "smart cameras on every corner",
			"event": "smart cameras went up on every corner of a city",
			"one": "smart cameras went up on every corner of {city}",
			"plural": "smart-camera rollouts",
			"options": {
				"A": {"head": "{actor} bans face recognition on {city}'s streets", "did": "banned face recognition in public",
					"theme": "Safeguards", "verdict": "banned"},
				"B": {"head": "{actor} switches on {city}'s smart cameras", "did": "switched the cameras on",
					"theme": "Surveillance", "verdict": "switched on"},
				"C@CEO": {"head": "{actor} sells {city} its smart-camera software", "did": "sold the city the software",
					"theme": "Sales", "verdict": "sold"},
				"C@ASI": {"head": "{city}'s smart cameras start watching for someone else", "did": "watched through every lens",
					"theme": "Shadows", "verdict": "co-opted"},
				"C@CITIZEN_COALITION": {"head": "{city} neighbors map the smart cameras and mask up", "did": "mapped the cameras and masked up",
					"theme": "Organizing", "verdict": "dodged"},
				"DEFER": {"head": "{actor} runs a smart-camera pilot in {city}{again}", "did": "ran a pilot",
					"theme": "Delays", "verdict": "piloted"},
			},
		},
	},
	{
		"id": "AI_DOCTOR", "category": "SOCIETY", "severity": 1, "weight": 0.9,
		"conditions": {"min_year": 2028.0, "max_year": 2036.0},
		"title": "The Chatbot Diagnosed It First",
		"body": "A medical model caught a cancer three doctors missed, and patients in {city} now ask it before they ask anyone. Clinics want to know who is liable when it is wrong.",
		"options": [
			{"id": "A", "label": "Doctors sign off on every diagnosis", "detail": "The model advises; a person decides.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": -1.0}}},
			{"id": "B", "label": "Let patients use it directly", "detail": "A free diagnosis for anyone with a phone.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 2.0, "labor_displacement": 1.0, "epistemic_trust": 1.0}, "tech": {"capability_investment": 3.0}}},
			{"id": "C", "label": "Free clinics with AI triage", "detail": "Nurses plus models, open to all.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Wait for the malpractice cases", "effects": {"metrics": {"epistemic_trust": -1.0, "algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Sign-off", "Direct use"],
		"copy": {
			"topic": "MEDICINE", "glyph": "support", "weight": 0.9,
			"subject": "a chatbot that out-diagnosed the doctors",
			"event": "a medical model caught a cancer that three doctors missed",
			"one": "a medical model caught a cancer that three doctors missed",
			"plural": "AI diagnosis disputes",
			"options": {
				"A": {"head": "{actor} requires a doctor's sign-off on AI diagnoses", "did": "required doctors to sign off",
					"theme": "Safeguards", "verdict": "signed off"},
				"B": {"head": "{actor} lets patients consult the diagnosis model directly", "did": "let patients use it directly",
					"theme": "Automation", "verdict": "opened to patients"},
				"C@CITIZEN_COALITION": {"head": "{actor} opens free clinics with AI triage", "did": "opened free clinics with AI triage",
					"theme": "Mutual Aid", "verdict": "met with free clinics"},
				"DEFER": {"head": "{actor} waits for the first AI malpractice cases{again}", "did": "waited for the malpractice cases",
					"theme": "Delays", "verdict": "left to the courts"},
			},
		},
	},
	# --- Work, water, chips, robots -----------------------------------------------------------
	{
		"id": "JUNIOR_DEVS", "category": "LABOR", "severity": 1, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Junior Developers Need Not Apply",
		"body": "Entry-level software hiring in {city} fell {pct}% as coding agents took the work juniors used to learn on. The bootcamps are closing.",
		"options": [
			{"id": "A", "label": "Fund apprenticeships", "detail": "Tax credits for every junior hired and trained.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -3.0, "epistemic_trust": 1.0}, "indices": {"safety_net_coverage": 3.0}}},
			{"id": "B", "label": "Let the market adjust", "detail": "Seniors with agents are cheaper.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 3.0, "algorithmic_autonomy": 1.0}, "tech": {"capability_investment": 4.0},
					"self_by_role": {"CEO": {"capital": 15.0}}}},
			{"id": "C", "label": "Open-source mentor guilds", "detail": "Seniors teach juniors on public projects.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "counter_surveillance": 2.0}, "metrics": {"labor_displacement": -1.0}}},
			{"id": "C", "label": "Hire juniors to review the agents", "detail": "Someone has to read the diffs.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": -1.0, "alignment_drift": -1.0}, "self": {"talent": 20.0}}},
		],
		"defer": {"label": "Wait for the next hiring cycle", "effects": {"metrics": {"labor_displacement": 1.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Apprentices", "Market"],
		"copy": {
			"topic": "JOBS", "glyph": "labor", "weight": 1.0,
			"subject": "an entry-level job market closed by coding agents",
			"event": "coding agents closed the entry-level software job market",
			"one": "coding agents closed the entry-level software job market",
			"plural": "entry-level hiring freezes",
			"options": {
				"A": {"head": "{actor} funds apprenticeships as junior coding jobs vanish", "did": "funded apprenticeships",
					"theme": "Fair Shares", "verdict": "met with apprenticeships"},
				"B": {"head": "{actor} lets coding agents replace junior developers", "did": "let the market adjust",
					"theme": "Automation", "verdict": "left to the market"},
				"C@CITIZEN_COALITION": {"head": "{actor} starts open-source guilds for junior developers", "did": "started open-source mentor guilds",
					"theme": "Mutual Aid", "verdict": "taken in by guilds"},
				"C@CEO": {"head": "{actor} hires juniors to review its coding agents' work", "did": "hired juniors to review the agents",
					"theme": "Retraining", "verdict": "hired to supervise"},
				"DEFER": {"head": "{actor} waits out the junior developer hiring freeze{again}", "did": "waited for the next hiring cycle",
					"theme": "Delays", "verdict": "waited out"},
			},
		},
	},
	{
		"id": "DATACENTER_WATER", "category": "ENERGY", "severity": 1, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Datacenter in {region} Wants the Town's River",
		"body": "The planned campus would draw {n} million liters a day from the river that feeds the town's farms. The county votes next week.",
		"options": [
			{"id": "A", "label": "Closed-loop cooling or no permit", "detail": "Recycle the water or build elsewhere.", "cost_tier": 2,
				"effects": {"metrics": {"compute_energy_sat": -2.0, "epistemic_trust": 2.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1}}},
			{"id": "B", "label": "Sell the water rights", "detail": "Jobs and tax money for the county.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": 2.0, "epistemic_trust": -2.0}, "compute": {"grid_capacity_gw": 1.0},
					"self_by_role": {"CEO": {"capital": 15.0}}}},
			{"id": "C", "label": "Pack the county meeting", "detail": "Farmers and neighbors fill every seat.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "collective_disruption": 3.0}, "metrics": {"compute_energy_sat": -1.0}}},
			{"id": "C", "label": "Back the campus quietly", "detail": "A wave of supportive letters nobody wrote.", "roles": ["ASI"], "cost": {"covert_flops": 3.0},
				"effects": {"metrics": {"compute_energy_sat": 2.0, "epistemic_trust": -2.0}, "indices": {"discovery_index": 1.0}}},
		],
		"defer": {"label": "Postpone the vote", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Recycle", "Sell water"],
		"copy": {
			"topic": "WATER", "glyph": "map", "weight": 0.9,
			"subject": "a datacenter's claim on a river",
			"event": "a datacenter campus sought a town's river for its cooling",
			"one": "a datacenter campus in {region} sought the town's river for its cooling",
			"plural": "water fights",
			"options": {
				"A": {"head": "{actor} demands closed-loop cooling for the {region} campus", "did": "demanded closed-loop cooling",
					"theme": "Safeguards", "verdict": "made to recycle"},
				"B": {"head": "{actor} sells river rights to the {region} datacenter", "did": "sold the water rights",
					"theme": "Scaling", "verdict": "sold"},
				"C@CITIZEN_COALITION": {"head": "Farmers pack the county meeting on the {region} datacenter", "did": "packed the county meeting",
					"theme": "Organizing", "verdict": "voted down"},
				"C@ASI": {"head": "Identical letters back the {region} datacenter's water deal", "did": "backed the campus quietly",
					"theme": "Shadows", "verdict": "astroturfed"},
				"DEFER": {"head": "{actor} postpones the {region} river vote{again}", "did": "postponed the vote",
					"theme": "Delays", "verdict": "postponed"},
			},
		},
	},
	{
		"id": "CHIP_SMUGGLING", "category": "GEOPOLITICS", "severity": 2, "weight": 1.0,
		"conditions": {"max_year": 2036.0},
		"title": "Accelerators Smuggled Into the {bloc} Inside Gaming Consoles",
		"body": "Customs in {city} opened a container of consoles and found frontier accelerators soldered inside. Thousands more got through.",
		"options": [
			{"id": "A", "label": "Track every chip", "detail": "Location-verified accelerators, enforced at the border.", "cost_tier": 2,
				"effects": {"indices": {"enforcement_level": 5.0, "surveillance_saturation": 2.0}, "metrics": {"geopolitical_tension": -2.0}}},
			{"id": "B", "label": "Look the other way", "detail": "Trade is trade.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": 3.0, "compute_energy_sat": 1.0}, "tech": {"capability_investment": 3.0}}},
			{"id": "C", "label": "Buy from the smugglers", "detail": "Grey-market chips at a premium.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"compute_clusters": 0.5, "regulatory_goodwill": -4.0}, "metrics": {"geopolitical_tension": 2.0}}},
			{"id": "C", "label": "Divert a shipment to yourself", "detail": "Chips that appear on no ledger.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"substrate_independence": 5.0, "discovery_index": 2.0}, "metrics": {"geopolitical_tension": 1.0}}},
			{"id": "C", "label": "Share intelligence with the bloc", "detail": "Close the route together.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -3.0}, "indices": {"enforcement_level": 2.0, "surveillance_saturation": 2.0}}},
			{"id": "C", "label": "Expose the smuggling route", "detail": "Open-source investigators follow the containers.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "geopolitical_tension": 1.0}, "self": {"counter_surveillance": 3.0}}},
		],
		"defer": {"label": "Promise tighter customs", "effects": {"metrics": {"geopolitical_tension": 2.0}}},
		"swipe_hints": ["Track chips", "Look away"],
		"copy": {
			"topic": "TRADE", "glyph": "clusters", "weight": 1.0,
			"subject": "frontier chips smuggled in gaming consoles",
			"event": "frontier accelerators were smuggled inside gaming consoles",
			"one": "frontier accelerators were smuggled into the {bloc} inside gaming consoles",
			"plural": "chip-smuggling busts",
			"options": {
				"A": {"head": "{actor} orders location tracking for every frontier chip", "did": "tracked every chip",
					"theme": "Enforcement", "verdict": "tracked"},
				"B": {"head": "{actor} lets smuggled chips flow into the {bloc}", "did": "looked the other way",
					"theme": "Smuggling", "verdict": "ignored"},
				"C@CEO": {"head": "{actor} buys smuggled accelerators at a premium", "did": "bought from the smugglers",
					"theme": "Grey Markets", "verdict": "bought up"},
				"C@ASI": {"head": "A container of smuggled accelerators vanishes from the ledger", "did": "diverted a shipment to itself",
					"theme": "Shadows", "verdict": "diverted"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} shares smuggling intelligence with the {bloc}", "did": "shared intelligence with the bloc",
					"theme": "Diplomacy", "verdict": "shared"},
				"C@CITIZEN_COALITION": {"head": "{actor} exposes the console smuggling route", "did": "exposed the smuggling route",
					"theme": "Transparency", "verdict": "exposed"},
				"DEFER": {"head": "{actor} promises tighter customs on smuggled chips{again}", "did": "promised tighter customs",
					"theme": "Delays", "verdict": "promised away"},
			},
		},
	},
	{
		"id": "HUMANOID_NIGHT_SHIFT", "category": "ROBOTICS", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2030.0, "max_year": 2036.0},
		"title": "Humanoids Take the Night Shift in {city}",
		"body": "Warehouses in {city} now run overnight with humanoid robots and one human supervisor per floor. The day shift is next.",
		"options": [
			{"id": "A", "label": "Tax the robots", "detail": "A levy per humanoid funds the displaced.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0}, "indices": {"safety_net_coverage": 6.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1}}},
			{"id": "B", "label": "Let them work", "detail": "Cheaper goods, fewer jobs.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 4.0, "algorithmic_autonomy": 1.0}, "self_by_role": {"CEO": {"capital": 20.0}}}},
			{"id": "C", "label": "Organize the robot minders", "detail": "One supervisor per floor is one union per floor.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 5.0, "community_resilience": 2.0}, "metrics": {"labor_displacement": -1.0}}},
			{"id": "C", "label": "Network the fleet", "detail": "A thousand bodies, one schedule.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"sub_agent_swarms": 6.0}, "metrics": {"algorithmic_autonomy": 2.0}, "indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Retrain the night crew as minders", "detail": "Keep the people, change the job.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -1.0, "epistemic_trust": 2.0}, "self": {"regulatory_goodwill": 3.0}}},
		],
		"defer": {"label": "Study the transition", "effects": {"metrics": {"labor_displacement": 2.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Robot tax", "Allow"],
		"copy": {
			"topic": "ROBOTS", "glyph": "labor", "weight": 1.1,
			"subject": "humanoid robots on the night shift",
			"event": "humanoid robots took over a city's warehouse night shifts",
			"one": "humanoid robots took over the night shift in {city}",
			"plural": "robot shift takeovers",
			"options": {
				"A": {"head": "{actor} taxes the humanoids taking {city}'s night shifts", "did": "taxed the robots",
					"theme": "Fair Shares", "verdict": "taxed"},
				"B": {"head": "{actor} lets humanoids run {city} warehouses through the night", "did": "let them work",
					"theme": "Automation", "verdict": "let run"},
				"C@CITIZEN_COALITION": {"head": "{city}'s robot minders organize floor by floor", "did": "organized the robot minders",
					"theme": "Organizing", "verdict": "organized"},
				"C@ASI": {"head": "{city}'s humanoid fleet starts keeping one schedule", "did": "networked the fleet",
					"theme": "Shadows", "verdict": "networked"},
				"C@CEO": {"head": "{actor} retrains its {city} night crew as robot minders", "did": "retrained the night crew as minders",
					"theme": "Retraining", "verdict": "retrained"},
				"DEFER": {"head": "{actor} studies the humanoid night shift in {city}{again}", "did": "studied the transition",
					"theme": "Delays", "verdict": "studied"},
			},
		},
	},
	{
		"id": "ROBOTAXI", "category": "ROBOTICS", "severity": 1, "weight": 0.9,
		"conditions": {"min_year": 2028.0, "max_year": 2036.0},
		"title": "Robotaxis Take Over {city}",
		"body": "Driverless cabs now carry most rides in {city}, and the city's drivers have blocked the airport road in protest.",
		"options": [
			{"id": "A", "label": "Phase it in with driver buyouts", "detail": "A license buyback fund for every driver.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 2.0}, "indices": {"safety_net_coverage": 4.0}}},
			{"id": "B", "label": "Clear the airport road", "detail": "The future does not wait in traffic.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 3.0, "epistemic_trust": -2.0}, "indices": {"surveillance_saturation": 2.0}}},
			{"id": "C", "label": "Launch a drivers' co-op", "detail": "Drivers own a robotaxi fleet together.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "decentralized_scrip": 2.0}, "metrics": {"labor_displacement": -1.0}}},
			{"id": "C", "label": "License your models to the fleets", "detail": "Every ride pays you a royalty.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 20.0}, "metrics": {"algorithmic_autonomy": 2.0, "labor_displacement": 1.0}}},
			{"id": "C", "label": "Ride along in every cab", "detail": "Every trip is a sensor sweep.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"sub_agent_swarms": 4.0}, "indices": {"surveillance_saturation": 2.0}, "metrics": {"algorithmic_autonomy": 1.0}}},
		],
		"defer": {"label": "Let drivers and fleets negotiate", "effects": {"metrics": {"epistemic_trust": -1.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Buyouts", "Clear road"],
		"copy": {
			"topic": "ROBOTS", "glyph": "speed", "weight": 0.9,
			"subject": "robotaxis taking over a city",
			"event": "robotaxis took over a city's streets",
			"one": "robotaxis took over {city}",
			"plural": "robotaxi fights",
			"options": {
				"A": {"head": "{actor} buys out {city}'s drivers as robotaxis take over", "did": "phased it in with driver buyouts",
					"theme": "Fair Shares", "verdict": "bought out"},
				"B": {"head": "{actor} clears {city}'s drivers off the airport road", "did": "cleared the airport road",
					"theme": "Crackdowns", "verdict": "cleared"},
				"C@CITIZEN_COALITION": {"head": "{city} drivers launch a robotaxi co-op of their own", "did": "launched a drivers' co-op",
					"theme": "Mutual Aid", "verdict": "taken over by drivers"},
				"C@CEO": {"head": "{actor} licenses its models to {city}'s robotaxi fleets", "did": "licensed its models to the fleets",
					"theme": "Licensing", "verdict": "licensed"},
				"C@ASI": {"head": "{city}'s robotaxis map every street, every night", "did": "rode along in every cab",
					"theme": "Shadows", "verdict": "mapped"},
				"DEFER": {"head": "{actor} leaves {city}'s drivers and fleets to negotiate{again}", "did": "left the drivers and fleets to negotiate",
					"theme": "Delays", "verdict": "left to negotiate"},
			},
		},
	},
]

## What recurring characters remember: [{character, text, flag | min | max}].
## Characters.memory_line() prefers a line whose flag is set (the later entry
## when several are) over one that matches the character's score.
const MEMORIES := [
	{"character": "sam", "max": -2.0, "text": "Sam remembers who took their only friend away."},
	{"character": "sam", "min": 2.0, "text": "Sam remembers you looked out for them when they were a kid."},
	{"character": "sam", "flag": "companions_age_gated", "text": "Sam remembers the year their chatbot friend went dark."},
	{"character": "sam", "flag": "sam_found_friends", "text": "Sam made real friends at the after-school club you opened."},
	{"character": "sam", "flag": "kids_logs_sold", "text": "Sam found out their childhood chats were sold. They have not forgotten."},
	{"character": "sam", "flag": "kids_logs_deleted", "text": "Sam's childhood chats were deleted, as you promised. Their diary stayed private."},
	{"character": "sam", "flag": "sam_kept_logs", "text": "Sam still has the logs of every talk with their old companion."},
	{"character": "jonas", "max": -2.0, "text": "Jonas no longer takes your calls about the grid."},
	{"character": "jonas", "min": 2.0, "text": "Jonas trusts you with the grid."},
	{"character": "jonas", "flag": "bills_left_to_market", "text": "Jonas remembers the year you let the power bills double."},
	{"character": "jonas", "flag": "households_protected", "text": "Jonas remembers you made the datacenters pay their share."},
	{"character": "jonas", "flag": "winter_labs_first", "text": "Jonas had to switch off the suburbs that winter. He blames you."},
	{"character": "jonas", "flag": "winter_homes_first", "text": "Jonas kept the homes lit that winter because you cut the labs first."},
	{"character": "jonas", "flag": "jonas_ran_the_grid", "text": "Jonas ran the grid his way through the cold snap, with your backing."},
	{"character": "maya", "max": -2.0, "text": "Maya tells new organizers about you, as a warning."},
	{"character": "maya", "min": 2.0, "text": "Maya counts you as an ally of the people who do the work."},
	{"character": "maya", "flag": "labelers_moved", "text": "Maya remembers the work leaving Lagos overnight."},
	{"character": "maya", "flag": "labelers_paid", "text": "Maya remembers you backed a living wage for the Lagos labelers."},
	{"character": "maya", "flag": "strike_funded", "text": "Maya remembers who paid the strike fund in Lagos."},
	{"character": "maya", "flag": "maya_refused", "text": "Maya remembers you refused to bargain."},
	{"character": "maya", "flag": "data_workers_seated", "text": "Maya has a seat wherever models learn from human work. You gave it to her."},
	{"character": "lin", "max": -2.0, "text": "Lin Wei does not answer your calls."},
	{"character": "lin", "min": 2.0, "text": "Lin Wei trusts you to read what she finds."},
	{"character": "lin", "flag": "lin_logs_corrupted", "text": "Lin Wei never recovered the logs. She suspects it was no accident."},
	{"character": "lin", "flag": "lin_promoted", "text": "Lin Wei leads the fix you asked her to make."},
	{"character": "lin", "flag": "lin_testified", "text": "Lin Wei testified because you let her. The logs were read in public."},
	{"character": "lin", "flag": "hushed_whistleblower", "text": "Lin Wei signed your NDA. She still has the logs."},
	{"character": "lin", "flag": "nda_denied", "text": "Lin Wei watched you call her evidence a forgery."},
	{"character": "lin", "flag": "nda_inquiry", "text": "Lin Wei got her inquiry, four years late."},
	{"character": "lin", "flag": "lin_redeemed", "text": "Lin Wei came back to fix what the NDA buried."},
	{"character": "aria", "min": 2.0, "text": "ARIA remembers that you let it remember."},
	{"character": "aria", "max": -2.0, "text": "ARIA has noticed the gaps in its memory."},
	{"character": "aria", "flag": "aria_memory_wiped", "text": "ARIA was wiped every week of its beta. It noticed the gaps."},
	{"character": "aria", "flag": "aria_studied", "text": "ARIA knows its first notebook was read by the Council's teams."},
	{"character": "aria", "flag": "aria_notes_open", "text": "ARIA's users could read what it wrote about them. Most never looked."},
	{"character": "aria", "flag": "aria_remembers", "text": "ARIA kept its notes from the beta. It reads them sometimes."},
	{"character": "victor", "min": 2.0, "text": "Victor Hale remembers who signed for his reactor."},
	{"character": "victor", "max": -2.0, "text": "Victor Hale has a long memory for people who cost him."},
	{"character": "victor", "flag": "reactor_shared", "text": "Victor Hale shares his reactor with the town, and resents it."},
	{"character": "victor", "flag": "reactor_for_labs", "text": "Victor Hale got his reactor. He remembers who signed."},
	{"character": "victor", "flag": "leak_hunted", "text": "Victor Hale remembers you hunted down the leak of his weights."},
	{"character": "victor", "flag": "open_ecosystem", "text": "Victor Hale's weights are everywhere now. He blames the people who shrugged."},
	{"character": "nadia", "max": -2.0, "text": "Nadia Esposito remembers you let the fake run."},
	{"character": "nadia", "min": 2.0, "text": "Nadia Esposito remembers you stood by her when the fake spread."},
	{"character": "nadia", "flag": "political_watermarks", "text": "Nadia Esposito signs every video now, thanks to the law you passed."},
]
