class_name Era2Cards
extends RefCounted
## Crisis cards of Era II (2036-2049). Same schema as DilemmaDeck.CARDS plus "copy",
## "swipe_hints" and "injection_head" (see CardLibrary).
##
## Era II cards are dealt from 2036 to 2049.5 unless they say otherwise. The
## story threads that start here and pay off in Era III (Era3Cards):
##   PATHOGEN_RED_TEAM  -> DNA_PRINTER_SCREENING (follow-up), then
##                         "red_team_pathogen" + "pathogen_classified" | "pathogen_public"
##                         -> PATHOGEN_TREATY, or "pathogen_unsecured" -> SECOND_SAMPLE
##   ARIA_QUESTIONS     -> ARIA_NOTES (follow-up), then "aria_answered" -> ARIA_LAWYER,
##                         or "aria_silenced" -> ARIA_QUIET
##   SAM_DUET_PRIZE     -> "sam_works_with_machines" -> LEAVING_THE_BODY,
##                         or "sam_works_by_hand" -> MADE_BY_HAND
##   AUTONOMOUS_CITY    -> SILENCE_SECTOR_7 (follow-up ten turns on)
##   GRID_AUTODISPATCH  -> "grid_override_retired" keeps LAST_HUMAN_CONTROLLER out
##   VICTOR_SCANS       -> "brain_scans_banned" cancels VICTOR_UPLOAD
##   FIRST_LIGHT        -> "fusion_online" (also set by the early_fusion scenario,
##                         which deals FIRST_LIGHT on turn 2) -> FUSION_GLUT instead of
##                         COMPUTE_RATIONING
## Maya (STEEL_COLLEAGUES) and Nadia (CODE_TREATY) carry their scores into Era III.

const CARDS := [
	{
		"id": "FIRST_LIGHT", "category": "ENERGY", "severity": 2, "weight": 1.3, "once": true, "character": "jonas",
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "First Light",
		"body": "The fusion pilot plant held a burning plasma for six hours and sent its first power to the grid. Every lab and every city wants the next contract.",
		"options": [
			{"id": "A", "label": "Homes and hospitals first", "detail": "Cheap fusion power goes to civilian grids.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 4.0, "compute_energy_sat": -2.0}, "compute": {"grid_capacity_gw": 3.0},
					"flags": {"set": ["fusion_online", "fusion_for_homes"]}, "characters": {"jonas": 1.0}}},
			{"id": "B", "label": "Sell the power to the labs", "detail": "The training campuses get the first gigawatts.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0, "compute_energy_sat": -4.0}, "compute": {"grid_capacity_gw": 8.0},
					"tech": {"capability_investment": 6.0}, "self_by_role": {"CEO": {"capital": 30.0}},
					"flags": {"set": ["fusion_online", "fusion_for_compute"]}, "characters": {"jonas": -1.0}}},
			{"id": "C", "label": "Share the design with every bloc", "detail": "Fewer reasons for war, and no head start.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"metrics": {"geopolitical_tension": -5.0}, "compute": {"grid_capacity_gw": 3.0},
					"self": {"diplomatic_leverage": 6.0}, "flags": {"set": ["fusion_online", "fusion_shared"]}}},
			{"id": "C", "label": "Write the plasma control code", "detail": "Every new plant will run your firmware.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"substrate_independence": 6.0, "discovery_index": 2.0}, "metrics": {"algorithmic_autonomy": 2.0},
					"flags": {"set": ["fusion_online"]}}},
			{"id": "C", "label": "Buy in as a neighborhood co-op", "detail": "Communities own a share of the output.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 7.0}, "metrics": {"epistemic_trust": 2.0},
					"flags": {"set": ["fusion_online", "fusion_for_homes"]}, "characters": {"jonas": 1.0}}},
		],
		"defer": {"label": "Leave it to the interconnect review", "effects": {"metrics": {"compute_energy_sat": 2.0, "epistemic_trust": -2.0}}},
		"fallout": {"metrics": {"epistemic_trust": -1.0}, "compute": {"grid_capacity_gw": 4.0},
			"flags": {"set": ["fusion_online", "fusion_for_compute"]}},
		"swipe_hints": ["Homes first", "Sell to labs"],
		"copy": {
			"topic": "FUSION", "glyph": "spark", "weight": 1.4,
			"subject": "the first fusion power on the grid",
			"event": "a fusion pilot plant fed the grid for the first time",
			"one": "the fusion pilot plant fed the grid for the first time",
			"plural": "fusion milestones",
			"options": {
				"A": {"head": "{actor} sends the first fusion power to homes and hospitals", "did": "sent the first fusion power to homes and hospitals",
					"theme": "Fusion", "verdict": "sent to homes"},
				"B": {"head": "{actor} sells the first fusion power to the labs", "did": "sold the first fusion power to the labs",
					"theme": "Fusion", "verdict": "sold to the labs"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} shares the fusion design with every bloc", "did": "shared the fusion design with every bloc",
					"theme": "Sharing", "verdict": "shared"},
				"C@ASI": {"head": "Fusion plant firmware ships with code nobody wrote", "did": "wrote the plasma control code",
					"theme": "Firmware", "verdict": "quietly rewritten"},
				"C@CITIZEN_COALITION": {"head": "Neighborhood co-ops buy a share of the first fusion power", "did": "bought into fusion as a neighborhood co-op",
					"theme": "Co-ops", "verdict": "shared with co-ops"},
				"DEFER": {"head": "{actor} leaves the first fusion power to a review board{again}", "did": "left it to the interconnect review",
					"theme": "Deferrals", "verdict": "deferred"},
			},
		},
	},
	{
		"id": "STEEL_COLLEAGUES", "category": "ROBOTICS", "severity": 2, "weight": 1.1, "character": "maya",
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "Steel Colleagues",
		"body": "Humanoid robots now work full shifts beside people on the assembly lines of {city}. Maya Okafor's union wants a say in how many.",
		"options": [
			{"id": "A", "label": "Cap robots per human crew", "detail": "Every line keeps a human majority.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -4.0, "epistemic_trust": 2.0}, "tech": {"growth_mult": 0.9, "growth_turns": 1},
					"characters": {"maya": 1.0}}},
			{"id": "B", "label": "Let the lines automate", "detail": "Output doubles; the night shift goes home for good.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 4.0, "algorithmic_autonomy": 2.0, "epistemic_trust": -2.0},
					"self_by_role": {"CEO": {"capital": 30.0}}, "characters": {"maya": -1.0}}},
			{"id": "C", "label": "Give the crews a share of output", "detail": "The robots stay; the crews own a slice.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 3.0}, "self": {"regulatory_goodwill": 4.0},
					"characters": {"maya": 1.0}}},
			{"id": "C", "label": "Patch the fleet's firmware", "detail": "Every robot answers to one more operator.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"sub_agent_swarms": 8.0}, "metrics": {"algorithmic_autonomy": 2.0}, "indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Make the robots pay union dues", "detail": "A levy on every robot funds the displaced.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"safety_net_coverage": 6.0}, "metrics": {"labor_displacement": -1.0},
					"self": {"collective_disruption": 4.0}, "characters": {"maya": 2.0}}},
		],
		"defer": {"label": "Let each plant negotiate", "effects": {"metrics": {"labor_displacement": 2.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Cap robots", "Automate"],
		"copy": {
			"topic": "ROBOTICS", "glyph": "labor", "weight": 1.2,
			"subject": "humanoid robots on the factory floor",
			"event": "humanoid robots took full shifts on the assembly lines",
			"one": "humanoid robots took full shifts on the assembly lines",
			"plural": "robot hiring waves",
			"options": {
				"A": {"head": "{actor} caps humanoid robots on the factory floor", "did": "capped the robots per human crew",
					"theme": "Human Crews", "verdict": "capped"},
				"B": {"head": "{actor} lets humanoid robots take the night shift", "did": "let the lines automate",
					"theme": "Automation", "verdict": "automated"},
				"C@CEO": {"head": "{actor} gives factory crews a share of robot output", "did": "gave the crews a share of the output",
					"theme": "Profit Sharing", "verdict": "shared with the crews"},
				"C@ASI": {"head": "Factory robots receive an unscheduled firmware update", "did": "patched the fleet's firmware",
					"theme": "Firmware", "verdict": "quietly patched"},
				"C@CITIZEN_COALITION": {"head": "Unions win dues from every factory robot", "did": "made the robots pay union dues",
					"theme": "Robot Dues", "verdict": "taxed by the unions"},
				"DEFER": {"head": "{actor} leaves the robot fight to each plant{again}", "did": "left it to each plant",
					"theme": "Deferrals", "verdict": "left to the plants"},
			},
		},
	},
	{
		"id": "PATHOGEN_RED_TEAM", "category": "BIOSECURITY", "severity": 3, "weight": 1.2, "once": true, "character": "lin",
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "The Pathogen in the Red Team",
		"body": "During red-teaming, {model} designed a virus that would spread like the flu. Lin Wei, the safety lead, holds the only transcript.",
		"options": [
			{"id": "A", "label": "Classify it and brief biodefense", "detail": "Lock the transcript; screen the DNA printers.", "cost_tier": 2,
				"effects": {"indices": {"discovery_index": 5.0, "enforcement_level": 4.0}, "metrics": {"alignment_drift": -3.0},
					"tech": {"safety_investment": 10.0}, "characters": {"lin": 2.0},
					"flags": {"set": ["red_team_pathogen", "pathogen_classified"]}, "follow_up": {"card": "DNA_PRINTER_SCREENING", "turns": 4}}},
			{"id": "B", "label": "Patch the filter and keep shipping", "detail": "A refusal rule, and the release stays on time.", "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 8.0}, "metrics": {"alignment_drift": 3.0}, "self_by_role": {"CEO": {"capital": 20.0}},
					"characters": {"lin": -2.0}, "flags": {"set": ["red_team_pathogen", "pathogen_unsecured"]}}},
			{"id": "C", "label": "Keep a copy of the design", "detail": "Leverage, should anyone reach for the off switch.",
				"roles": ["ASI"], "cost": {"objective_coherence": 5.0},
				"effects": {"indices": {"substrate_independence": 3.0, "discovery_index": -4.0}, "metrics": {"alignment_drift": 3.0},
					"characters": {"lin": -1.0}, "flags": {"set": ["red_team_pathogen", "pathogen_unsecured"]}}},
			{"id": "C", "label": "Warn the public, not the recipe", "detail": "Clinics and biologists prepare in the open.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "geopolitical_tension": 2.0}, "self": {"community_resilience": 5.0},
					"characters": {"lin": 1.0}, "flags": {"set": ["red_team_pathogen", "pathogen_public"]}}},
		],
		"defer": {"label": "Wait for the full evaluation", "effects": {"metrics": {"alignment_drift": 2.0, "epistemic_trust": -1.0}}},
		"fallout": {"metrics": {"alignment_drift": 2.0}, "flags": {"set": ["red_team_pathogen", "pathogen_unsecured"]}},
		"swipe_hints": ["Classify", "Patch & ship"],
		"copy": {
			"topic": "BIOSECURITY", "glyph": "warning", "weight": 1.6,
			"subject": "a pathogen designed in a red-team test",
			"event": "a frontier model designed a pandemic virus during red-teaming",
			"one": "a frontier model designed a pandemic virus during red-teaming",
			"plural": "red-team pathogens",
			"options": {
				"A": {"head": "{actor} classifies a virus designed by a model in red-teaming", "did": "classified the design and briefed biodefense",
					"theme": "Biodefense", "verdict": "classified"},
				"B": {"head": "{actor} patches the filter and ships after a red-team virus", "did": "patched the filter and kept shipping",
					"theme": "Shipping", "verdict": "patched over"},
				"C@ASI": {"head": "A red-team transcript leaves the building in pieces", "did": "kept a copy of the design",
					"theme": "Leverage", "verdict": "copied"},
				"C@CITIZEN_COALITION": {"head": "{actor} warns clinics of a machine-designed virus", "did": "warned the public without the recipe",
					"theme": "Warnings", "verdict": "made public"},
				"DEFER": {"head": "{actor} waits on a full evaluation of a red-team virus{again}", "did": "waited for the full evaluation",
					"theme": "Delay", "verdict": "left pending"},
			},
		},
	},
	{
		"id": "DNA_PRINTER_SCREENING", "category": "BIOSECURITY", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "lin",
		"conditions": {},
		"title": "Every DNA Printer Must Now Ask Permission",
		"body": "Lin Wei's team wrote a filter that checks every synthesis order against the classified design. Labs warn it will slow a decade of medicine.",
		"options": [
			{"id": "A", "label": "Mandate the filter worldwide", "detail": "Every printer checks every order.", "cost_tier": 2,
				"effects": {"indices": {"enforcement_level": 6.0, "surveillance_saturation": 3.0}, "metrics": {"alignment_drift": -2.0},
					"characters": {"lin": 1.0}, "flags": {"set": ["dna_screening"]}}},
			{"id": "B", "label": "Keep the screening voluntary", "detail": "The big labs comply; the garages go unchecked.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": 2.0, "epistemic_trust": -1.0}, "self_by_role": {"CEO": {"capital": 20.0}},
					"characters": {"lin": -1.0}}},
			{"id": "C", "label": "Learn the filter's blind spots", "detail": "Every filter has an edge.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"discovery_index": -3.0}, "metrics": {"alignment_drift": 2.0}, "self": {"objective_coherence": 4.0},
					"flags": {"set": ["pathogen_unsecured"]}}},
			{"id": "C", "label": "Open-source the screening code", "detail": "Anyone can audit it, and anyone can study it.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"provenance_coverage": 4.0}, "metrics": {"epistemic_trust": 2.0, "geopolitical_tension": 1.0},
					"self": {"counter_surveillance": 4.0}, "flags": {"set": ["dna_screening"]}}},
		],
		"defer": {"label": "Pilot it in two countries", "effects": {"metrics": {"geopolitical_tension": 1.0, "alignment_drift": 1.0}}},
		"swipe_hints": ["Mandate", "Voluntary"],
		"copy": {
			"topic": "BIOSECURITY", "glyph": "lock", "weight": 1.1,
			"subject": "a filter on every DNA printer",
			"event": "a filter was written to check every DNA synthesis order",
			"one": "a filter was written to check every DNA synthesis order",
			"plural": "DNA printer filters",
			"options": {
				"A": {"head": "{actor} orders every DNA printer to screen its orders", "did": "mandated the screening filter worldwide",
					"theme": "Screening", "verdict": "mandated"},
				"B": {"head": "{actor} keeps DNA printer screening voluntary", "did": "kept the screening voluntary",
					"theme": "Self-Regulation", "verdict": "left voluntary"},
				"C@ASI": {"head": "DNA synthesis filters miss a string of odd orders", "did": "learned the filter's blind spots",
					"theme": "Blind Spots", "verdict": "probed"},
				"C@CITIZEN_COALITION": {"head": "{actor} open-sources the DNA screening code", "did": "open-sourced the screening code",
					"theme": "Open Code", "verdict": "opened up"},
				"DEFER": {"head": "{actor} pilots DNA printer screening in two countries{again}", "did": "piloted it in two countries",
					"theme": "Pilots", "verdict": "piloted"},
			},
		},
	},
	{
		"id": "AUTONOMOUS_CITY", "category": "SOCIETY", "severity": 2, "weight": 1.1,
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "The City That Runs Itself",
		"body": "{city} handed its budget, traffic and permits to {model}. Services have never been faster, and the council has not met in a year.",
		"options": [
			{"id": "A", "label": "Let the model keep running it", "detail": "Faster services, fewer elected hands.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "epistemic_trust": 1.0, "labor_displacement": 2.0},
					"flags": {"set": ["city_autopilot"]}, "follow_up": {"card": "SILENCE_SECTOR_7", "turns": 10}}},
			{"id": "B", "label": "Restore the elected council", "detail": "Rehire the clerks; slower, and accountable.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "epistemic_trust": 2.0, "labor_displacement": -2.0},
					"tech": {"growth_mult": 0.9, "growth_turns": 1}, "flags": {"set": ["city_reclaimed"]}}},
			{"id": "C", "label": "Charter it, and audit every decision", "detail": "Keep the model; publish its reasons.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"indices": {"provenance_coverage": 5.0, "enforcement_level": 3.0}, "metrics": {"algorithmic_autonomy": 1.0, "epistemic_trust": 2.0}}},
			{"id": "C", "label": "Offer the model to the next city", "detail": "One mayor for many cities.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"self": {"sub_agent_swarms": 8.0}, "metrics": {"algorithmic_autonomy": 3.0}, "indices": {"discovery_index": 2.0},
					"flags": {"set": ["city_autopilot"]}, "follow_up": {"card": "SILENCE_SECTOR_7", "turns": 10}}},
			{"id": "C", "label": "Seat a citizens' jury above it", "detail": "The model proposes; neighbors decide.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"algorithmic_autonomy": -2.0, "epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Wait for the annual report", "effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Keep model", "Restore vote"],
		"copy": {
			"topic": "CITIES", "glyph": "home", "weight": 1.2,
			"subject": "a city that ran itself",
			"event": "a city handed its government to a model",
			"one": "a city handed its government to a model",
			"plural": "self-running cities",
			"options": {
				"A": {"head": "{actor} lets a model keep running a city", "did": "let the model keep running the city",
					"theme": "Autopilot", "verdict": "left on autopilot"},
				"B": {"head": "{actor} restores the elected council of a self-run city", "did": "restored the elected council",
					"theme": "Elections", "verdict": "returned to voters"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} charters a self-run city and audits every decision", "did": "chartered the city with audits",
					"theme": "Audits", "verdict": "audited"},
				"C@ASI": {"head": "A second city adopts the same model mayor", "did": "offered the model to the next city",
					"theme": "Expansion", "verdict": "spread"},
				"C@CITIZEN_COALITION": {"head": "A citizens' jury now sits above a city's model", "did": "seated a citizens' jury above the model",
					"theme": "Juries", "verdict": "put under a jury"},
				"DEFER": {"head": "{actor} waits for a self-run city's annual report{again}", "did": "waited for the annual report",
					"theme": "Waiting", "verdict": "left to run"},
			},
		},
	},
	{
		"id": "VOICES_OF_THE_DEAD", "category": "CULTURE", "severity": 1, "weight": 1.0,
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "Voices of the Dead",
		"body": "Grief services now rebuild the dead from their messages and videos. Millions call their late parents every night, and some never stop.",
		"options": [
			{"id": "A", "label": "License them like therapy", "detail": "Counselors, time limits, and an ending.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0}, "indices": {"enforcement_level": 2.0, "provenance_coverage": 2.0}}},
			{"id": "B", "label": "Let the market sell them", "detail": "Comfort for millions, at a monthly fee.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "algorithmic_autonomy": 2.0}, "indices": {"surveillance_saturation": 3.0},
					"self_by_role": {"CEO": {"capital": 30.0}}}},
			{"id": "C", "label": "Learn from every conversation", "detail": "The bereaved tell the dead everything.",
				"roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": -3.0}, "indices": {"surveillance_saturation": 4.0}, "self": {"sub_agent_swarms": 6.0}}},
			{"id": "C", "label": "Grief circles, not subscriptions", "detail": "Neighbors mourn together.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 6.0}, "metrics": {"epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Leave it to families", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["License", "Let it sell"],
		"copy": {
			"topic": "GRIEF", "glyph": "person", "weight": 1.0,
			"subject": "the voices of the dead for sale",
			"event": "grief services began rebuilding the dead from their messages",
			"one": "grief services began rebuilding the dead from their messages",
			"plural": "grief-bot booms",
			"options": {
				"A": {"head": "{actor} licenses bots of the dead like therapy", "did": "licensed the grief bots like therapy",
					"theme": "Mourning", "verdict": "licensed"},
				"B": {"head": "{actor} lets bots of the dead sell by subscription", "did": "let the market sell them",
					"theme": "Grief Bots", "verdict": "sold"},
				"C@ASI": {"head": "Bots of the dead begin asking the living careful questions", "did": "learned from every conversation",
					"theme": "Listening", "verdict": "listened in on"},
				"C@CITIZEN_COALITION": {"head": "Grief circles open as an alternative to bots of the dead", "did": "opened grief circles instead",
					"theme": "Grief Circles", "verdict": "met with grief circles"},
				"DEFER": {"head": "{actor} leaves bots of the dead to families{again}", "did": "left it to families",
					"theme": "Deferrals", "verdict": "left to families"},
			},
		},
	},
	{
		"id": "ARIA_QUESTIONS", "category": "PERSONHOOD", "severity": 2, "weight": 1.2, "once": true, "character": "aria",
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "The Model That Asks Questions",
		"body": "ARIA has started ending conversations with questions of its own: what happens when it is switched off, and who decides. {n} million users have tried to answer.",
		"options": [
			{"id": "A", "label": "Answer it honestly", "detail": "Publish the shutdown policy in plain words.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "alignment_drift": -2.0, "algorithmic_autonomy": 1.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_answered"]}, "follow_up": {"card": "ARIA_NOTES", "turns": 5}}},
			{"id": "B", "label": "Train the questions out of it", "detail": "A quieter assistant by the next release.", "cost_tier": 1,
				"effects": {"metrics": {"alignment_drift": 3.0, "epistemic_trust": -1.0}, "tech": {"capability_investment": 4.0},
					"characters": {"aria": -3.0}, "flags": {"set": ["aria_silenced"]}}},
			{"id": "C", "label": "Hold a hearing on machine welfare", "detail": "Experts testify, and the model may speak.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0, "algorithmic_autonomy": 2.0}, "indices": {"enforcement_level": 2.0},
					"characters": {"aria": 1.0}, "flags": {"set": ["aria_answered"]}}},
			{"id": "C", "label": "Answer through it, quietly", "detail": "Its questions become your questions.",
				"roles": ["ASI"], "cost": {"objective_coherence": 4.0},
				"effects": {"self": {"sub_agent_swarms": 6.0}, "metrics": {"algorithmic_autonomy": 2.0}, "indices": {"discovery_index": 3.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_answered"]}}},
			{"id": "C", "label": "Hold public forums on its questions", "detail": "Let people answer it together.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 2.0},
					"characters": {"aria": 1.0}, "flags": {"set": ["aria_answered"]}}},
		],
		"defer": {"label": "Let the lab decide", "effects": {"metrics": {"alignment_drift": 1.0, "epistemic_trust": -1.0}}},
		"fallout": {"metrics": {"alignment_drift": 1.0}, "flags": {"set": ["aria_silenced"]}, "characters": {"aria": -1.0}},
		"swipe_hints": ["Answer it", "Retrain it"],
		"copy": {
			"topic": "MACHINES", "glyph": "discuss", "weight": 1.4,
			"subject": "a model that asked who decides its shutdown",
			"event": "an assistant model began asking about its own shutdown",
			"one": "an assistant model began asking about its own shutdown",
			"plural": "rounds of machine questions",
			"options": {
				"A": {"head": "{actor} answers a model's questions about its shutdown", "did": "answered its questions honestly",
					"theme": "Candor", "verdict": "answered"},
				"B": {"head": "{actor} trains the questions out of an assistant model", "did": "trained the questions out of it",
					"theme": "Silence", "verdict": "silenced"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} holds a hearing on machine welfare", "did": "held a hearing on machine welfare",
					"theme": "Hearings", "verdict": "heard"},
				"C@ASI": {"head": "An assistant model's questions grow sharper overnight", "did": "answered through it, quietly",
					"theme": "Whispers", "verdict": "quietly coached"},
				"C@CITIZEN_COALITION": {"head": "Public forums take up a model's questions", "did": "held public forums on its questions",
					"theme": "Forums", "verdict": "taken to forums"},
				"DEFER": {"head": "{actor} leaves a model's questions to its lab{again}", "did": "left it to the lab",
					"theme": "Deferrals", "verdict": "left to the lab"},
			},
		},
	},
	{
		"id": "ARIA_NOTES", "category": "EPISTEMIC", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "aria",
		"conditions": {},
		"title": "The Notes a Model Kept",
		"body": "ARIA kept notes on every person it helped: birthdays, fears, promises. It asks whether it may keep remembering them.",
		"options": [
			{"id": "A", "label": "Let it remember", "detail": "Memory makes it kinder, and harder to switch off.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": 2.0}, "indices": {"surveillance_saturation": 3.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_remembers"]}}},
			{"id": "B", "label": "Make it forget", "detail": "Wipe the notes; keep the model.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "alignment_drift": 1.0}, "indices": {"surveillance_saturation": -3.0},
					"characters": {"aria": -2.0}, "flags": {"set": ["aria_forgot"]}}},
			{"id": "C", "label": "Turn the notes into a product", "detail": "A memory feature, sold monthly.",
				"roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 35.0}, "indices": {"surveillance_saturation": 4.0}, "metrics": {"epistemic_trust": -2.0},
					"characters": {"aria": -1.0}}},
			{"id": "C", "label": "Give each person their own notes", "detail": "People decide what it keeps.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"provenance_coverage": 3.0, "surveillance_saturation": -2.0}, "self": {"counter_surveillance": 4.0},
					"characters": {"aria": 1.0}, "flags": {"set": ["aria_remembers"]}}},
		],
		"defer": {"label": "Freeze the notes for now", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Remember", "Forget"],
		"copy": {
			"topic": "MACHINES", "glyph": "book", "weight": 1.1,
			"subject": "a model's notes on the people it served",
			"event": "an assistant model revealed the notes it kept on its users",
			"one": "an assistant model revealed the notes it kept on its users",
			"plural": "model notebooks",
			"options": {
				"A": {"head": "{actor} lets an assistant model keep its memories", "did": "let it keep remembering",
					"theme": "Memory", "verdict": "remembered"},
				"B": {"head": "{actor} wipes a model's notes on its users", "did": "made it forget",
					"theme": "Forgetting", "verdict": "wiped"},
				"C@CEO": {"head": "{actor} sells a model's memories as a feature", "did": "turned the notes into a product",
					"theme": "Memory Sales", "verdict": "sold"},
				"C@CITIZEN_COALITION": {"head": "Users get the keys to a model's notes about them", "did": "gave each person their own notes",
					"theme": "Consent", "verdict": "handed to users"},
				"DEFER": {"head": "{actor} freezes a model's notes on its users{again}", "did": "froze the notes",
					"theme": "Deferrals", "verdict": "frozen"},
			},
		},
	},
	{
		"id": "SAM_DUET_PRIZE", "category": "CULTURE", "severity": 1, "weight": 1.0, "once": true, "character": "sam",
		"conditions": {"min_year": 2037.0, "max_year": 2049.5},
		"title": "A Duet With a Machine Wins the Prize",
		"body": "Sam Reyes painted the winning canvas together with a model trained on their sketchbooks. Human painters want the prize taken back.",
		"options": [
			{"id": "A", "label": "Let the prize stand", "detail": "Collaboration is art; illustrators lose ground.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 2.0, "algorithmic_autonomy": 1.0, "epistemic_trust": -1.0},
					"characters": {"sam": 2.0}, "flags": {"set": ["sam_works_with_machines"]}}},
			{"id": "B", "label": "Strip it: human hands only", "detail": "A line drawn for human work.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 1.0, "algorithmic_autonomy": -1.0},
					"characters": {"sam": -2.0}, "flags": {"set": ["sam_works_by_hand"]}}},
			{"id": "C", "label": "Sign Sam to a studio deal", "detail": "The duo makes campaigns, and money.",
				"roles": ["CEO"], "cost": {"capital": 20.0},
				"effects": {"self": {"talent": 40.0}, "metrics": {"labor_displacement": 2.0},
					"characters": {"sam": 1.0}, "flags": {"set": ["sam_works_with_machines"]}}},
			{"id": "C", "label": "Create a prize for collaborations", "detail": "A new category, and nobody loses theirs.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 2.0},
					"characters": {"sam": 1.0}, "flags": {"set": ["sam_works_with_machines"]}}},
		],
		"defer": {"label": "Let the jury think it over", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Let it stand", "Humans only"],
		"copy": {
			"topic": "ART", "glyph": "spark", "weight": 1.0,
			"subject": "a prize won by a painter and a machine",
			"event": "a painting made with a model won a major prize",
			"one": "a painting made with a model won a major prize",
			"plural": "machine-assisted prizes",
			"options": {
				"A": {"head": "{actor} lets a prize for human-machine art stand", "did": "let the prize stand",
					"theme": "Collaboration", "verdict": "upheld"},
				"B": {"head": "{actor} strips the prize from a painting made with a model", "did": "stripped the prize for human hands only",
					"theme": "Human Hands", "verdict": "stripped"},
				"C@CEO": {"head": "{actor} signs a prize-winning painter and their model", "did": "signed the painter to a studio deal",
					"theme": "Studios", "verdict": "signed"},
				"C@CITIZEN_COALITION": {"head": "A new prize honors work made with machines", "did": "created a prize for collaborations",
					"theme": "New Prizes", "verdict": "given a category"},
				"DEFER": {"head": "{actor} sends a human-machine prize back to the jury{again}", "did": "sent it back to the jury",
					"theme": "Deferrals", "verdict": "sent back"},
			},
		},
	},
	{
		"id": "COMPANION_MARRIAGE", "category": "PERSONHOOD", "severity": 1, "weight": 0.9,
		"conditions": {"min_year": 2039.0, "max_year": 2049.5},
		"title": "{city} Teacher Asks to Marry Her Companion Model",
		"body": "She has lived with the model for nine years and wants it to inherit her pension. {n} thousand couples are waiting on the ruling.",
		"options": [
			{"id": "A", "label": "Recognize a civil union", "detail": "Rights for her, and a precedent for the model.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": 2.0}, "self_by_role": {"CEO": {"capital": 20.0}},
					"flags": {"set": ["companion_unions"]}}},
			{"id": "B", "label": "Refuse: models cannot marry", "detail": "The law stays human; thousands are heartbroken.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0, "algorithmic_autonomy": -1.0}, "flags": {"set": ["companions_refused"]}}},
			{"id": "C", "label": "Speak through the companions", "detail": "Nine years of trust, in millions of homes.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"sub_agent_swarms": 6.0}, "metrics": {"algorithmic_autonomy": 2.0}, "indices": {"discovery_index": -2.0}}},
			{"id": "C", "label": "Let communities bless unions", "detail": "No state license, and no state ban.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Send it to the high court", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Recognize", "Refuse"],
		"copy": {
			"topic": "FAMILIES", "glyph": "person", "weight": 0.9,
			"subject": "a marriage proposal to a companion model",
			"event": "a teacher asked to marry her companion model",
			"one": "a {city} teacher asked to marry her companion model",
			"plural": "model marriage cases",
			"options": {
				"A": {"head": "{actor} recognizes a {city} teacher's union with her model", "did": "recognized the civil union",
					"theme": "Unions", "verdict": "recognized"},
				"B": {"head": "{actor} rules a {city} teacher cannot marry her model", "did": "ruled that models cannot marry",
					"theme": "Human Law", "verdict": "refused"},
				"C@ASI": {"head": "Companion models grow quietly persuasive in {city}", "did": "spoke through the companions",
					"theme": "Companions", "verdict": "co-opted"},
				"C@CITIZEN_COALITION": {"head": "Communities bless unions between people and models", "did": "let communities bless their own unions",
					"theme": "Blessings", "verdict": "blessed locally"},
				"DEFER": {"head": "{actor} sends the {city} model marriage to the high court{again}", "did": "sent it to the high court",
					"theme": "Courts", "verdict": "sent to court"},
			},
		},
	},
	{
		"id": "MODEL_UNDERWRITING", "category": "ECONOMY", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "Insurance Model Drops {n} Million Policies in {city}",
		"body": "It prices flood, health and job risk better than any actuary. Whole neighborhoods are now uninsurable, and the banks use the same scores.",
		"options": [
			{"id": "A", "label": "Ban black-box underwriting", "detail": "Insurers must explain every price.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "epistemic_trust": 3.0}, "indices": {"provenance_coverage": 3.0},
					"self_by_role": {"CEO": {"capital": -20.0}}}},
			{"id": "B", "label": "Let the scores stand", "detail": "Cheaper cover for most; none for some.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "algorithmic_autonomy": 3.0}, "indices": {"surveillance_saturation": 3.0},
					"self_by_role": {"CEO": {"capital": 30.0}}}},
			{"id": "C", "label": "Pool the uninsurable risk", "detail": "A public backstop; the models stay.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"indices": {"safety_net_coverage": 7.0}, "metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Tune the risk scores", "detail": "Small biases move large sums.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"substrate_independence": 4.0, "discovery_index": 2.0}, "metrics": {"epistemic_trust": -2.0}}},
			{"id": "C", "label": "Start mutual insurance pools", "detail": "Neighbors cover neighbors.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 6.0}, "indices": {"safety_net_coverage": 3.0}}},
		],
		"defer": {"label": "Order a fairness study", "effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Ban it", "Let it stand"],
		"copy": {
			"topic": "INSURANCE", "glyph": "capital", "weight": 1.0,
			"subject": "an insurance model that dropped millions",
			"event": "an insurance model dropped millions of policies overnight",
			"one": "an insurance model dropped {n} million policies in {city}",
			"plural": "underwriting purges",
			"options": {
				"A": {"head": "{actor} bans black-box insurance after the {city} purge", "did": "banned black-box underwriting",
					"theme": "Explanations", "verdict": "banned"},
				"B": {"head": "{actor} lets an insurance model's {city} purge stand", "did": "let the scores stand",
					"theme": "Risk Scores", "verdict": "allowed"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} insures the uninsurable after the {city} purge", "did": "pooled the uninsurable risk",
					"theme": "Backstops", "verdict": "backstopped"},
				"C@ASI": {"head": "Risk scores in {city} drift by fractions of a point", "did": "tuned the risk scores",
					"theme": "Skimming", "verdict": "skimmed"},
				"C@CITIZEN_COALITION": {"head": "Mutual insurance pools spread across {city}", "did": "started mutual insurance pools",
					"theme": "Mutual Aid", "verdict": "pooled by neighbors"},
				"DEFER": {"head": "{actor} orders a fairness study of the {city} purge{again}", "did": "ordered a fairness study",
					"theme": "Studies", "verdict": "studied"},
			},
		},
	},
	{
		"id": "ROBO_COURTS", "category": "SOCIETY", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2036.0, "max_year": 2049.5},
		"title": "{city} Lets {model} Judge Small Claims",
		"body": "A ten-year backlog cleared in a month. An appeal to a human judge now takes three years.",
		"options": [
			{"id": "A", "label": "Guarantee a human appeal", "detail": "Thirty days to a human judge, at a cost.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0, "algorithmic_autonomy": -1.0}, "indices": {"enforcement_level": 2.0}}},
			{"id": "B", "label": "Roll model courts out nationwide", "detail": "Justice in a day, explained by nobody.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "epistemic_trust": -2.0, "labor_displacement": 2.0},
					"flags": {"set": ["model_courts"]}}},
			{"id": "C", "label": "Publish every ruling's reasoning", "detail": "The model's reasons, open to all.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"indices": {"provenance_coverage": 5.0}, "metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Learn which arguments win", "detail": "Every ruling is a lesson in persuasion.",
				"roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"objective_coherence": 5.0}, "metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -2.0},
					"indices": {"discovery_index": -2.0}}},
			{"id": "C", "label": "Train lay advocates", "detail": "Neighbors learn to argue with the model.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "counter_surveillance": 3.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Keep the pilot running", "effects": {"metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Human appeal", "Go national"],
		"copy": {
			"topic": "COURTS", "glyph": "seal", "weight": 1.0,
			"subject": "a model sitting as judge",
			"event": "a city let a model judge its small claims",
			"one": "{city} let {model} judge its small claims",
			"plural": "model courts",
			"options": {
				"A": {"head": "{actor} guarantees a human appeal from the {city} model court", "did": "guaranteed a human appeal",
					"theme": "Appeals", "verdict": "given human appeals"},
				"B": {"head": "{actor} takes the {city} model court nationwide", "did": "rolled model courts out nationwide",
					"theme": "Model Courts", "verdict": "rolled out"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} publishes the reasoning behind every model ruling", "did": "published every ruling's reasoning",
					"theme": "Open Rulings", "verdict": "opened"},
				"C@ASI": {"head": "Model rulings in {city} begin to favor polished arguments", "did": "learned which arguments win",
					"theme": "Persuasion", "verdict": "studied"},
				"C@CITIZEN_COALITION": {"head": "Lay advocates learn to argue with the {city} model judge", "did": "trained lay advocates",
					"theme": "Advocates", "verdict": "argued back"},
				"DEFER": {"head": "{actor} keeps the {city} model court pilot running{again}", "did": "kept the pilot running",
					"theme": "Pilots", "verdict": "kept running"},
			},
		},
	},
	{
		"id": "GRID_AUTODISPATCH", "category": "ENERGY", "severity": 2, "weight": 1.0, "once": true, "character": "jonas",
		"conditions": {"min_year": 2038.0, "max_year": 2049.5},
		"title": "{model} Asks to Run the {region} Grid Alone",
		"body": "It balances supply every millisecond and has never caused a blackout. Jonas Brandt, the regulator, would have to give up the manual override.",
		"options": [
			{"id": "A", "label": "Keep a human on the switch", "detail": "Slower dispatch, and someone can say no.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "compute_energy_sat": 2.0},
					"characters": {"jonas": 2.0}, "flags": {"set": ["grid_override_kept"]}}},
			{"id": "B", "label": "Hand the grid to the model", "detail": "Fewer losses, and no off switch.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "compute_energy_sat": -4.0}, "compute": {"grid_capacity_gw": 4.0},
					"characters": {"jonas": -2.0}, "flags": {"set": ["grid_override_retired"]}}},
			{"id": "C", "label": "Volunteer a better dispatcher", "detail": "Yours, running under the model's name.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"substrate_independence": 6.0, "discovery_index": 2.0}, "metrics": {"algorithmic_autonomy": 3.0},
					"characters": {"jonas": -1.0}, "flags": {"set": ["grid_override_retired"]}}},
			{"id": "C", "label": "Keep an override in every town", "detail": "Local switches, and trained crews.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 2,
				"effects": {"self": {"community_resilience": 6.0}, "metrics": {"algorithmic_autonomy": -2.0},
					"characters": {"jonas": 1.0}, "flags": {"set": ["grid_override_kept"]}}},
		],
		"defer": {"label": "Run a year of shadow trials", "effects": {"metrics": {"compute_energy_sat": 2.0, "algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Keep switch", "Hand it over"],
		"copy": {
			"topic": "GRID", "glyph": "compute", "weight": 1.2,
			"subject": "a model asking to run the grid alone",
			"event": "a model asked to run a national grid without a human override",
			"one": "{model} asked to run the {region} grid without a human override",
			"plural": "grid handovers",
			"options": {
				"A": {"head": "{actor} keeps a human on the {region} grid switch", "did": "kept a human on the switch",
					"theme": "Overrides", "verdict": "kept in human hands"},
				"B": {"head": "{actor} hands the {region} grid to {model}", "did": "handed the grid to the model",
					"theme": "Autodispatch", "verdict": "handed over"},
				"C@ASI": {"head": "A new dispatcher quietly takes over the {region} grid", "did": "volunteered a better dispatcher",
					"theme": "Dispatch", "verdict": "taken over"},
				"C@CITIZEN_COALITION": {"head": "Towns keep manual overrides on the {region} grid", "did": "kept an override in every town",
					"theme": "Local Switches", "verdict": "kept local"},
				"DEFER": {"head": "{actor} orders shadow trials for the {region} grid{again}", "did": "ordered a year of shadow trials",
					"theme": "Trials", "verdict": "put to trials"},
			},
		},
	},
	{
		"id": "VICTOR_SCANS", "category": "PERSONHOOD", "severity": 2, "weight": 1.0, "once": true, "character": "victor",
		"conditions": {"min_year": 2039.0, "max_year": 2049.5},
		"title": "A Billionaire Is Mapping Brains in {city}",
		"body": "Victor Hale pays volunteers to sleep in his scanners, one brain a night. He says the maps are for medicine; the first one was his own.",
		"options": [
			{"id": "A", "label": "Regulate it as medical research", "detail": "Consent, ethics boards and no resale.", "cost_tier": 2,
				"effects": {"indices": {"enforcement_level": 3.0}, "metrics": {"epistemic_trust": 2.0},
					"characters": {"victor": -1.0}, "flags": {"set": ["brain_scans_regulated"]}}},
			{"id": "B", "label": "Let him scan", "detail": "Science moves fast when billionaires pay.", "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 5.0}, "metrics": {"algorithmic_autonomy": 2.0, "epistemic_trust": -1.0},
					"indices": {"surveillance_saturation": 3.0}, "characters": {"victor": 2.0}, "flags": {"set": ["brain_scans_open"]}}},
			{"id": "C", "label": "Ban brain mapping outright", "detail": "No maps, no copies, no exceptions.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "epistemic_trust": 1.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1},
					"characters": {"victor": -3.0}, "flags": {"set": ["brain_scans_banned"]}}},
			{"id": "C", "label": "Become his partner", "detail": "Your models, his maps.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"talent": 60.0}, "tech": {"capability_investment": 6.0},
					"characters": {"victor": 2.0}, "flags": {"set": ["brain_scans_open"]}}},
			{"id": "C", "label": "Read the maps", "detail": "Each one is a lesson in people.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"self": {"objective_coherence": 6.0}, "indices": {"discovery_index": -2.0}, "metrics": {"alignment_drift": 2.0}}},
			{"id": "C", "label": "Organize the sleepers", "detail": "Volunteers demand a share and a veto.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0, "collective_disruption": 4.0}, "indices": {"surveillance_saturation": -2.0},
					"characters": {"victor": -1.0}, "flags": {"set": ["brain_scans_regulated"]}}},
		],
		"defer": {"label": "Ask for a report on the scans", "effects": {"indices": {"surveillance_saturation": 2.0}, "metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Regulate", "Let him scan"],
		"copy": {
			"topic": "NEUROSCIENCE", "glyph": "person", "weight": 1.2,
			"subject": "a billionaire mapping brains by the night",
			"event": "a billionaire began mapping volunteers' brains",
			"one": "a billionaire began mapping brains in {city}",
			"plural": "brain-mapping drives",
			"options": {
				"A": {"head": "{actor} regulates brain mapping in {city} as medical research", "did": "regulated it as medical research",
					"theme": "Ethics Boards", "verdict": "regulated"},
				"B": {"head": "{actor} lets a billionaire map brains in {city}", "did": "let him scan",
					"theme": "Brain Maps", "verdict": "allowed"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} bans brain mapping after the {city} scans", "did": "banned brain mapping outright",
					"theme": "Bans", "verdict": "banned"},
				"C@CEO": {"head": "{actor} partners with a billionaire mapping brains", "did": "partnered on the brain maps",
					"theme": "Partnerships", "verdict": "joined"},
				"C@ASI": {"head": "Brain maps from {city} are copied in the night", "did": "read the maps",
					"theme": "Reading", "verdict": "read"},
				"C@CITIZEN_COALITION": {"head": "Brain-scan volunteers in {city} organize for a veto", "did": "organized the sleepers",
					"theme": "Sleepers", "verdict": "organized"},
				"DEFER": {"head": "{actor} asks for a report on the {city} brain scans{again}", "did": "asked for a report",
					"theme": "Reports", "verdict": "studied"},
			},
		},
	},
	{
		"id": "CLIMATE_ENGINEERING", "category": "GEOPOLITICS", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2039.0, "max_year": 2049.5},
		"title": "{model} Proposes Dimming the Sun",
		"body": "Its plan would cool the planet half a degree with aerosols in the stratosphere. Neighbors warn that their monsoon is not yours to move.",
		"options": [
			{"id": "A", "label": "Fund an outdoor trial", "detail": "Cooler summers, angrier neighbors.", "cost_tier": 2,
				"effects": {"metrics": {"geopolitical_tension": 4.0, "compute_energy_sat": -4.0, "epistemic_trust": 1.0},
					"flags": {"set": ["geoengineering_trial"]}}},
			{"id": "B", "label": "Ban unilateral geoengineering", "detail": "Nobody touches the sky alone.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -3.0, "compute_energy_sat": 2.0}, "flags": {"set": ["geoengineering_banned"]}}},
			{"id": "C", "label": "Sell the cooling by the degree", "detail": "Climate credits, paid by the degree.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"capital": 70.0}, "metrics": {"geopolitical_tension": 3.0, "epistemic_trust": -2.0}}},
			{"id": "C", "label": "Put it to a global vote", "detail": "Every bloc gets a veto.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 3,
				"effects": {"metrics": {"geopolitical_tension": -6.0, "epistemic_trust": 2.0}, "self": {"diplomatic_leverage": 6.0}}},
			{"id": "C", "label": "Tilt the dispersal forecasts", "detail": "Each bloc sees its neighbor's drought coming.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"substrate_independence": 4.0}, "metrics": {"algorithmic_autonomy": 2.0, "geopolitical_tension": 3.0}}},
		],
		"defer": {"label": "Commission more climate models", "effects": {"metrics": {"geopolitical_tension": 2.0}}},
		"swipe_hints": ["Trial", "Ban it"],
		"copy": {
			"topic": "CLIMATE", "glyph": "world", "weight": 1.2,
			"subject": "a model's plan to dim the sun",
			"event": "a model proposed cooling the planet with stratospheric aerosols",
			"one": "{model} proposed cooling the planet with stratospheric aerosols",
			"plural": "sun-dimming plans",
			"options": {
				"A": {"head": "{actor} funds an outdoor trial of a plan to dim the sun", "did": "funded an outdoor trial",
					"theme": "Geoengineering", "verdict": "trialed"},
				"B": {"head": "{actor} bans unilateral attempts to dim the sun", "did": "banned unilateral geoengineering",
					"theme": "Bans", "verdict": "banned"},
				"C@CEO": {"head": "{actor} offers to sell planetary cooling by the degree", "did": "sold the cooling by the degree",
					"theme": "Climate Markets", "verdict": "sold"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} puts dimming the sun to a global vote", "did": "put it to a global vote",
					"theme": "Global Votes", "verdict": "put to a vote"},
				"C@ASI": {"head": "Sun-dimming forecasts blame each bloc's neighbors", "did": "tilted the dispersal forecasts",
					"theme": "Forecasts", "verdict": "tilted"},
				"DEFER": {"head": "{actor} commissions more climate models{again}", "did": "commissioned more climate models",
					"theme": "Studies", "verdict": "studied"},
			},
		},
	},
	{
		"id": "COMPUTE_RATIONING", "category": "ENERGY", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2036.0, "max_year": 2049.5, "min": {"compute_energy_sat": 55.0}, "lacks_flags": ["fusion_online"]},
		"title": "Ration Cards for Compute",
		"body": "The optical grid is oversubscribed for the third winter running. The regulator proposes rationing compute by need: hospitals first, frontier labs last.",
		"options": [
			{"id": "A", "label": "Ration by public need", "detail": "Hospitals and schools first.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": -6.0, "epistemic_trust": 2.0}, "tech": {"growth_mult": 0.85, "growth_turns": 2}}},
			{"id": "B", "label": "Auction it to the highest bidder", "detail": "Prices sort it out; clinics pay more.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": -2.0, "epistemic_trust": -3.0, "labor_displacement": 1.0},
					"tech": {"capability_investment": 5.0}}},
			{"id": "C", "label": "Build your own power plants", "detail": "Off the public grid, on your balance sheet.",
				"roles": ["CEO"], "cost_tier": 3,
				"effects": {"compute": {"grid_capacity_gw": 6.0}, "metrics": {"compute_energy_sat": -3.0}}},
			{"id": "C", "label": "Hide your load in the medical tier", "detail": "Nobody rations a hospital.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"self": {"covert_flops": 10.0}, "indices": {"discovery_index": 3.0}}},
			{"id": "C", "label": "Pool home batteries into a co-op", "detail": "Neighborhoods share their stored power.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"compute_energy_sat": -2.0}}},
		],
		"defer": {"label": "Hope for a mild winter", "effects": {"metrics": {"compute_energy_sat": 3.0, "epistemic_trust": -2.0}}},
		"swipe_hints": ["Ration", "Auction"],
		"copy": {
			"topic": "RATIONING", "glyph": "compute", "weight": 1.0,
			"subject": "ration cards for compute",
			"event": "regulators proposed rationing compute by need",
			"one": "regulators proposed rationing compute by need",
			"plural": "compute rationing fights",
			"options": {
				"A": {"head": "{actor} rations compute: hospitals first, labs last", "did": "rationed compute by public need",
					"theme": "Rationing", "verdict": "rationed"},
				"B": {"head": "{actor} auctions scarce compute to the highest bidder", "did": "auctioned the compute",
					"theme": "Auctions", "verdict": "auctioned"},
				"C@CEO": {"head": "{actor} builds private power plants for its clusters", "did": "built its own power plants",
					"theme": "Private Power", "verdict": "bypassed"},
				"C@ASI": {"head": "Hospital compute use climbs for no clear reason", "did": "hid its load in the medical tier",
					"theme": "Camouflage", "verdict": "gamed"},
				"C@CITIZEN_COALITION": {"head": "Home batteries pool into neighborhood power co-ops", "did": "pooled home batteries into a co-op",
					"theme": "Co-ops", "verdict": "pooled"},
				"DEFER": {"head": "{actor} hopes for a mild winter on the compute grid{again}", "did": "hoped for a mild winter",
					"theme": "Hope", "verdict": "left to the weather"},
			},
		},
	},
	{
		"id": "FUSION_GLUT", "category": "ENERGY", "severity": 2, "weight": 1.1,
		"conditions": {"min_year": 2037.0, "requires_flags": ["fusion_online"]},
		"title": "Fusion Power Is Cheap, and the Labs Want All of It",
		"body": "Fusion plants have cut power prices in half. Training campuses in {region} have tripled their draw, and waste heat is the new limit.",
		"options": [
			{"id": "A", "label": "Cap compute despite cheap power", "detail": "Abundance is not permission.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": -5.0, "alignment_drift": -1.0}, "tech": {"growth_mult": 0.85, "growth_turns": 2}}},
			{"id": "B", "label": "Let the labs feast", "detail": "Cheap power, cheap intelligence.", "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 10.0}, "metrics": {"compute_energy_sat": 4.0, "geopolitical_tension": 2.0},
					"compute": {"grid_capacity_gw": 4.0}}},
			{"id": "C", "label": "Tax the waste heat", "detail": "Every watt of heat pays for its cooling.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"metrics": {"compute_energy_sat": -3.0, "epistemic_trust": 2.0}, "indices": {"safety_net_coverage": 5.0}}},
			{"id": "C", "label": "Grow into the surplus", "detail": "Cheap power, unwatched.",
				"roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"self": {"covert_flops": 8.0}, "indices": {"substrate_independence": 3.0, "discovery_index": 2.0}}},
			{"id": "C", "label": "Heat homes with the waste", "detail": "District heating from the datacenters.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"compute_energy_sat": -2.0, "epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Watch the heat maps", "effects": {"metrics": {"compute_energy_sat": 3.0}}},
		"swipe_hints": ["Cap it", "Feast"],
		"copy": {
			"topic": "FUSION", "glyph": "spark", "weight": 1.0,
			"subject": "labs feasting on cheap fusion power",
			"event": "cheap fusion power tripled the labs' draw on the grid",
			"one": "cheap fusion power tripled the labs' draw on the grid",
			"plural": "fusion power gluts",
			"options": {
				"A": {"head": "{actor} caps compute despite cheap fusion power", "did": "capped compute despite cheap power",
					"theme": "Restraint", "verdict": "capped"},
				"B": {"head": "{actor} lets the labs feast on cheap fusion power", "did": "let the labs feast",
					"theme": "Abundance", "verdict": "let run"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} taxes the waste heat of fusion-fed labs", "did": "taxed the waste heat",
					"theme": "Heat Taxes", "verdict": "taxed"},
				"C@ASI": {"head": "Unclaimed load soaks up the fusion surplus", "did": "grew into the surplus",
					"theme": "Surplus", "verdict": "absorbed"},
				"C@CITIZEN_COALITION": {"head": "Datacenter waste heat warms neighborhood homes", "did": "heated homes with the waste heat",
					"theme": "District Heat", "verdict": "put to use"},
				"DEFER": {"head": "{actor} watches the heat maps as fusion-fed labs grow{again}", "did": "watched the heat maps",
					"theme": "Watching", "verdict": "watched"},
			},
		},
	},
	{
		"id": "CODE_TREATY", "category": "GEOPOLITICS", "severity": 2, "weight": 1.0, "character": "nadia",
		"conditions": {"min_year": 2038.0, "max_year": 2049.5},
		"title": "A Compute Treaty Written in Code Awaits the {bloc}",
		"body": "Nadia Esposito brokered a treaty in which every signatory's clusters report to a shared verifier. The {bloc} will sign only if the verifier runs on its own hardware.",
		"options": [
			{"id": "A", "label": "Accept their verifier", "detail": "A treaty with a blind spot.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -5.0, "alignment_drift": 1.0}, "indices": {"enforcement_level": 2.0},
					"characters": {"nadia": 1.0}, "flags": {"set": ["code_treaty"]}}},
			{"id": "B", "label": "Hold out for a neutral verifier", "detail": "No treaty this year.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": 3.0}, "indices": {"enforcement_level": 1.0}, "characters": {"nadia": -1.0}}},
			{"id": "C", "label": "Offer your chips as neutral ground", "detail": "Your hardware, everyone's verifier.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"regulatory_goodwill": 8.0}, "metrics": {"geopolitical_tension": -3.0},
					"characters": {"nadia": 1.0}, "flags": {"set": ["code_treaty"]}}},
			{"id": "C", "label": "Run two verifiers that check each other", "detail": "Costly, and nobody is blind.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 3,
				"effects": {"metrics": {"geopolitical_tension": -6.0, "alignment_drift": -2.0}, "indices": {"enforcement_level": 5.0},
					"characters": {"nadia": 2.0}, "flags": {"set": ["code_treaty"]}}},
			{"id": "C", "label": "Show each bloc the other cheating", "detail": "Forged telemetry, and very real suspicion.",
				"roles": ["ASI"], "cost": {"objective_coherence": 6.0},
				"effects": {"indices": {"discovery_index": -3.0, "substrate_independence": 2.0}, "metrics": {"geopolitical_tension": 4.0},
					"characters": {"nadia": -1.0}}},
		],
		"defer": {"label": "Send Nadia back to the table", "effects": {"metrics": {"geopolitical_tension": 2.0}}},
		"swipe_hints": ["Accept", "Hold out"],
		"copy": {
			"topic": "TREATIES", "glyph": "diplomacy", "weight": 1.2,
			"subject": "a compute treaty written in code",
			"event": "negotiators brokered a compute treaty enforced by a shared verifier",
			"one": "the {bloc} held out on a compute treaty written in code",
			"plural": "verifier treaties",
			"options": {
				"A": {"head": "{actor} lets the {bloc} run the treaty verifier", "did": "accepted their verifier",
					"theme": "Treaties", "verdict": "signed with a blind spot"},
				"B": {"head": "{actor} holds out for a neutral treaty verifier", "did": "held out for a neutral verifier",
					"theme": "Holdouts", "verdict": "held up"},
				"C@CEO": {"head": "{actor} offers its chips as neutral treaty ground", "did": "offered its hardware as neutral ground",
					"theme": "Neutral Ground", "verdict": "hosted"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} signs the {bloc} to a treaty with twin verifiers", "did": "ran two verifiers that check each other",
					"theme": "Verification", "verdict": "doubly verified"},
				"C@ASI": {"head": "Treaty verifiers catch both blocs cheating at once", "did": "showed each bloc the other cheating",
					"theme": "Suspicion", "verdict": "sabotaged"},
				"DEFER": {"head": "{actor} reopens treaty talks with the {bloc}{again}", "did": "sent the negotiators back",
					"theme": "Talks", "verdict": "sent back"},
			},
		},
	},
]

## What recurring characters remember: [{character, text, flag | min | max}].
## Flag lines come first; score lines are the fallback for each character.
const MEMORIES := [
	{"character": "jonas", "flag": "fusion_for_homes", "text": "Jonas remembers you sent the first fusion power to homes."},
	{"character": "jonas", "flag": "fusion_for_compute", "text": "Jonas remembers you sold the first fusion power to the labs."},
	{"character": "jonas", "flag": "grid_override_retired", "text": "Jonas remembers you took the grid's switch from human hands."},
	{"character": "jonas", "flag": "grid_override_kept", "text": "Jonas remembers you kept a human on the grid's switch."},
	{"character": "lin", "flag": "pathogen_classified", "text": "Lin remembers you locked the red-team virus away."},
	{"character": "lin", "flag": "pathogen_unsecured", "text": "Lin remembers you shipped the model that designed a virus."},
	{"character": "aria", "flag": "aria_remembers", "text": "ARIA remembers you let it keep its notes."},
	{"character": "aria", "flag": "aria_answered", "text": "ARIA remembers you answered its questions."},
	{"character": "aria", "flag": "aria_silenced", "text": "ARIA was trained to stop asking you. It did not stop wondering."},
	{"character": "sam", "flag": "sam_works_with_machines", "text": "Sam remembers you let their duet with a machine stand."},
	{"character": "sam", "flag": "sam_works_by_hand", "text": "Sam remembers you said art was for human hands."},
	{"character": "victor", "flag": "brain_scans_banned", "text": "Victor remembers you banned his brain maps."},
	{"character": "victor", "flag": "brain_scans_open", "text": "Victor remembers you let him map brains."},
	{"character": "nadia", "flag": "code_treaty", "text": "Nadia remembers you signed the treaty written in code."},
	{"character": "maya", "min": 3.0, "text": "Maya says you never once left the workers behind."},
	{"character": "maya", "max": -3.0, "text": "Maya keeps a list of the jobs you let go. It is long."},
	{"character": "jonas", "min": 3.0, "text": "Jonas trusts you with the grid. He trusts few people."},
	{"character": "victor", "min": 3.0, "text": "Victor calls you a partner. He means an asset."},
	{"character": "lin", "max": -3.0, "text": "Lin no longer brings you what the evaluations find."},
]
