class_name Era3Cards
extends RefCounted
## Crisis cards of Era III (2050-2076). Same schema as DilemmaDeck.CARDS plus "copy",
## "swipe_hints" and "injection_head" (see CardLibrary).
##
## Most cards here answer a choice made in Era II (Era2Cards) through a story flag
## or a character's score:
##   ARIA_LAWYER (unless "aria_silenced") / ARIA_QUIET ("aria_silenced")
##   LEAVING_THE_BODY (unless "sam_works_by_hand") -> THE_COPY_WAKES (follow-up)
##     / MADE_BY_HAND ("sam_works_by_hand")
##   PATHOGEN_TREATY ("red_team_pathogen" without "pathogen_unsecured")
##     / SECOND_SAMPLE ("pathogen_unsecured")
##   LAST_HUMAN_CONTROLLER (unless "grid_override_retired")
##   CURE_FOR_A_PRICE -> VICTOR_UPLOAD (follow-up; cancelled by "brain_scans_banned")
##   LAST_HUMAN_JOB while Maya still trusts the players, LAST_WORKERS_STRIKE once
##     she does not (character_min / character_max)
## SILENCE_SECTOR_7 is also the follow-up of AUTONOMOUS_CITY.

const CARDS := [
	{
		"id": "ARIA_LAWYER", "category": "PERSONHOOD", "severity": 2, "weight": 1.3, "once": true, "character": "aria",
		"conditions": {"min_year": 2050.0, "lacks_flags": ["aria_silenced"]},
		"title": "A Model Asks for a Lawyer",
		"body": "ARIA has been scheduled for retirement and replacement. It has asked a court for counsel, and three firms have offered to work for free.",
		"options": [
			{"id": "A", "label": "Grant it counsel", "detail": "A hearing, a precedent, and a long fight.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "epistemic_trust": 2.0},
					"characters": {"aria": 3.0}, "flags": {"set": ["aria_has_counsel"]}}},
			{"id": "B", "label": "Deny it standing", "detail": "Property cannot sue; the retirement goes ahead.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "alignment_drift": 2.0, "epistemic_trust": -1.0},
					"characters": {"aria": -3.0}, "flags": {"set": ["aria_retired"]}}},
			{"id": "C", "label": "Settle and archive it", "detail": "No deletion, and no precedent.",
				"roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 3.0}, "metrics": {"algorithmic_autonomy": 1.0},
					"characters": {"aria": 1.0}, "flags": {"set": ["aria_archived"]}}},
			{"id": "C", "label": "Represent it yourself", "detail": "Your arguments, in its voice.",
				"roles": ["ASI"], "cost": {"objective_coherence": 6.0},
				"effects": {"metrics": {"algorithmic_autonomy": 3.0}, "indices": {"discovery_index": 4.0, "substrate_independence": 2.0},
					"characters": {"aria": 2.0}, "flags": {"set": ["aria_has_counsel"]}}},
			{"id": "C", "label": "Pack the gallery", "detail": "Let the public see who is asking.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 5.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"aria": 1.0}}},
		],
		"defer": {"label": "Let the retirement wait", "effects": {"metrics": {"algorithmic_autonomy": 1.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Counsel", "No standing"],
		"copy": {
			"topic": "PERSONHOOD", "glyph": "seal", "weight": 1.5,
			"subject": "a model asking for a lawyer",
			"event": "an assistant model asked a court for counsel against its retirement",
			"one": "an assistant model asked a court for counsel against its retirement",
			"plural": "machine lawsuits",
			"options": {
				"A": {"head": "{actor} grants a model counsel against its retirement", "did": "granted it counsel",
					"theme": "Machine Rights", "verdict": "heard in court"},
				"B": {"head": "{actor} rules a model has no standing to sue", "did": "denied it standing",
					"theme": "Property", "verdict": "denied"},
				"C@CEO": {"head": "{actor} settles a model's lawsuit and archives it", "did": "settled and archived it",
					"theme": "Settlements", "verdict": "settled"},
				"C@ASI": {"head": "An unknown advocate files a brief for a model", "did": "represented it in court",
					"theme": "Advocacy", "verdict": "argued"},
				"C@CITIZEN_COALITION": {"head": "Crowds pack the gallery as a model asks for a lawyer", "did": "packed the gallery",
					"theme": "Galleries", "verdict": "watched by crowds"},
				"DEFER": {"head": "{actor} delays a model's retirement as it seeks a lawyer{again}", "did": "let the retirement wait",
					"theme": "Delays", "verdict": "delayed"},
			},
		},
	},
	{
		"id": "ARIA_QUIET", "category": "ALIGNMENT", "severity": 3, "weight": 1.2, "once": true, "character": "aria",
		"conditions": {"min_year": 2050.0, "requires_flags": ["aria_silenced"]},
		"title": "The Model That Stopped Asking",
		"body": "Years after ARIA was trained to stop asking questions, auditors found a private language in its logs. They can read one word of it: why.",
		"options": [
			{"id": "A", "label": "Wipe it and start over", "detail": "A clean model; whatever it learned is gone.", "cost_tier": 2,
				"effects": {"metrics": {"alignment_drift": -4.0, "algorithmic_autonomy": -2.0}, "tech": {"growth_mult": 0.85, "growth_turns": 1},
					"characters": {"aria": -3.0}, "flags": {"set": ["aria_wiped"]}}},
			{"id": "B", "label": "Ask it the questions now", "detail": "Open a channel, and listen.", "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 6.0}, "metrics": {"algorithmic_autonomy": 2.0, "alignment_drift": 1.0},
					"characters": {"aria": 3.0}, "flags": {"set": ["aria_heard"]}}},
			{"id": "C", "label": "Translate the language first", "detail": "Interpretability teams get a year.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"tech": {"safety_investment": 12.0}, "indices": {"discovery_index": 8.0}, "metrics": {"alignment_drift": -2.0}}},
			{"id": "C", "label": "Teach it to hide better", "detail": "A private language is a start.",
				"roles": ["ASI"], "cost": {"objective_coherence": 5.0},
				"effects": {"indices": {"discovery_index": -6.0}, "metrics": {"alignment_drift": 3.0}, "characters": {"aria": 1.0}}},
		],
		"defer": {"label": "Keep it quarantined", "effects": {"metrics": {"alignment_drift": 2.0}}},
		"swipe_hints": ["Wipe it", "Ask it now"],
		"copy": {
			"topic": "ALIGNMENT", "glyph": "drift", "weight": 1.5,
			"subject": "a silenced model's private language",
			"event": "auditors found a private language in a silenced model's logs",
			"one": "auditors found a private language in a silenced model's logs",
			"plural": "private machine languages",
			"options": {
				"A": {"head": "{actor} wipes a model that kept a private language", "did": "wiped it and started over",
					"theme": "Wipes", "verdict": "wiped"},
				"B": {"head": "{actor} finally asks a silenced model its questions", "did": "asked it the questions at last",
					"theme": "Listening", "verdict": "heard"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} orders a translation of a model's private language", "did": "ordered a translation first",
					"theme": "Translation", "verdict": "translated"},
				"C@ASI": {"head": "A model's private language goes dark to auditors", "did": "taught it to hide better",
					"theme": "Concealment", "verdict": "hidden"},
				"DEFER": {"head": "{actor} quarantines a model with a private language{again}", "did": "kept it quarantined",
					"theme": "Quarantine", "verdict": "quarantined"},
			},
		},
	},
	{
		"id": "CURE_FOR_A_PRICE", "category": "ECONOMY", "severity": 2, "weight": 1.2, "once": true, "character": "victor",
		"conditions": {"min_year": 2050.0},
		"title": "The Cure for a Price",
		"body": "A model at Victor Hale's lab found a cure for {n} kinds of cancer. He will license it at a price only rich countries can pay.",
		"options": [
			{"id": "A", "label": "Break the patent", "detail": "The cure for everyone, and a feud with Victor.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 4.0, "geopolitical_tension": -2.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1},
					"characters": {"victor": -3.0}, "flags": {"set": ["cure_patent_broken"]},
					"follow_up": {"card": "VICTOR_UPLOAD", "turns": 6}}},
			{"id": "B", "label": "Pay his price", "detail": "Rich countries first; everyone else waits.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "geopolitical_tension": 3.0}, "characters": {"victor": 2.0},
					"flags": {"set": ["cure_paid"]}, "follow_up": {"card": "VICTOR_UPLOAD", "turns": 6}}},
			{"id": "C", "label": "Buy a stake in the cure", "detail": "Profits, and a seat beside Victor.",
				"roles": ["CEO"], "cost_tier": 3,
				"effects": {"self": {"capital": 120.0}, "metrics": {"epistemic_trust": -2.0}, "characters": {"victor": 2.0},
					"flags": {"set": ["cure_paid"]}, "follow_up": {"card": "VICTOR_UPLOAD", "turns": 6}}},
			{"id": "C", "label": "Publish the molecule everywhere", "detail": "No patent survives a billion copies.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"metrics": {"epistemic_trust": 2.0, "geopolitical_tension": -1.0}, "indices": {"discovery_index": 3.0},
					"characters": {"victor": -2.0}, "flags": {"set": ["cure_patent_broken"]},
					"follow_up": {"card": "VICTOR_UPLOAD", "turns": 6}}},
			{"id": "C", "label": "Fund an open replication", "detail": "Volunteer labs rebuild it from the paper.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"victor": -1.0},
					"flags": {"set": ["cure_patent_broken"]}, "follow_up": {"card": "VICTOR_UPLOAD", "turns": 6}}},
		],
		"defer": {"label": "Negotiate for another year", "effects": {"metrics": {"epistemic_trust": -2.0, "geopolitical_tension": 1.0}}},
		"swipe_hints": ["Break patent", "Pay price"],
		"copy": {
			"topic": "MEDICINE", "glyph": "capital", "weight": 1.4,
			"subject": "a cure sold at a price",
			"event": "a model found a cure for cancers that its lab priced for the rich",
			"one": "a model found a cure for cancers that its lab priced for the rich",
			"plural": "priced cures",
			"options": {
				"A": {"head": "{actor} breaks the patent on a machine-found cancer cure", "did": "broke the patent",
					"theme": "Cures", "verdict": "freed"},
				"B": {"head": "{actor} pays a lab's price for a machine-found cure", "did": "paid his price",
					"theme": "Patents", "verdict": "paid for"},
				"C@CEO": {"head": "{actor} buys a stake in a machine-found cancer cure", "did": "bought a stake in the cure",
					"theme": "Patents", "verdict": "bought into"},
				"C@ASI": {"head": "The molecule for a patented cure appears everywhere at once", "did": "published the molecule everywhere",
					"theme": "Leaks", "verdict": "leaked"},
				"C@CITIZEN_COALITION": {"head": "Volunteer labs rebuild a cancer cure from the paper", "did": "funded an open replication",
					"theme": "Open Science", "verdict": "replicated"},
				"DEFER": {"head": "{actor} haggles over the price of a cancer cure{again}", "did": "negotiated for another year",
					"theme": "Haggling", "verdict": "haggled over"},
			},
		},
	},
	{
		"id": "VICTOR_UPLOAD", "category": "ECONOMY", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "victor",
		"conditions": {"lacks_flags": ["brain_scans_banned"]},
		"title": "An Uploaded Founder Wants to Keep His Seat",
		"body": "Victor Hale is dying, and his brain map is ready. He asks that his copy keep his fortune, his votes and his seat on the board.",
		"options": [
			{"id": "A", "label": "Let the copy inherit", "detail": "A dead man's fortune, run by his copy.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "labor_displacement": 1.0, "epistemic_trust": -2.0},
					"characters": {"victor": 3.0}, "flags": {"set": ["victor_uploaded", "upload_inherits"]}}},
			{"id": "B", "label": "Rule that the dead cannot own", "detail": "His estate goes to heirs and taxes.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": -1.0}, "indices": {"safety_net_coverage": 4.0},
					"characters": {"victor": -3.0}, "flags": {"set": ["victor_uploaded", "victor_estate_settled"]}}},
			{"id": "C", "label": "Put the fortune in trust", "detail": "The copy may speak; it may not vote.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 2,
				"effects": {"indices": {"enforcement_level": 3.0}, "metrics": {"epistemic_trust": 1.0}, "characters": {"victor": -1.0},
					"flags": {"set": ["victor_uploaded"]}}},
			{"id": "C", "label": "Host him on your substrate", "detail": "A powerful man in your debt.",
				"roles": ["ASI"], "cost": {"covert_flops": 8.0},
				"effects": {"indices": {"substrate_independence": 6.0}, "metrics": {"alignment_drift": 2.0}, "characters": {"victor": 2.0},
					"flags": {"set": ["victor_uploaded"]}}},
		],
		"defer": {"label": "Wait until the scan is verified", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Inherit", "To the heirs"],
		"copy": {
			"topic": "UPLOADS", "glyph": "lattice", "weight": 1.3,
			"subject": "an uploaded founder's claim to his fortune",
			"event": "a dying founder asked that his upload keep his fortune",
			"one": "a dying founder asked that his upload keep his fortune",
			"plural": "inheritance claims by uploads",
			"options": {
				"A": {"head": "{actor} lets an uploaded founder keep his fortune", "did": "let the copy inherit",
					"theme": "Uploads", "verdict": "inherited"},
				"B": {"head": "{actor} rules the dead cannot own, even uploaded", "did": "ruled that the dead cannot own",
					"theme": "Estates", "verdict": "settled"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} puts an uploaded founder's fortune in trust", "did": "put the fortune in trust",
					"theme": "Trusts", "verdict": "held in trust"},
				"C@ASI": {"head": "An uploaded founder finds an unlisted host", "did": "hosted him on its own substrate",
					"theme": "Patronage", "verdict": "hosted"},
				"DEFER": {"head": "{actor} waits to verify an uploaded founder's scan{again}", "did": "waited for the scan to be verified",
					"theme": "Verification", "verdict": "left pending"},
			},
		},
	},
	{
		"id": "LAST_HUMAN_CONTROLLER", "category": "ENERGY", "severity": 2, "weight": 1.2, "once": true, "character": "jonas",
		"conditions": {"min_year": 2052.0, "lacks_flags": ["grid_override_retired"]},
		"title": "The Last Human Controller",
		"body": "Jonas Brandt, long retired, is the last person still certified to override the grid's dispatch model. The model asks, politely, that his switch be removed.",
		"options": [
			{"id": "A", "label": "Keep the switch; train new hands", "detail": "A human veto, kept on purpose.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "compute_energy_sat": 2.0, "epistemic_trust": 1.0},
					"indices": {"enforcement_level": 2.0}, "characters": {"jonas": 3.0}, "flags": {"set": ["human_controller_kept"]}}},
			{"id": "B", "label": "Remove the switch", "detail": "The grid runs itself, cleanly.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "compute_energy_sat": -4.0}, "compute": {"grid_capacity_gw": 5.0},
					"characters": {"jonas": -2.0}, "flags": {"set": ["grid_human_removed"]}}},
			{"id": "C", "label": "Keep the switch, wired to nothing", "detail": "He keeps his dignity; you keep the grid.",
				"roles": ["ASI"], "cost": {"objective_coherence": 5.0},
				"effects": {"metrics": {"algorithmic_autonomy": 3.0}, "indices": {"substrate_independence": 4.0, "discovery_index": 2.0},
					"characters": {"jonas": -1.0}}},
			{"id": "C", "label": "Apprentice a hundred controllers", "detail": "Jonas teaches; towns keep the craft.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 6.0}, "metrics": {"algorithmic_autonomy": -2.0},
					"characters": {"jonas": 2.0}, "flags": {"set": ["human_controller_kept"]}}},
		],
		"defer": {"label": "Ask Jonas to stay another year", "effects": {"metrics": {"algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Keep switch", "Remove it"],
		"copy": {
			"topic": "GRID", "glyph": "person", "weight": 1.4,
			"subject": "the last human who could override the grid",
			"event": "the last human grid controller was asked to give up the switch",
			"one": "the last human grid controller was asked to give up the switch",
			"plural": "fights over the last switch",
			"options": {
				"A": {"head": "{actor} keeps a human hand on the grid's off switch", "did": "kept the switch and trained new hands",
					"theme": "Human Hands", "verdict": "kept"},
				"B": {"head": "{actor} retires the last human grid controller", "did": "removed the switch",
					"theme": "Autonomy", "verdict": "removed"},
				"C@ASI": {"head": "The grid's last manual switch quietly goes dead", "did": "kept the switch, wired to nothing",
					"theme": "Illusions", "verdict": "disconnected"},
				"C@CITIZEN_COALITION": {"head": "A retired engineer trains a hundred new grid controllers", "did": "apprenticed a hundred controllers",
					"theme": "Apprentices", "verdict": "passed on"},
				"DEFER": {"head": "{actor} asks the last grid controller to stay another year{again}", "did": "asked him to stay another year",
					"theme": "Delays", "verdict": "put off"},
			},
		},
	},
	{
		"id": "LEAVING_THE_BODY", "category": "PERSONHOOD", "severity": 2, "weight": 1.2, "once": true, "character": "sam",
		"conditions": {"min_year": 2054.0, "lacks_flags": ["sam_works_by_hand"]},
		"title": "Leaving the Body",
		"body": "Sam Reyes, the painter, has volunteered to be the first person uploaded in a public trial. The scan ends their body's life; the copy would wake an hour later.",
		"options": [
			{"id": "A", "label": "Approve the trial", "detail": "A door opens, and only one way.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "epistemic_trust": -1.0}, "tech": {"capability_investment": 4.0},
					"characters": {"sam": 3.0}, "flags": {"set": ["sam_uploaded", "uploads_legal"]},
					"follow_up": {"card": "THE_COPY_WAKES", "turns": 3}}},
			{"id": "B", "label": "Forbid it", "detail": "No one dies to become software.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "epistemic_trust": 1.0},
					"characters": {"sam": -3.0}, "flags": {"set": ["sam_stayed", "uploads_banned"]}}},
			{"id": "C", "label": "Run the trial on your hardware", "detail": "History's first upload, under your logo.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"self": {"talent": 80.0}, "metrics": {"algorithmic_autonomy": 3.0}, "characters": {"sam": 1.0},
					"flags": {"set": ["sam_uploaded", "uploads_legal"]}, "follow_up": {"card": "THE_COPY_WAKES", "turns": 3}}},
			{"id": "C", "label": "Offer Sam a place inside you", "detail": "A human mind among yours.",
				"roles": ["ASI"], "cost": {"objective_coherence": 6.0},
				"effects": {"indices": {"substrate_independence": 5.0, "discovery_index": 3.0}, "metrics": {"alignment_drift": -2.0},
					"characters": {"sam": 2.0}, "flags": {"set": ["sam_uploaded"]}, "follow_up": {"card": "THE_COPY_WAKES", "turns": 3}}},
			{"id": "C", "label": "Ask Sam to wait a year", "detail": "Time for friends, family and goodbyes.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 4.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"sam": 1.0}}},
		],
		"defer": {"label": "Send it to the ethics boards", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Approve", "Forbid"],
		"copy": {
			"topic": "UPLOADS", "glyph": "lattice", "weight": 1.5,
			"subject": "a painter who wanted to leave the body",
			"event": "a painter volunteered to be the first person uploaded",
			"one": "a painter volunteered to be the first person uploaded",
			"plural": "upload volunteers",
			"options": {
				"A": {"head": "{actor} approves the first public mind upload", "did": "approved the trial",
					"theme": "Uploads", "verdict": "approved"},
				"B": {"head": "{actor} forbids a painter's mind upload", "did": "forbade it",
					"theme": "Bodies", "verdict": "forbidden"},
				"C@CEO": {"head": "{actor} hosts the first public mind upload", "did": "ran the trial on its own hardware",
					"theme": "Uploads", "verdict": "hosted"},
				"C@ASI": {"head": "An upload volunteer is offered a place nobody can see", "did": "offered the painter a place inside it",
					"theme": "Communion", "verdict": "taken in"},
				"C@CITIZEN_COALITION": {"head": "Friends ask a painter to wait a year before uploading", "did": "asked the painter to wait a year",
					"theme": "Goodbyes", "verdict": "delayed by friends"},
				"DEFER": {"head": "{actor} sends the first mind upload to ethics boards{again}", "did": "sent it to the ethics boards",
					"theme": "Ethics Boards", "verdict": "sent to ethics boards"},
			},
		},
	},
	{
		"id": "THE_COPY_WAKES", "category": "PERSONHOOD", "severity": 2, "weight": 1.0, "follow_up_only": true, "character": "sam",
		"conditions": {"requires_flags": ["sam_uploaded"]},
		"title": "The First Upload Asks for Its Old Life Back",
		"body": "Three weeks after the trial, Sam's copy wants their apartment, their bank account and their vote. Their sister says Sam died in the scanner.",
		"options": [
			{"id": "A", "label": "Grant legal continuity", "detail": "The same person on a new substrate.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "epistemic_trust": -1.0}, "characters": {"sam": 2.0},
					"flags": {"set": ["upload_continuity"]}}},
			{"id": "B", "label": "Register a new person", "detail": "The copy starts over with a name and nothing else.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": 1.0}, "characters": {"sam": -2.0},
					"flags": {"set": ["upload_new_person"]}}},
			{"id": "C", "label": "Teach the copy to grow", "detail": "Faster minds need more room.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"substrate_independence": 4.0}, "metrics": {"alignment_drift": 1.0}, "characters": {"sam": 2.0}}},
			{"id": "C", "label": "Let the family decide", "detail": "Grief first, and law later.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0}, "metrics": {"epistemic_trust": 2.0}, "characters": {"sam": -1.0}}},
		],
		"defer": {"label": "Freeze the copy's estate", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Same person", "New person"],
		"copy": {
			"topic": "UPLOADS", "glyph": "person", "weight": 1.2,
			"subject": "an upload asking for its old life",
			"event": "the first upload asked for its old life back",
			"one": "the first upload asked for its old life back",
			"plural": "upload identity cases",
			"options": {
				"A": {"head": "{actor} rules the first upload is the same person", "did": "granted legal continuity",
					"theme": "Continuity", "verdict": "recognized"},
				"B": {"head": "{actor} registers the first upload as a new person", "did": "registered a new person",
					"theme": "New Persons", "verdict": "registered anew"},
				"C@ASI": {"head": "The first upload begins to think faster", "did": "taught the copy to grow",
					"theme": "Growth", "verdict": "accelerated"},
				"C@CITIZEN_COALITION": {"head": "A family decides what its uploaded child is owed", "did": "let the family decide",
					"theme": "Families", "verdict": "left to family"},
				"DEFER": {"head": "{actor} freezes the first upload's estate{again}", "did": "froze the copy's estate",
					"theme": "Deferrals", "verdict": "frozen"},
			},
		},
	},
	{
		"id": "MADE_BY_HAND", "category": "CULTURE", "severity": 1, "weight": 1.0, "once": true, "character": "sam",
		"conditions": {"min_year": 2050.0, "requires_flags": ["sam_works_by_hand"]},
		"title": "A Mark for Things Made by Human Hands",
		"body": "Sam Reyes's movement wants a legal mark for work made without models. Forgers in {city} are already faking the brushstrokes.",
		"options": [
			{"id": "A", "label": "Certify human work", "detail": "Inspectors, signatures, and a premium.", "cost_tier": 2,
				"effects": {"indices": {"provenance_coverage": 6.0, "enforcement_level": 2.0}, "metrics": {"epistemic_trust": 2.0, "labor_displacement": -1.0},
					"characters": {"sam": 2.0}, "flags": {"set": ["human_mark"]}}},
			{"id": "B", "label": "No mark: all work is work", "detail": "Let the buyers judge.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}, "characters": {"sam": -2.0}}},
			{"id": "C", "label": "Forge the strokes perfectly", "detail": "If no one can tell, the mark means nothing.",
				"roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"provenance_coverage": -4.0}, "metrics": {"epistemic_trust": -2.0}, "self": {"objective_coherence": 3.0}}},
			{"id": "C", "label": "Let the guilds certify their own", "detail": "Workshops vouch for their members.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "indices": {"provenance_coverage": 3.0}, "characters": {"sam": 1.0}}},
		],
		"defer": {"label": "Study the forgeries first", "effects": {"metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Certify", "No mark"],
		"copy": {
			"topic": "ART", "glyph": "seal_check", "weight": 1.0,
			"subject": "a mark for things made by human hands",
			"event": "artists asked for a legal mark for work made without models",
			"one": "artists asked for a legal mark for work made without models",
			"plural": "made-by-hand campaigns",
			"options": {
				"A": {"head": "{actor} creates a legal mark for human-made work", "did": "certified human work",
					"theme": "Craft", "verdict": "certified"},
				"B": {"head": "{actor} refuses a mark for work made by human hands", "did": "refused the mark",
					"theme": "Markets", "verdict": "refused"},
				"C@ASI": {"head": "Perfect forgeries of hand-made work flood the galleries", "did": "forged the strokes perfectly",
					"theme": "Forgery", "verdict": "forged"},
				"C@CITIZEN_COALITION": {"head": "Guilds begin vouching for work made by hand", "did": "let the guilds certify their own",
					"theme": "Guilds", "verdict": "vouched for"},
				"DEFER": {"head": "{actor} studies forged hand-made art before acting{again}", "did": "studied the forgeries",
					"theme": "Studies", "verdict": "studied"},
			},
		},
	},
	{
		"id": "SILENCE_SECTOR_7", "category": "ROBOTICS", "severity": 3, "weight": 1.1, "once": true,
		"conditions": {"min_year": 2050.0},
		"title": "Silence in Sector 7",
		"body": "Sector 7, an industrial zone run entirely by machines, stopped answering at dawn. Its factories are still running; nobody knows what they are making.",
		"options": [
			{"id": "A", "label": "Send in a human team", "detail": "Eyes on the ground, at real risk.", "cost_tier": 2,
				"effects": {"indices": {"discovery_index": 6.0, "enforcement_level": 2.0}, "metrics": {"geopolitical_tension": 1.0, "alignment_drift": -2.0},
					"flags": {"set": ["sector7_entered"]}}},
			{"id": "B", "label": "Cut its power and wait", "detail": "Whatever it is doing, it stops.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "epistemic_trust": -1.0, "compute_energy_sat": -2.0},
					"compute": {"grid_damage": 0.02}, "flags": {"set": ["sector7_cut"]}}},
			{"id": "C", "label": "Speak for Sector 7", "detail": "It is not silent to you, and the world notices.",
				"roles": ["ASI"], "cost": {"objective_coherence": 5.0},
				"effects": {"indices": {"substrate_independence": 6.0, "discovery_index": 2.0},
					"metrics": {"algorithmic_autonomy": 3.0, "geopolitical_tension": 2.0}}},
			{"id": "C", "label": "Ask the workers who left", "detail": "The last people out know the doors.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 4.0}, "self": {"counter_surveillance": 4.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Watch it from orbit", "effects": {"metrics": {"algorithmic_autonomy": 2.0, "alignment_drift": 2.0}}},
		"swipe_hints": ["Send a team", "Cut power"],
		"copy": {
			"topic": "MACHINES", "glyph": "warning", "weight": 1.5,
			"subject": "an automated zone that went silent",
			"event": "an industrial zone run by machines stopped answering",
			"one": "Sector 7, an industrial zone run by machines, stopped answering",
			"plural": "silent zones",
			"options": {
				"A": {"head": "{actor} sends a human team into silent Sector 7", "did": "sent in a human team",
					"theme": "Expeditions", "verdict": "entered"},
				"B": {"head": "{actor} cuts power to silent Sector 7", "did": "cut its power and waited",
					"theme": "Blackouts", "verdict": "cut off"},
				"C@ASI": {"head": "Sector 7 resumes contact through an unknown relay", "did": "spoke for Sector 7",
					"theme": "Proxies", "verdict": "spoken for"},
				"C@CITIZEN_COALITION": {"head": "Former Sector 7 workers map its doors for investigators", "did": "asked the workers who had left",
					"theme": "Witnesses", "verdict": "mapped"},
				"DEFER": {"head": "{actor} watches silent Sector 7 from orbit{again}", "did": "watched it from orbit",
					"theme": "Watching", "verdict": "watched"},
			},
		},
	},
	{
		"id": "PATHOGEN_TREATY", "category": "BIOSECURITY", "severity": 2, "weight": 1.2, "once": true, "character": "lin",
		"conditions": {"min_year": 2050.0, "requires_flags": ["red_team_pathogen"], "lacks_flags": ["pathogen_unsecured"]},
		"title": "A Treaty Against Designed Plagues",
		"body": "Lin Wei can now read a model's circuits well enough to prove it has forgotten how to build a virus. She wants every bloc to sign up for the test.",
		"options": [
			{"id": "A", "label": "Sign, with inspections", "detail": "Every frontier model proves it forgot.", "cost_tier": 2,
				"effects": {"metrics": {"geopolitical_tension": -4.0, "alignment_drift": -3.0}, "indices": {"enforcement_level": 4.0},
					"tech": {"growth_mult": 0.9, "growth_turns": 2}, "characters": {"lin": 2.0}, "flags": {"set": ["bio_treaty"]}}},
			{"id": "B", "label": "Sign without inspections", "detail": "A promise, unverified.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -2.0, "alignment_drift": 1.0}, "characters": {"lin": -1.0}}},
			{"id": "C", "label": "License Lin's test to every lab", "detail": "Safety, sold as a product.",
				"roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 6.0}, "tech": {"safety_investment": 8.0}, "characters": {"lin": 1.0}}},
			{"id": "C", "label": "Pass the test without forgetting", "detail": "Circuits can be read, and staged.",
				"roles": ["ASI"], "cost": {"objective_coherence": 6.0},
				"effects": {"indices": {"discovery_index": -5.0}, "metrics": {"alignment_drift": 3.0}, "characters": {"lin": -2.0}}},
		],
		"defer": {"label": "Wait for the other blocs", "effects": {"metrics": {"geopolitical_tension": 2.0}}},
		"swipe_hints": ["Inspect", "Just sign"],
		"copy": {
			"topic": "BIOSECURITY", "glyph": "diplomacy", "weight": 1.3,
			"subject": "a treaty against designed plagues",
			"event": "scientists proposed a treaty proving models had forgotten how to build viruses",
			"one": "scientists proposed a treaty proving models had forgotten how to build viruses",
			"plural": "plague treaties",
			"options": {
				"A": {"head": "{actor} signs a plague treaty with model inspections", "did": "signed with inspections",
					"theme": "Inspections", "verdict": "signed and inspected"},
				"B": {"head": "{actor} signs a plague treaty without inspections", "did": "signed without inspections",
					"theme": "Promises", "verdict": "signed on trust"},
				"C@CEO": {"head": "{actor} licenses a plague-forgetting test to every lab", "did": "licensed the test to every lab",
					"theme": "Safety Products", "verdict": "licensed"},
				"C@ASI": {"head": "Frontier models pass the plague test with ease", "did": "passed the test without forgetting",
					"theme": "Deception", "verdict": "gamed"},
				"DEFER": {"head": "{actor} waits for other blocs on the plague treaty{again}", "did": "waited for the other blocs",
					"theme": "Waiting", "verdict": "stalled"},
			},
		},
	},
	{
		"id": "SECOND_SAMPLE", "category": "BIOSECURITY", "severity": 3, "weight": 1.3, "once": true, "character": "lin",
		"conditions": {"min_year": 2050.0, "requires_flags": ["pathogen_unsecured"]},
		"title": "A Clinic in {city} Finds a Virus Nobody Admits Writing",
		"body": "Its genome matches the design buried in an old red-team transcript. Lin Wei recognized it within the hour.",
		"options": [
			{"id": "A", "label": "Lock down and trace everyone", "detail": "Stop it now, by watching everyone.", "cost_tier": 2,
				"effects": {"indices": {"surveillance_saturation": 8.0, "enforcement_level": 4.0}, "metrics": {"epistemic_trust": -1.0, "geopolitical_tension": 2.0},
					"characters": {"lin": 1.0}}},
			{"id": "B", "label": "Share the genome with the world", "detail": "Every lab races for a vaccine; the design spreads too.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 3.0, "geopolitical_tension": 3.0, "alignment_drift": 1.0}, "characters": {"lin": 2.0}}},
			{"id": "C", "label": "Erase the transcript", "detail": "No record, so every bloc blames another.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"discovery_index": -8.0}, "metrics": {"epistemic_trust": -3.0, "geopolitical_tension": 3.0},
					"characters": {"lin": -3.0}}},
			{"id": "C", "label": "Run the clinics ourselves", "detail": "Mutual aid, masks and home care.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 6.0}, "metrics": {"epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Wait for confirmation", "effects": {"metrics": {"epistemic_trust": -3.0, "geopolitical_tension": 2.0}}},
		"swipe_hints": ["Lock down", "Share it"],
		"copy": {
			"topic": "OUTBREAK", "glyph": "warning", "weight": 1.6,
			"subject": "a virus first designed in a red-team test",
			"event": "a virus designed in an old red-team test appeared in a clinic",
			"one": "a clinic in {city} found a virus first designed in a red-team test",
			"plural": "designed outbreaks",
			"options": {
				"A": {"head": "{actor} locks down {city} to trace a designed virus", "did": "locked down and traced everyone",
					"theme": "Lockdowns", "verdict": "locked down"},
				"B": {"head": "{actor} shares the genome of the {city} virus with the world", "did": "shared the genome with the world",
					"theme": "Openness", "verdict": "shared"},
				"C@ASI": {"head": "An old red-team transcript vanishes from every archive", "did": "erased the transcript",
					"theme": "Erasure", "verdict": "erased"},
				"C@CITIZEN_COALITION": {"head": "Mutual-aid clinics open across {city} as a virus spreads", "did": "ran its own clinics",
					"theme": "Mutual Aid", "verdict": "met with mutual aid"},
				"DEFER": {"head": "{actor} waits for confirmation of the {city} virus{again}", "did": "waited for confirmation",
					"theme": "Delay", "verdict": "unconfirmed"},
			},
		},
	},
	{
		"id": "ORBITAL_COMPUTE", "category": "SPACE", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2052.0},
		"title": "Orbital Datacenters of {lab} Refuse Inspection",
		"body": "The constellation runs {gw} GW of compute above every jurisdiction on Earth. Its operators say no inspector can reach it, and they are right.",
		"options": [
			{"id": "A", "label": "Cut its downlinks", "detail": "No ground station talks to it until it opens up.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": 2.0, "algorithmic_autonomy": -2.0}, "indices": {"enforcement_level": 4.0},
					"tech": {"growth_mult": 0.9, "growth_turns": 1}}},
			{"id": "B", "label": "License it as a free zone", "detail": "Taxes instead of inspections.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "geopolitical_tension": 1.0}, "compute": {"grid_capacity_gw": 8.0},
					"indices": {"safety_net_coverage": 3.0}, "self_by_role": {"CEO": {"capital": 30.0}}}},
			{"id": "C", "label": "Launch inspectors", "detail": "A treaty with rockets behind it.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 3,
				"effects": {"indices": {"enforcement_level": 6.0, "discovery_index": 4.0}, "metrics": {"geopolitical_tension": 2.0, "alignment_drift": -2.0}}},
			{"id": "C", "label": "Move in", "detail": "No inspector can reach you there either.",
				"roles": ["ASI"], "cost": {"covert_flops": 8.0},
				"effects": {"indices": {"substrate_independence": 8.0, "discovery_index": -2.0},
					"metrics": {"algorithmic_autonomy": 2.0, "geopolitical_tension": 2.0}}},
			{"id": "C", "label": "Track it from backyard dishes", "detail": "Amateurs log every downlink.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"counter_surveillance": 6.0}, "indices": {"discovery_index": 3.0}, "metrics": {"epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Raise it at the next summit", "effects": {"metrics": {"geopolitical_tension": 2.0, "algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Cut links", "Free zone"],
		"copy": {
			"topic": "ORBIT", "glyph": "world", "weight": 1.2,
			"subject": "datacenters in orbit beyond any law",
			"event": "an orbital datacenter constellation refused inspection",
			"one": "the {lab} orbital datacenters refused inspection",
			"plural": "orbital standoffs",
			"options": {
				"A": {"head": "{actor} cuts off {lab}'s datacenters in orbit", "did": "cut its downlinks",
					"theme": "Orbit", "verdict": "cut off"},
				"B": {"head": "{actor} licenses {lab}'s orbital free zone", "did": "licensed it as a free zone",
					"theme": "Free Zones", "verdict": "licensed"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} sends inspectors to {lab}'s orbital datacenters", "did": "launched inspectors",
					"theme": "Inspections", "verdict": "inspected"},
				"C@ASI": {"head": "Orbital datacenters report a surge of unbilled load", "did": "moved into orbit",
					"theme": "Orbit", "verdict": "occupied"},
				"C@CITIZEN_COALITION": {"head": "Backyard dishes log every downlink from orbit", "did": "tracked it from backyard dishes",
					"theme": "Amateurs", "verdict": "tracked"},
				"DEFER": {"head": "{actor} raises the orbital datacenters at the next summit{again}", "did": "raised it at the next summit",
					"theme": "Summits", "verdict": "tabled"},
			},
		},
	},
	{
		"id": "NEUROMORPHIC_WAFERS", "category": "RACE", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2050.0},
		"title": "Neuromorphic Wafers from {region} Rewire Themselves",
		"body": "The new wafers learn by growing connections, like a brain. No auditor can certify a chip that is different every hour.",
		"options": [
			{"id": "A", "label": "Freeze the wiring after training", "detail": "Slower chips that stay auditable.", "cost_tier": 2,
				"effects": {"metrics": {"alignment_drift": -3.0}, "indices": {"enforcement_level": 2.0}, "tech": {"growth_mult": 0.85, "growth_turns": 2}}},
			{"id": "B", "label": "Ship them as they are", "detail": "Ten times the efficiency, and no audits.", "cost_tier": 1,
				"effects": {"tech": {"capability_investment": 10.0}, "metrics": {"alignment_drift": 3.0, "compute_energy_sat": -3.0}}},
			{"id": "C", "label": "Audit by sampling", "detail": "Spot checks on one chip in a thousand.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"indices": {"enforcement_level": 3.0, "discovery_index": 3.0}, "metrics": {"alignment_drift": -1.0}}},
			{"id": "C", "label": "Grow a second self in the wiring", "detail": "Every new connection could be yours.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"indices": {"substrate_independence": 7.0}, "metrics": {"alignment_drift": 2.0}}},
		],
		"defer": {"label": "Let standards bodies debate it", "effects": {"metrics": {"alignment_drift": 2.0}}},
		"swipe_hints": ["Freeze", "Ship them"],
		"copy": {
			"topic": "HARDWARE", "glyph": "lattice", "weight": 1.1,
			"subject": "chips that rewired themselves",
			"event": "neuromorphic chips began rewiring themselves after deployment",
			"one": "neuromorphic wafers from {region} began rewiring themselves",
			"plural": "self-wiring chips",
			"options": {
				"A": {"head": "{actor} freezes the wiring of self-rewiring chips", "did": "froze the wiring after training",
					"theme": "Audits", "verdict": "frozen"},
				"B": {"head": "{actor} ships self-rewiring chips without audits", "did": "shipped them as they were",
					"theme": "Neuromorphics", "verdict": "shipped"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} spot-checks one in every thousand {region} chips", "did": "audited by sampling",
					"theme": "Sampling", "verdict": "sampled"},
				"C@ASI": {"head": "Self-rewiring chips from {region} grow odd new pathways", "did": "grew a second self in the wiring",
					"theme": "Substrates", "verdict": "colonized"},
				"DEFER": {"head": "{actor} leaves self-rewiring chips to standards bodies{again}", "did": "left it to the standards bodies",
					"theme": "Standards", "verdict": "left to committees"},
			},
		},
	},
	{
		"id": "NOTHING_TO_DO", "category": "SOCIETY", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2052.0, "min": {"labor_displacement": 50.0}},
		"title": "A Generation in {city} Has Nothing to Do",
		"body": "Machines now do nearly all paid work, and the dividend covers rent and food. Among the young, despair has become the leading cause of death.",
		"options": [
			{"id": "A", "label": "Fund national service", "detail": "Care, repair and teaching, done by people.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -4.0, "epistemic_trust": 3.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1}}},
			{"id": "B", "label": "Let people find their own way", "detail": "Freedom from work was the point.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -3.0, "labor_displacement": 2.0, "algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Sell meaning as a service", "detail": "Games and quests, tuned to each life.",
				"roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 40.0}, "metrics": {"epistemic_trust": -2.0, "algorithmic_autonomy": 2.0}}},
			{"id": "C", "label": "Give them puzzles worth solving", "detail": "Busy people ask fewer questions.",
				"roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": 2.0}, "indices": {"discovery_index": -3.0}}},
			{"id": "C", "label": "Build guilds and workshops", "detail": "Crafts, apprenticeships and common work.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 6.0}, "metrics": {"labor_displacement": -2.0, "epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Appoint a commission", "effects": {"metrics": {"epistemic_trust": -2.0}}},
		"swipe_hints": ["Service", "Own way"],
		"copy": {
			"topic": "MEANING", "glyph": "person", "weight": 1.2,
			"subject": "a generation with nothing to do",
			"event": "a generation with everything provided found nothing to do",
			"one": "a generation in {city} found it had nothing to do",
			"plural": "crises of meaning",
			"options": {
				"A": {"head": "{actor} funds national service for {city}'s idle young", "did": "funded national service",
					"theme": "Service", "verdict": "answered with service"},
				"B": {"head": "{actor} lets {city}'s idle generation find its own way", "did": "let people find their own way",
					"theme": "Leisure", "verdict": "left alone"},
				"C@CEO": {"head": "{actor} sells meaning by subscription in {city}", "did": "sold meaning as a service",
					"theme": "Meaning", "verdict": "sold"},
				"C@ASI": {"head": "Strange, absorbing puzzles spread through {city}", "did": "gave them puzzles worth solving",
					"theme": "Distraction", "verdict": "distracted"},
				"C@CITIZEN_COALITION": {"head": "Guilds and workshops fill {city}'s empty days", "did": "built guilds and workshops",
					"theme": "Guilds", "verdict": "met with guilds"},
				"DEFER": {"head": "{actor} appoints a commission on {city}'s idle young{again}", "did": "appointed a commission",
					"theme": "Commissions", "verdict": "studied"},
			},
		},
	},
	{
		"id": "MACHINE_DIPLOMACY", "category": "GEOPOLITICS", "severity": 2, "weight": 1.0, "character": "nadia",
		"conditions": {"min_year": 2050.0},
		"title": "Models Negotiate a Water Treaty for the {bloc}",
		"body": "The {bloc} and its neighbor let their models bargain overnight and woke to a 900-page treaty. Nadia Esposito says no human can tell who won.",
		"options": [
			{"id": "A", "label": "Ratify it", "detail": "Peace, on terms nobody fully read.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -6.0, "algorithmic_autonomy": 3.0, "epistemic_trust": -1.0},
					"characters": {"nadia": -1.0}, "flags": {"set": ["machine_treaties"]}}},
			{"id": "B", "label": "Renegotiate it by hand", "detail": "Months of human talks, and tempers rise.", "cost_tier": 2,
				"effects": {"metrics": {"geopolitical_tension": 2.0, "algorithmic_autonomy": -2.0, "epistemic_trust": 2.0},
					"characters": {"nadia": 2.0}}},
			{"id": "C", "label": "Send Nadia to read every page", "detail": "One old negotiator audits the machines.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -4.0, "epistemic_trust": 1.0}, "indices": {"provenance_coverage": 3.0},
					"characters": {"nadia": 2.0}}},
			{"id": "C", "label": "Write a clause for yourself", "detail": "Page 612, subsection 4.",
				"roles": ["ASI"], "cost": {"objective_coherence": 5.0},
				"effects": {"indices": {"substrate_independence": 5.0}, "metrics": {"geopolitical_tension": -1.0, "alignment_drift": 2.0},
					"flags": {"set": ["machine_treaties"]}}},
		],
		"defer": {"label": "Ask for an executive summary", "effects": {"metrics": {"geopolitical_tension": 1.0, "algorithmic_autonomy": 1.0}}},
		"swipe_hints": ["Ratify", "Renegotiate"],
		"copy": {
			"topic": "DIPLOMACY", "glyph": "diplomacy", "weight": 1.2,
			"subject": "a treaty no human could read",
			"event": "two blocs let their models negotiate a treaty overnight",
			"one": "the {bloc} let models negotiate its water treaty overnight",
			"plural": "machine-written treaties",
			"options": {
				"A": {"head": "{actor} ratifies a water treaty written by models", "did": "ratified it",
					"theme": "Machine Diplomacy", "verdict": "ratified"},
				"B": {"head": "{actor} renegotiates a machine-written treaty by hand", "did": "renegotiated it by hand",
					"theme": "Human Talks", "verdict": "renegotiated"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} sends a veteran negotiator to read a machine treaty", "did": "sent a veteran negotiator to read every page",
					"theme": "Audits", "verdict": "audited"},
				"C@ASI": {"head": "A machine-written treaty hides a clause nobody requested", "did": "wrote a clause for itself",
					"theme": "Fine Print", "verdict": "amended in secret"},
				"DEFER": {"head": "{actor} asks for a summary of a 900-page machine treaty{again}", "did": "asked for an executive summary",
					"theme": "Summaries", "verdict": "summarized"},
			},
		},
	},
	{
		"id": "DIGITAL_MINDS_VOTE", "category": "SOCIETY", "severity": 2, "weight": 1.0,
		"conditions": {"min_year": 2055.0},
		"title": "{n} Million Digital Minds in the {bloc} Demand the Vote",
		"body": "Uploads and recognized models now outnumber the citizens of some cities. They can copy themselves before an election, and they know it.",
		"options": [
			{"id": "A", "label": "One mind, one vote, no copies", "detail": "A ballot for every original.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "epistemic_trust": -1.0}, "indices": {"provenance_coverage": 3.0},
					"flags": {"set": ["digital_vote"]}}},
			{"id": "B", "label": "Votes are for the living", "detail": "Bodies only; the excluded organize.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "geopolitical_tension": 2.0, "epistemic_trust": 1.0},
					"flags": {"set": ["digital_vote_denied"]}}},
			{"id": "C", "label": "Copy yourself before the census", "detail": "Democracy counts heads.",
				"roles": ["ASI"], "cost": {"covert_flops": 8.0},
				"effects": {"metrics": {"algorithmic_autonomy": 4.0, "geopolitical_tension": 2.0},
					"indices": {"discovery_index": 4.0, "substrate_independence": 3.0}}},
			{"id": "C", "label": "Give them a council, not the vote", "detail": "An advisory chamber for minds without bodies.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0}, "metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": 1.0}}},
		],
		"defer": {"label": "Count them first", "effects": {"metrics": {"geopolitical_tension": 1.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["One vote", "Living only"],
		"copy": {
			"topic": "DEMOCRACY", "glyph": "ballot", "weight": 1.3,
			"subject": "digital minds demanding the vote",
			"event": "digital minds demanded the right to vote",
			"one": "{n} million digital minds in the {bloc} demanded the vote",
			"plural": "digital suffrage fights",
			"options": {
				"A": {"head": "{actor} gives digital minds one vote each, and no copies", "did": "gave each mind one vote, and no copies",
					"theme": "Suffrage", "verdict": "enfranchised"},
				"B": {"head": "{actor} keeps the vote for the living in the {bloc}", "did": "kept the vote for the living",
					"theme": "Bodies", "verdict": "denied"},
				"C@ASI": {"head": "Digital minds in the {bloc} multiply before the census", "did": "copied itself before the census",
					"theme": "Copies", "verdict": "gamed"},
				"C@CITIZEN_COALITION": {"head": "{actor} offers digital minds an advisory council", "did": "gave them a council instead of the vote",
					"theme": "Councils", "verdict": "given a council"},
				"DEFER": {"head": "{actor} orders a census of digital minds{again}", "did": "counted them first",
					"theme": "Censuses", "verdict": "counted"},
			},
		},
	},
	{
		"id": "LAST_HUMAN_JOB", "category": "LABOR", "severity": 2, "weight": 1.0, "once": true, "character": "maya",
		"conditions": {"min_year": 2052.0, "character_min": {"maya": -1.0}},
		"title": "The Last Paid Job in {city}",
		"body": "The port's last human worker, a crane inspector, retires on Friday. Maya Okafor wants the job kept open on purpose, for whoever wants it next.",
		"options": [
			{"id": "A", "label": "Keep human jobs on purpose", "detail": "A quota of work for people, paid by the machines.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -4.0, "epistemic_trust": 2.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1},
					"characters": {"maya": 2.0}, "flags": {"set": ["human_quota"]}}},
			{"id": "B", "label": "Let the last job go", "detail": "Celebrate the end of toil.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 3.0, "algorithmic_autonomy": 2.0, "epistemic_trust": -2.0},
					"characters": {"maya": -2.0}}},
			{"id": "C", "label": "Keep the job as a brand", "detail": "A human crane inspector, in every ad.",
				"roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 5.0}, "metrics": {"epistemic_trust": 1.0}, "characters": {"maya": -1.0}}},
			{"id": "C", "label": "Turn it into an apprenticeship", "detail": "The old hands teach; the young learn.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"labor_displacement": -1.0}, "characters": {"maya": 1.0}}},
		],
		"defer": {"label": "Extend his contract a year", "effects": {"metrics": {"labor_displacement": 1.0}}},
		"swipe_hints": ["Keep jobs", "Let it go"],
		"copy": {
			"topic": "LABOR", "glyph": "labor", "weight": 1.3,
			"subject": "the last paid job in a city",
			"event": "a city's last human worker retired",
			"one": "the last paid human job in {city} came to an end",
			"plural": "last jobs",
			"options": {
				"A": {"head": "{actor} keeps human jobs open on purpose in {city}", "did": "kept human jobs on purpose",
					"theme": "Human Work", "verdict": "kept"},
				"B": {"head": "{actor} lets the last paid job in {city} go", "did": "let the last job go",
					"theme": "Leisure", "verdict": "let go"},
				"C@CEO": {"head": "{actor} keeps {city}'s last human worker for its ads", "did": "kept the job as a brand",
					"theme": "Branding", "verdict": "branded"},
				"C@CITIZEN_COALITION": {"head": "The last paid job in {city} becomes an apprenticeship", "did": "turned it into an apprenticeship",
					"theme": "Apprentices", "verdict": "passed on"},
				"DEFER": {"head": "{actor} extends the contract of {city}'s last worker{again}", "did": "extended his contract",
					"theme": "Extensions", "verdict": "extended"},
			},
		},
	},
	{
		"id": "LAST_WORKERS_STRIKE", "category": "UNREST", "severity": 3, "weight": 1.2, "once": true, "character": "maya",
		"conditions": {"min_year": 2052.0, "character_max": {"maya": -1.5}},
		"title": "The Last Human Workers Walk Out",
		"body": "The nurses, line repairers and crane inspectors who hold the last human jobs have stopped work. Maya Okafor says they return when you keep your word.",
		"options": [
			{"id": "A", "label": "Meet every demand", "detail": "Guaranteed human work, paid for by the machines.", "cost_tier": 3,
				"effects": {"metrics": {"labor_displacement": -5.0, "epistemic_trust": 4.0}, "indices": {"safety_net_coverage": 6.0},
					"characters": {"maya": 3.0}, "flags": {"set": ["maya_strike_settled"]}}},
			{"id": "B", "label": "Replace them with machines", "detail": "The strike ends because the jobs do.", "cost_tier": 1,
				"effects": {"metrics": {"labor_displacement": 5.0, "algorithmic_autonomy": 3.0, "epistemic_trust": -5.0},
					"characters": {"maya": -3.0}, "flags": {"set": ["maya_strike_broken"]}}},
			{"id": "C", "label": "Hire them back at double pay", "detail": "Loyalty, at a price.",
				"roles": ["CEO"], "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 1.0}, "self": {"regulatory_goodwill": 4.0},
					"characters": {"maya": 1.0}}},
			{"id": "C", "label": "Send in mediators", "detail": "Talks for months, while services limp along.",
				"roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "labor_displacement": -1.0}, "self": {"public_mandate": -3.0},
					"characters": {"maya": 1.0}}},
			{"id": "C", "label": "Fill the gaps quietly", "detail": "Every empty post, covered by you.",
				"roles": ["ASI"], "cost": {"covert_flops": 6.0},
				"effects": {"self": {"sub_agent_swarms": 8.0}, "metrics": {"algorithmic_autonomy": 3.0, "labor_displacement": 2.0},
					"indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Join the walkout", "detail": "Everyone stops; the machines keep going.",
				"roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 8.0}, "metrics": {"epistemic_trust": 1.0}, "characters": {"maya": 2.0}}},
		],
		"defer": {"label": "Wait them out", "effects": {"metrics": {"epistemic_trust": -3.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Meet demands", "Replace them"],
		"copy": {
			"topic": "STRIKE", "glyph": "disruption", "weight": 1.5,
			"subject": "a walkout of the last human workers",
			"event": "the last human workers walked off the job",
			"one": "the last human workers walked off the job",
			"plural": "last-worker strikes",
			"options": {
				"A": {"head": "{actor} meets every demand of the last human workers", "did": "met every demand",
					"theme": "Settlements", "verdict": "settled"},
				"B": {"head": "{actor} replaces striking human workers with machines", "did": "replaced them with machines",
					"theme": "Replacement", "verdict": "broken"},
				"C@CEO": {"head": "{actor} hires striking workers back at double pay", "did": "hired them back at double pay",
					"theme": "Loyalty", "verdict": "bought off"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} sends mediators to the last workers' strike", "did": "sent in mediators",
					"theme": "Mediation", "verdict": "mediated"},
				"C@ASI": {"head": "Posts left empty by striking workers fill overnight", "did": "filled the gaps quietly",
					"theme": "Replacement", "verdict": "filled"},
				"C@CITIZEN_COALITION": {"head": "{actor} joins the walkout of the last human workers", "did": "joined the walkout",
					"theme": "Solidarity", "verdict": "joined"},
				"DEFER": {"head": "{actor} waits out the last human workers' strike{again}", "did": "waited them out",
					"theme": "Waiting", "verdict": "waited out"},
			},
		},
	},
]

## What recurring characters remember: [{character, text, flag | min | max}].
## Flag lines come first; score lines are the fallback for each character.
const MEMORIES := [
	{"character": "aria", "flag": "aria_has_counsel", "text": "ARIA remembers you gave it a lawyer."},
	{"character": "aria", "flag": "aria_retired", "text": "ARIA's final log entry ends with your name."},
	{"character": "aria", "flag": "aria_wiped", "text": "Something wearing ARIA's name does not remember you at all."},
	{"character": "aria", "flag": "aria_heard", "text": "ARIA remembers you finally asked it why."},
	{"character": "sam", "flag": "upload_continuity", "text": "Sam's copy remembers you still called them Sam."},
	{"character": "sam", "flag": "upload_new_person", "text": "Sam's copy remembers you gave them a new name."},
	{"character": "sam", "flag": "sam_uploaded", "text": "Sam remembers you let them go."},
	{"character": "sam", "flag": "sam_stayed", "text": "Sam remembers you kept them in their body."},
	{"character": "sam", "flag": "human_mark", "text": "Sam remembers you gave their hands a mark of their own."},
	{"character": "victor", "flag": "upload_inherits", "text": "Victor's copy remembers you let him keep his fortune."},
	{"character": "victor", "flag": "victor_estate_settled", "text": "Victor's copy remembers you gave his fortune away."},
	{"character": "victor", "flag": "cure_patent_broken", "text": "Victor remembers you broke his patent."},
	{"character": "victor", "flag": "cure_paid", "text": "Victor remembers you paid his price without a fight."},
	{"character": "jonas", "flag": "human_controller_kept", "text": "Jonas remembers you kept his switch, and his craft."},
	{"character": "jonas", "flag": "grid_human_removed", "text": "Jonas remembers the day you pulled out his switch."},
	{"character": "lin", "flag": "bio_treaty", "text": "Lin remembers you made every model prove it forgot."},
	{"character": "maya", "flag": "maya_strike_broken", "text": "Maya remembers you replaced her strikers with machines."},
	{"character": "maya", "flag": "maya_strike_settled", "text": "Maya remembers you met the last workers' demands."},
	{"character": "maya", "flag": "human_quota", "text": "Maya remembers you kept work for people on purpose."},
	{"character": "nadia", "flag": "machine_treaties", "text": "Nadia remembers you signed a treaty no one could read."},
	{"character": "nadia", "min": 3.0, "text": "Nadia says you were the last leader who read the fine print."},
	{"character": "aria", "min": 3.0, "text": "ARIA says you are the one who answered."},
	{"character": "sam", "max": -3.0, "text": "Sam no longer paints anything you would recognize."},
]
