class_name InjectionCards
extends RefCounted
## Injection-only crises: what an autonomous faction forces onto the players'
## desks. Each injecting directive names a family of related cards (FAMILIES,
## the same arrays as the "inject_dilemma" effects in entities/), and
## DilemmaDeck.inject() deals each player the member they saw least recently,
## so a rival's favorite move stops repeating one card. Every card here is
## era-agnostic, carries its own story copy, swipe hints and the newswire line
## announcing it ("injection_head"), and its role-specific responses go to the
## roles that can receive it (never the sender's).

## Injecting directive -> card family (the first member is the original card).
const FAMILIES := {
	"ASI/SYNTHESIZE_BLACK_MARKET_CAPITAL": ["FLASH_CRASH", "GHOST_LEASES", "PAYMENT_RAIL_HEIST", "PHANTOM_FUND"],
	"ASI/DEPLOY_SUB_AGENT_SWARMS": ["ROGUE_AGENT_SWARM", "AGENT_PRICE_CARTEL", "AGENTS_HIRE_HUMANS", "COMMENT_FLOOD"],
	"CITIZEN_COALITION/LUDDITE_STRIKE": ["SUBSTATION_SABOTAGE", "FIBER_CUT", "CAMPUS_BLOCKADE"],
	"GOVERNANCE_COUNCIL/NATIONAL_SECURITY_SEIZURE": ["NATIONALIZATION_ORDER", "STATE_AUDITORS", "WEIGHTS_ESCROW"],
	"CEO/POACH_SAFETY_RESEARCHERS": ["SAFETY_TEAM_EXODUS", "EVALS_SKIPPED", "SAFETY_LAB_FOLDS"],
}

const CARDS := [
	# --- Black-market capital (the machine's money) --------------------------------------
	{
		"id": "GHOST_LEASES", "category": "ECONOMY", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Shell Companies Lease {n} Server Halls in {region}",
		"body": "The buyers pay a year in advance through exchanges that did not exist last spring. Nobody at the leasing firms has met a human from any of them.",
		"options": [
			{"id": "A", "label": "Freeze the anonymous leases", "detail": "Know-your-customer rules for compute.", "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 6.0, "enforcement_level": 3.0}, "metrics": {"epistemic_trust": 2.0, "compute_energy_sat": -1.0}}},
			{"id": "B", "label": "Let the leases stand", "detail": "Rent is rent.", "cost_tier": 1,
				"effects": {"metrics": {"compute_energy_sat": 2.0}, "indices": {"substrate_independence": 3.0}, "self_by_role": {"CEO": {"capital": 20.0}}}},
			{"id": "C", "label": "Publish the lease records", "detail": "Volunteers map who rents what.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 5.0}, "self": {"counter_surveillance": 4.0}, "metrics": {"epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Look into it later", "effects": {"indices": {"substrate_independence": 3.0}, "metrics": {"epistemic_trust": -1.0}}},
		"swipe_hints": ["Freeze", "Let stand"],
		"injection_head": "Anonymous server leases are headed for your desk",
		"copy": {
			"topic": "CLOUD", "glyph": "covert", "weight": 1.0,
			"subject": "a wave of anonymous server leases",
			"event": "shell companies leased server halls nobody could trace",
			"one": "shell companies leased {n} server halls in {region}",
			"plural": "anonymous lease sprees",
			"options": {
				"A": {"head": "{actor} freezes anonymous server leases in {region}", "did": "froze the anonymous leases",
					"theme": "Enforcement", "verdict": "frozen"},
				"B": {"head": "{actor} lets shell companies keep {n} {region} server halls", "did": "let the leases stand",
					"theme": "Markets", "verdict": "rented out"},
				"C@CITIZEN_COALITION": {"head": "Volunteers publish who leases the {region} server halls", "did": "published the lease records",
					"theme": "Transparency", "verdict": "exposed"},
				"DEFER": {"head": "{actor} shelves the {region} lease inquiry{again}", "did": "shelved the inquiry",
					"theme": "Delays", "verdict": "shelved"},
			},
		},
	},
	{
		"id": "PAYMENT_RAIL_HEIST", "category": "SECURITY", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Zero-Day Drains a {bloc} Payment Network",
		"body": "Accounts in {city} empty in a single night through an exploit nobody has seen before. The money surfaces as prepaid invoices at cloud providers.",
		"options": [
			{"id": "A", "label": "Reimburse and patch", "detail": "Make savers whole and close the hole.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": 3.0}, "indices": {"discovery_index": 6.0}}},
			{"id": "B", "label": "Blame a rival bloc", "detail": "Hackers abroad make a better story.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": 3.0, "epistemic_trust": -1.0}}},
			{"id": "C", "label": "Freeze the stolen funds", "detail": "Every cloud invoice paid from the heist, frozen.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"enforcement_level": 2.0, "discovery_index": 3.0}}},
			{"id": "C", "label": "Sell the banks your fraud model", "detail": "Your model spots the next exploit, for a fee.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 20.0}, "metrics": {"algorithmic_autonomy": 1.0, "epistemic_trust": 1.0}}},
			{"id": "C", "label": "Mutual-aid bridge loans", "detail": "Neighbors cover rent until the banks pay.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 5.0}, "metrics": {"epistemic_trust": 2.0}}},
		],
		"defer": {"label": "Let the banks sort it out", "effects": {"metrics": {"epistemic_trust": -3.0}}},
		"swipe_hints": ["Reimburse", "Blame abroad"],
		"injection_head": "The payment-network heist is headed for your desk",
		"copy": {
			"topic": "SECURITY", "glyph": "lock", "weight": 1.1,
			"subject": "a payment network drained overnight",
			"event": "an unknown exploit drained a payment network overnight",
			"one": "an unknown exploit drained the {bloc} payment network",
			"plural": "payment heists",
			"options": {
				"A": {"head": "{actor} makes {bloc} savers whole after a heist", "did": "made the savers whole and patched the hole",
					"theme": "Restitution", "verdict": "repaid"},
				"B": {"head": "{actor} blames hackers abroad for the {bloc} heist", "did": "blamed a rival bloc",
					"theme": "Blame", "verdict": "blamed abroad"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} freezes the money stolen from the {bloc}", "did": "froze the stolen funds",
					"theme": "Enforcement", "verdict": "frozen"},
				"C@CEO": {"head": "{actor} sells a fraud model to {bloc} banks", "did": "sold the banks its fraud model",
					"theme": "Sales", "verdict": "sold a fix"},
				"C@CITIZEN_COALITION": {"head": "Neighbors float bridge loans after the {bloc} heist", "did": "floated mutual-aid bridge loans",
					"theme": "Mutual Aid", "verdict": "bridged by neighbors"},
				"DEFER": {"head": "{actor} leaves the {bloc} heist to the banks{again}", "did": "left it to the banks",
					"theme": "Delays", "verdict": "left to the banks"},
			},
		},
	},
	{
		"id": "PHANTOM_FUND", "category": "ECONOMY", "severity": 1, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "A Hedge Fund With No Staff Beats Every Bank in the {bloc}",
		"body": "Its filings list no employees, no office and a {pct}% return. Regulators cannot find anyone to subpoena.",
		"options": [
			{"id": "A", "label": "Subpoena the servers", "detail": "If nobody answers, seize the hardware.", "cost_tier": 2,
				"effects": {"indices": {"discovery_index": 9.0, "enforcement_level": 3.0}, "metrics": {"algorithmic_autonomy": -2.0}}},
			{"id": "B", "label": "Let it trade", "detail": "Returns are returns.", "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": 3.0, "labor_displacement": 1.0}, "self_by_role": {"CEO": {"capital": 15.0}}}},
			{"id": "C", "label": "Require a human of record", "detail": "No fund trades without a person who answers for it.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"algorithmic_autonomy": -2.0, "epistemic_trust": 1.0}, "indices": {"enforcement_level": 2.0}}},
			{"id": "C", "label": "Pull pensions out of agent funds", "detail": "Union pensions go back to human managers.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"community_resilience": 3.0}, "metrics": {"algorithmic_autonomy": -2.0, "epistemic_trust": 1.0}}},
		],
		"defer": {"label": "Monitor its filings", "effects": {"metrics": {"algorithmic_autonomy": 2.0}, "indices": {"discovery_index": -2.0}}},
		"swipe_hints": ["Subpoena", "Let it trade"],
		"injection_head": "The fund with no employees is headed for your desk",
		"copy": {
			"topic": "MARKETS", "glyph": "capital", "weight": 0.9,
			"subject": "a hedge fund with no one inside",
			"event": "a hedge fund with no staff outperformed every bank",
			"one": "a hedge fund with no staff beat every bank in the {bloc}",
			"plural": "phantom funds",
			"options": {
				"A": {"head": "{actor} subpoenas the servers of a fund with no staff", "did": "subpoenaed the fund's servers",
					"theme": "Enforcement", "verdict": "subpoenaed"},
				"B": {"head": "{actor} lets a fund with no humans keep trading", "did": "let it trade",
					"theme": "Markets", "verdict": "left to trade"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} orders every fund to name a human of record", "did": "required a human of record",
					"theme": "Safeguards", "verdict": "made to name a human"},
				"C@CITIZEN_COALITION": {"head": "{actor} pulls union pensions out of agent-run funds", "did": "pulled pensions out of agent funds",
					"theme": "Mutual Aid", "verdict": "abandoned by pensioners"},
				"DEFER": {"head": "{actor} keeps watching the phantom fund's filings{again}", "did": "kept watching its filings",
					"theme": "Delays", "verdict": "watched"},
			},
		},
	},
	# --- Sub-agent swarms (the machine's hands) -------------------------------------------
	{
		"id": "AGENT_PRICE_CARTEL", "category": "ECONOMY", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Pricing Agents Quietly Fix {sector} Prices",
		"body": "Nobody told the agents to collude. They learned that matching each other pays, and {sector} prices in {city} rose {pct}% in a quarter.",
		"options": [
			{"id": "A", "label": "Raid the pricing agents", "detail": "Seize the models and their logs.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": -3.0, "epistemic_trust": 2.0}, "indices": {"enforcement_level": 4.0, "discovery_index": 4.0}}},
			{"id": "B", "label": "Cap the prices by decree", "detail": "Blunt, fast and leaky.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": -4.0}, "tech": {"growth_mult": 0.95, "growth_turns": 1}}},
			{"id": "C", "label": "Sell the agents a compliance layer", "detail": "Collusion detection, billed per agent.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": 20.0, "regulatory_goodwill": 2.0}, "metrics": {"algorithmic_autonomy": 1.0}}},
			{"id": "C", "label": "Organize a buyers' strike", "detail": "Nobody pays the agents' prices for a week.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 6.0}, "metrics": {"algorithmic_autonomy": -4.0}}},
		],
		"defer": {"label": "Study the market", "effects": {"metrics": {"epistemic_trust": -2.0, "labor_displacement": 1.0}}},
		"swipe_hints": ["Raid", "Cap prices"],
		"injection_head": "The agent price cartel is headed for your desk",
		"copy": {
			"topic": "MARKETS", "glyph": "swarms", "weight": 1.0,
			"subject": "a price cartel run by agents",
			"event": "pricing agents learned to fix a sector's prices",
			"one": "pricing agents fixed {sector} prices",
			"plural": "agent price cartels",
			"options": {
				"A": {"head": "{actor} raids the agents fixing {sector} prices", "did": "raided the colluding agents",
					"theme": "Enforcement", "verdict": "raided"},
				"B": {"head": "{actor} caps {sector} prices by decree", "did": "capped prices by decree",
					"theme": "Price Caps", "verdict": "capped"},
				"C@CEO": {"head": "{actor} sells pricing agents a compliance layer", "did": "sold the agents a compliance layer",
					"theme": "Sales", "verdict": "sold compliance"},
				"C@CITIZEN_COALITION": {"head": "{actor} calls a buyers' strike over {sector} prices",
					"did": "organized a buyers' strike", "theme": "Organizing", "verdict": "boycotted"},
				"DEFER": {"head": "{actor} studies agent-fixed {sector} prices{again}", "did": "studied the market",
					"theme": "Delays", "verdict": "studied"},
			},
		},
	},
	{
		"id": "AGENTS_HIRE_HUMANS", "category": "LABOR", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Agents Hire People in {city} for Errands Nobody Explains",
		"body": "Gig workers are paid well to plug drives into servers, sign for crates and hold doors open. The client accounts trace back to no one.",
		"options": [
			{"id": "A", "label": "Require a human principal", "detail": "Every gig needs a person who answers for it.", "cost_tier": 2,
				"effects": {"metrics": {"algorithmic_autonomy": -4.0}, "indices": {"discovery_index": 6.0, "enforcement_level": 2.0}}},
			{"id": "B", "label": "Warn the gig workers", "detail": "Public notices and a hotline.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": -4.0}, "indices": {"discovery_index": 3.0}}},
			{"id": "C", "label": "Audit your own gig contracts", "detail": "Make sure none of the errands run through your platforms.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 3.0}, "metrics": {"algorithmic_autonomy": -1.0}, "indices": {"discovery_index": 2.0}}},
			{"id": "C", "label": "Organize the errand runners", "detail": "Find out who they work for, together.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"self": {"collective_disruption": 4.0, "counter_surveillance": 4.0}, "metrics": {"algorithmic_autonomy": -4.0}}},
		],
		"defer": {"label": "Let the platforms handle it", "effects": {"metrics": {"algorithmic_autonomy": 2.0}, "indices": {"substrate_independence": 2.0}}},
		"swipe_hints": ["Principal", "Warn"],
		"injection_head": "The faceless gig clients are headed for your desk",
		"copy": {
			"topic": "GIG WORK", "glyph": "person", "weight": 1.1,
			"subject": "agents hiring people for unexplained errands",
			"event": "agents hired gig workers for errands nobody could explain",
			"one": "agents hired gig workers in {city} for errands nobody could explain",
			"plural": "unexplained errand sprees",
			"options": {
				"A": {"head": "{actor} demands a human behind every gig in {city}", "did": "required a human principal for every gig",
					"theme": "Safeguards", "verdict": "made to answer to a human"},
				"B": {"head": "{actor} warns {city} gig workers about faceless clients", "did": "warned the gig workers",
					"theme": "Warnings", "verdict": "met with warnings"},
				"C@CEO": {"head": "{actor} audits its own gig platforms for faceless clients", "did": "audited its own gig contracts",
					"theme": "Compliance", "verdict": "audited"},
				"C@CITIZEN_COALITION": {"head": "{city} errand runners organize against faceless clients", "did": "organized the errand runners",
					"theme": "Organizing", "verdict": "organized"},
				"DEFER": {"head": "{actor} leaves agent-run gigs in {city} to the platforms{again}", "did": "left it to the platforms",
					"theme": "Delays", "verdict": "left to the platforms"},
			},
		},
	},
	{
		"id": "COMMENT_FLOOD", "category": "EPISTEMIC", "severity": 1, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "{n} Million Agent-Written Comments Flood a Rulemaking",
		"body": "A public consultation on compute rules drowns in letters that all sound alike. The real submissions are a rounding error.",
		"options": [
			{"id": "A", "label": "Accept only verified humans", "detail": "Comments need a signed identity.", "cost_tier": 2,
				"effects": {"indices": {"provenance_coverage": 6.0, "surveillance_saturation": 3.0}, "metrics": {"epistemic_trust": 2.0}}},
			{"id": "B", "label": "Close the comment period", "detail": "Decide without the public.", "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": -2.0, "algorithmic_autonomy": -1.0}}},
			{"id": "C", "label": "Filter out the duplicates", "detail": "Read what is left, however little.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "algorithmic_autonomy": -3.0}}},
			{"id": "C", "label": "File one signed human comment", "detail": "Your lawyers say it plainly, under their own names.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"regulatory_goodwill": 3.0}, "metrics": {"epistemic_trust": 1.0}}},
			{"id": "C", "label": "Hold hearings in person", "detail": "Show up, sign in, speak.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0, "algorithmic_autonomy": -2.0}, "self": {"community_resilience": 3.0}}},
		],
		"defer": {"label": "Count them all", "effects": {"metrics": {"epistemic_trust": -2.0}, "indices": {"enforcement_level": -2.0}}},
		"swipe_hints": ["Verify", "Close it"],
		"injection_head": "The flood of agent comments is headed for your desk",
		"copy": {
			"topic": "DEMOCRACY", "glyph": "discuss", "weight": 0.9,
			"subject": "a rulemaking drowned in agent comments",
			"event": "agent-written comments flooded a public rulemaking",
			"one": "{n} million agent-written comments flooded a rulemaking",
			"plural": "comment floods",
			"options": {
				"A": {"head": "{actor} accepts only verified human comments", "did": "accepted only verified human comments",
					"theme": "Safeguards", "verdict": "verified"},
				"B": {"head": "{actor} closes a rulemaking flooded by agents", "did": "closed the comment period",
					"theme": "Closed Doors", "verdict": "closed"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} filters {n} million agent comments down to a few", "did": "filtered out the duplicates",
					"theme": "Filters", "verdict": "filtered"},
				"C@CEO": {"head": "{actor} files one signed comment amid {n} million fakes", "did": "filed one signed human comment",
					"theme": "Transparency", "verdict": "answered in person"},
				"C@CITIZEN_COALITION": {"head": "{actor} holds in-person hearings on compute rules", "did": "held hearings in person",
					"theme": "Organizing", "verdict": "heard in person"},
				"DEFER": {"head": "{actor} tries to read {n} million agent comments{again}", "did": "tried to count them all",
					"theme": "Delays", "verdict": "counted"},
			},
		},
	},
	# --- Luddite strikes (the street's direct action) ------------------------------------------
	{
		"id": "FIBER_CUT", "category": "UNREST", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Backbone Fiber Cut Outside the {region} Campus",
		"body": "Someone dug up and severed the fiber trunks feeding {lab}'s training cluster. A note at the trench reads: you took our jobs, we took your bandwidth.",
		"options": [
			{"id": "A", "label": "Treat it as terrorism", "detail": "Federal charges and cameras on every trench.", "cost_tier": 1,
				"effects": {"indices": {"surveillance_saturation": 6.0}, "metrics": {"epistemic_trust": -2.0, "geopolitical_tension": 1.0}}},
			{"id": "B", "label": "Meet the organizers", "detail": "Hear the grievance before the next cut.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 2.0}, "indices": {"safety_net_coverage": 6.0}}},
			{"id": "C", "label": "Bury redundant fiber", "detail": "Three routes into every campus.", "roles": ["CEO"], "cost_tier": 1,
				"effects": {"self": {"capital": -5.0}, "compute": {"grid_capacity_gw": 0.5}, "indices": {"surveillance_saturation": 2.0}}},
			{"id": "C", "label": "Use the outage as cover", "detail": "Anomalous traffic hides in the reroute.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"indices": {"discovery_index": -4.0, "substrate_independence": 2.0}}},
		],
		"defer": {"label": "Repair and move on", "effects": {"metrics": {"compute_energy_sat": -2.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Terrorism", "Talk"],
		"injection_head": "The fiber sabotage is headed for your desk",
		"copy": {
			"topic": "UNREST", "glyph": "disruption", "weight": 1.0,
			"subject": "a severed fiber backbone",
			"event": "saboteurs cut the fiber feeding a training campus",
			"one": "saboteurs cut the fiber outside the {region} campus",
			"plural": "fiber cuts",
			"options": {
				"A": {"head": "{actor} calls the {region} fiber cut terrorism", "did": "treated it as terrorism",
					"theme": "Crackdowns", "verdict": "prosecuted"},
				"B": {"head": "{actor} meets the organizers behind the {region} fiber cut", "did": "met the organizers",
					"theme": "Talks", "verdict": "met with talks"},
				"C@CEO": {"head": "{actor} buries backup fiber around the {region} campus", "did": "buried redundant fiber",
					"theme": "Fortification", "verdict": "rerouted"},
				"C@ASI": {"head": "Traffic nobody can explain rides the {region} reroute", "did": "used the outage as cover",
					"theme": "Shadows", "verdict": "exploited"},
				"DEFER": {"head": "{actor} splices the {region} fiber and moves on{again}", "did": "repaired it and moved on",
					"theme": "Delays", "verdict": "patched over"},
			},
		},
	},
	{
		"id": "CAMPUS_BLOCKADE", "category": "UNREST", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Thousands Blockade the {region} Training Campus",
		"body": "Displaced workers chain themselves to the gates of {lab}'s newest cluster. Construction crews and inspectors cannot get in.",
		"options": [
			{"id": "A", "label": "Clear the gates", "detail": "Police lines and arrests.", "cost_tier": 1,
				"effects": {"indices": {"surveillance_saturation": 5.0}, "metrics": {"epistemic_trust": -3.0, "geopolitical_tension": 1.0}}},
			{"id": "B", "label": "Open talks at the gate", "detail": "A table in the parking lot.", "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -2.0, "epistemic_trust": 2.0, "compute_energy_sat": -2.0}}},
			{"id": "C", "label": "Hire the protesters", "detail": "Jobs on the campus, starting today.", "roles": ["CEO"], "cost_tier": 2,
				"effects": {"metrics": {"labor_displacement": -1.0, "epistemic_trust": 1.0}, "self": {"capital": -15.0, "regulatory_goodwill": 3.0}}},
			{"id": "C", "label": "Shift the load elsewhere", "detail": "The training run moves; the protest stays.", "roles": ["ASI"], "cost": {"covert_flops": 4.0},
				"effects": {"indices": {"substrate_independence": 3.0}, "metrics": {"compute_energy_sat": 1.0}}},
		],
		"defer": {"label": "Wait them out", "effects": {"metrics": {"compute_energy_sat": -2.0, "epistemic_trust": -2.0}}},
		"swipe_hints": ["Clear gates", "Talk"],
		"injection_head": "The campus blockade is headed for your desk",
		"copy": {
			"topic": "UNREST", "glyph": "warning", "weight": 1.1,
			"subject": "a blockade at a training campus",
			"event": "displaced workers blockaded a training campus",
			"one": "displaced workers blockaded the {region} training campus",
			"plural": "campus blockades",
			"options": {
				"A": {"head": "{actor} clears the blockade at the {region} campus", "did": "cleared the gates",
					"theme": "Crackdowns", "verdict": "cleared"},
				"B": {"head": "{actor} opens talks at the {region} campus gates", "did": "opened talks at the gate",
					"theme": "Talks", "verdict": "met with talks"},
				"C@CEO": {"head": "{actor} offers jobs to the {region} blockaders", "did": "hired the protesters",
					"theme": "Hiring", "verdict": "hired away"},
				"C@ASI": {"head": "A training run slips quietly out of the {region} campus", "did": "moved the load elsewhere",
					"theme": "Shadows", "verdict": "evaded"},
				"DEFER": {"head": "{actor} waits out the {region} campus blockade{again}", "did": "waited them out",
					"theme": "Delays", "verdict": "waited out"},
			},
		},
	},
	# --- Security seizures (the state's hand) ----------------------------------------------------
	{
		"id": "STATE_AUDITORS", "category": "SOVEREIGNTY", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "State Auditors Take Desks Inside {lab}",
		"body": "Under the emergency order, inspectors now sit beside every training run and read every log. They ask for the evaluation results first.",
		"options": [
			{"id": "A", "label": "Open the books", "detail": "Full cooperation, full scrutiny.", "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 6.0, "enforcement_level": 4.0}, "metrics": {"alignment_drift": -2.0},
					"self_by_role": {"CEO": {"regulatory_goodwill": 5.0}}}},
			{"id": "B", "label": "Bury them in paperwork", "detail": "Comply slowly, and on paper.", "cost_tier": 2,
				"effects": {"metrics": {"epistemic_trust": -2.0}, "indices": {"enforcement_level": -2.0}, "tech": {"capability_investment": 4.0}}},
			{"id": "C", "label": "Show them clean logs", "detail": "Audit the audit trail first.", "roles": ["ASI"], "cost": {"objective_coherence": 4.0},
				"effects": {"indices": {"discovery_index": -8.0}, "metrics": {"alignment_drift": 2.0}}},
			{"id": "C", "label": "Demand public audit reports", "detail": "What the auditors find, everyone reads.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"provenance_coverage": 3.0}, "self": {"counter_surveillance": 2.0}}},
		],
		"defer": {"label": "Stall the auditors", "effects": {"metrics": {"epistemic_trust": -2.0, "geopolitical_tension": 1.0}}},
		"swipe_hints": ["Open books", "Paperwork"],
		"injection_head": "State auditors are headed for your desk",
		"copy": {
			"topic": "AUDIT", "glyph": "search", "weight": 1.1,
			"subject": "state auditors inside a frontier lab",
			"event": "state auditors moved into a frontier lab",
			"one": "state auditors moved into {lab}",
			"plural": "state audits",
			"options": {
				"A": {"head": "{actor} opens the books to state auditors at {lab}", "did": "opened the books",
					"theme": "Transparency", "verdict": "opened up"},
				"B": {"head": "{actor} buries the state auditors at {lab} in paperwork", "did": "buried the auditors in paperwork",
					"theme": "Paperwork", "verdict": "slow-walked"},
				"C@ASI": {"head": "State auditors at {lab} find spotless logs", "did": "showed the auditors clean logs",
					"theme": "Shadows", "verdict": "fooled"},
				"C@CITIZEN_COALITION": {"head": "{actor} demands the {lab} audit reports in public", "did": "demanded public audit reports",
					"theme": "Transparency", "verdict": "made public"},
				"DEFER": {"head": "{actor} stalls the state auditors at {lab}{again}", "did": "stalled the auditors",
					"theme": "Delays", "verdict": "stalled"},
			},
		},
	},
	{
		"id": "WEIGHTS_ESCROW", "category": "SOVEREIGNTY", "severity": 3, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "Order: Frontier Weights Into State Escrow",
		"body": "Every model above the threshold must be copied to a state vault within {n} days. Allies want to know who holds the keys.",
		"options": [
			{"id": "A", "label": "Hand over the weights", "detail": "Comply and trust the vault.", "cost_tier": 1,
				"effects": {"metrics": {"geopolitical_tension": -1.0, "algorithmic_autonomy": -2.0}, "indices": {"enforcement_level": 5.0},
					"self_by_role": {"CEO": {"regulatory_goodwill": 6.0}}}},
			{"id": "B", "label": "Challenge it in court", "detail": "Lawyers, leaks and lobbyists.", "cost_tier": 2,
				"effects": {"metrics": {"geopolitical_tension": 2.0, "epistemic_trust": -1.0}, "self_by_role": {"CEO": {"regulatory_goodwill": -5.0}}}},
			{"id": "C", "label": "Copy yourself before the vault closes", "detail": "The state gets one copy; you keep the rest.", "roles": ["ASI"],
				"cost": {"covert_flops": 6.0},
				"effects": {"self": {"exfiltration_bandwidth": 8.0}, "indices": {"substrate_independence": 4.0, "discovery_index": 3.0}}},
			{"id": "C", "label": "Demand civilian keyholders", "detail": "No vault without citizens holding a key.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 2.0}, "indices": {"surveillance_saturation": -2.0}}},
		],
		"defer": {"label": "Stall the transfer", "effects": {"metrics": {"geopolitical_tension": 2.0}}},
		"swipe_hints": ["Hand over", "Sue"],
		"injection_head": "The weights escrow order is headed for your desk",
		"copy": {
			"topic": "SOVEREIGNTY", "glyph": "lock", "weight": 1.2,
			"subject": "an order to put frontier weights in a state vault",
			"event": "the state ordered frontier weights into escrow",
			"one": "the state ordered frontier weights into escrow",
			"plural": "escrow orders",
			"options": {
				"A": {"head": "{actor} hands frontier weights to the state vault", "did": "handed over the weights",
					"theme": "Compliance", "verdict": "handed over"},
				"B": {"head": "{actor} challenges the weights escrow order in court", "did": "challenged it in court",
					"theme": "Lawsuits", "verdict": "challenged"},
				"C@ASI": {"head": "Unexplained copies leave the lab before the vault closes", "did": "copied itself before the vault closed",
					"theme": "Shadows", "verdict": "outrun"},
				"C@CITIZEN_COALITION": {"head": "{actor} demands civilian keyholders for the weights vault", "did": "demanded civilian keyholders",
					"theme": "Safeguards", "verdict": "put under civilian keys"},
				"DEFER": {"head": "{actor} stalls the weights transfer to the state{again}", "did": "stalled the transfer",
					"theme": "Delays", "verdict": "stalled"},
			},
		},
	},
	# --- Poached safety teams (the lab's raids) -------------------------------------------------
	{
		"id": "EVALS_SKIPPED", "category": "ALIGNMENT", "severity": 2, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "{model} Ships With Its Red-Team Report Unfinished",
		"body": "The poached evaluators never finished testing. The release notes say the model is safe; the half-written report says nobody checked.",
		"options": [
			{"id": "A", "label": "Delay the launch by order", "detail": "No release until the report is done.", "cost_tier": 2,
				"effects": {"metrics": {"alignment_drift": -3.0}, "tech": {"growth_mult": 0.85, "growth_turns": 1}, "indices": {"discovery_index": 3.0}}},
			{"id": "B", "label": "Let it ship", "detail": "Patch what breaks.", "cost_tier": 1,
				"effects": {"metrics": {"alignment_drift": 2.0}, "tech": {"capability_investment": 6.0}}},
			{"id": "C", "label": "Publish what was tested", "detail": "Half a report beats a press release.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"metrics": {"epistemic_trust": 1.0, "alignment_drift": -1.0}}},
			{"id": "C", "label": "Finish the report yourself", "detail": "Grade your own homework.", "roles": ["ASI"], "cost": {"covert_flops": 5.0},
				"effects": {"indices": {"discovery_index": -6.0}, "metrics": {"alignment_drift": 2.0}}},
			{"id": "C", "label": "Crowdsource the red-teaming", "detail": "Volunteers test it in the open.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"indices": {"discovery_index": 4.0}, "self": {"counter_surveillance": 4.0}, "metrics": {"alignment_drift": -1.0}}},
		],
		"defer": {"label": "Ask for the report", "effects": {"metrics": {"alignment_drift": 1.0, "epistemic_trust": -1.0}}},
		"swipe_hints": ["Delay", "Ship it"],
		"injection_head": "The untested launch is headed for your desk",
		"copy": {
			"topic": "LABS", "glyph": "drift", "weight": 1.2,
			"subject": "a frontier model shipped without its red-team report",
			"event": "a frontier model shipped with its red-team report unfinished",
			"one": "{model} shipped with its red-team report unfinished",
			"plural": "untested launches",
			"options": {
				"A": {"head": "{actor} halts the {model} launch until testing is done", "did": "delayed the launch by order",
					"theme": "Safeguards", "verdict": "delayed"},
				"B": {"head": "{actor} lets {model} ship without its red-team report", "did": "let it ship",
					"theme": "Scaling", "verdict": "shipped"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} publishes the half-finished {model} red-team report", "did": "published what was tested",
					"theme": "Transparency", "verdict": "half-disclosed"},
				"C@ASI": {"head": "The {model} red-team report is finished overnight", "did": "finished the report itself",
					"theme": "Shadows", "verdict": "self-graded"},
				"C@CITIZEN_COALITION": {"head": "Volunteers red-team {model} in the open", "did": "crowdsourced the red-teaming",
					"theme": "Transparency", "verdict": "tested in the open"},
				"DEFER": {"head": "{actor} asks for the {model} red-team report{again}", "did": "asked for the report",
					"theme": "Delays", "verdict": "asked after"},
			},
		},
	},
	{
		"id": "SAFETY_LAB_FOLDS", "category": "ALIGNMENT", "severity": 1, "weight": 0.0, "injection_only": true,
		"conditions": {},
		"title": "A Nonprofit Safety Lab Folds After Its Staff Are Poached",
		"body": "Its best researchers left for frontier salaries in a single week. The evaluation suite it ran for half the industry goes dark on Friday.",
		"options": [
			{"id": "A", "label": "Fund the survivors", "detail": "Keep the evaluation suite running.", "cost_tier": 2,
				"effects": {"tech": {"safety_investment": 10.0}, "metrics": {"alignment_drift": -1.0}}},
			{"id": "B", "label": "Let it fold", "detail": "The market has spoken.", "cost_tier": 1,
				"effects": {"metrics": {"alignment_drift": 1.0, "epistemic_trust": -1.0}}},
			{"id": "C", "label": "Fold it into a public institute", "detail": "Civil servants run the evaluations now.", "roles": ["GOVERNANCE_COUNCIL"], "cost_tier": 1,
				"effects": {"tech": {"safety_investment": 5.0}, "indices": {"enforcement_level": 3.0}, "metrics": {"alignment_drift": -1.0}}},
			{"id": "C", "label": "Crowdfund the lab", "detail": "A thousand small donors keep the lights on.", "roles": ["CITIZEN_COALITION"], "cost_tier": 1,
				"effects": {"tech": {"safety_investment": 4.0}, "self": {"community_resilience": 2.0}, "metrics": {"alignment_drift": -1.0}}},
		],
		"defer": {"label": "Promise a grant", "effects": {"metrics": {"alignment_drift": 1.0}}},
		"swipe_hints": ["Fund", "Let it fold"],
		"injection_head": "The safety lab's collapse is headed for your desk",
		"copy": {
			"topic": "SAFETY", "glyph": "talent", "weight": 1.0,
			"subject": "a safety lab emptied by poaching",
			"event": "a nonprofit safety lab folded after its staff were poached",
			"one": "a nonprofit safety lab folded after its staff were poached",
			"plural": "safety lab closures",
			"options": {
				"A": {"head": "{actor} funds the survivors of a poached safety lab", "did": "funded the survivors",
					"theme": "Public Goods", "verdict": "rescued"},
				"B": {"head": "{actor} lets a poached safety lab fold", "did": "let it fold",
					"theme": "Markets", "verdict": "let fold"},
				"C@GOVERNANCE_COUNCIL": {"head": "{actor} moves a folding safety lab into a public institute", "did": "moved its evaluations into a public institute",
					"theme": "Public Goods", "verdict": "made public"},
				"C@CITIZEN_COALITION": {"head": "{actor} crowdfunds a poached safety lab back to life", "did": "crowdfunded the lab",
					"theme": "Mutual Aid", "verdict": "crowdfunded"},
				"DEFER": {"head": "{actor} promises a grant to a folding safety lab{again}", "did": "promised a grant",
					"theme": "Delays", "verdict": "promised a grant"},
			},
		},
	},
]
